// Bộ thủ chữ Hán 214 — dữ liệu cho flashcard
// 214 bộ thủ → 22 ngày, 10 bộ/ngày (ngày 22 có 4 bộ)

const FULL_DAYS = [
  {
    id: 1,
    hsk: 1,
    theme: "Bộ thủ 1-10",
    themeZh: "部首 1-10",
    cards: [
      { type: "1 nét", word: "一", pinyin: "yī", meaning: "NHẤT — Số 1, nét ngang", example: { zh: "五", pinyin: "wǔ", vi: "số năm" } },
      { type: "1 nét", word: "丨", pinyin: "gǔn", meaning: "CỔN — Nét sổ dọc", example: { zh: "中", pinyin: "zhōng", vi: "giữa, trung" } },
      { type: "1 nét", word: "丶", pinyin: "zhǔ", meaning: "CHỦ — Nét chấm, điểm", example: { zh: "主", pinyin: "zhǔ", vi: "chủ, chính" } },
      { type: "1 nét", word: "丿", pinyin: "piě", meaning: "PHIỆT — Nét xiên qua trái", example: { zh: "久", pinyin: "jiǔ", vi: "lâu" } },
      { type: "1 nét", word: "乙 (乚)", pinyin: "yǐ", meaning: "ẤT — Vị trí thứ hai trong thiên can", example: { zh: "九", pinyin: "jiǔ", vi: "số chín" } },
      { type: "1 nét", word: "亅", pinyin: "jué", meaning: "QUYẾT — Nét sổ có móc", example: { zh: "了", pinyin: "le", vi: "(trợ từ)" } },
      { type: "2 nét", word: "二", pinyin: "èr", meaning: "NHỊ — Số 2", example: { zh: "二", pinyin: "èr", vi: "số hai" } },
      { type: "2 nét", word: "亠", pinyin: "tóu", meaning: "ĐẦU — (không có nghĩa cụ thể)", example: { zh: "京", pinyin: "jīng", vi: "kinh đô" } },
      { type: "2 nét", word: "人 (亻)", pinyin: "rén", meaning: "NHÂN — Người", example: { zh: "你", pinyin: "nǐ", vi: "bạn" } },
      { type: "2 nét", word: "儿", pinyin: "ér", meaning: "NHÂN — Người (chân người)", example: { zh: "儿子", pinyin: "érzi", vi: "con trai" } },
    ],
  },
  {
    id: 2,
    hsk: 1,
    theme: "Bộ thủ 11-20",
    themeZh: "部首 11-20",
    cards: [
      { type: "2 nét", word: "入", pinyin: "rù", meaning: "NHẬP — Nhập, vào", example: { zh: "入口", pinyin: "rùkǒu", vi: "lối vào" } },
      { type: "2 nét", word: "八", pinyin: "bā", meaning: "BÁT — Số 8", example: { zh: "分", pinyin: "fēn", vi: "phân, chia" } },
      { type: "2 nét", word: "冂", pinyin: "jiōng", meaning: "QUYNH — Vùng biên giới xa, hoang địa", example: { zh: "内", pinyin: "nèi", vi: "trong" } },
      { type: "2 nét", word: "冖", pinyin: "mì", meaning: "MỊCH — Trùm khăn lên đầu", example: { zh: "写", pinyin: "xiě", vi: "viết" } },
      { type: "2 nét", word: "冫", pinyin: "bīng", meaning: "BĂNG — Nước đá, băng tuyết", example: { zh: "冷", pinyin: "lěng", vi: "lạnh" } },
      { type: "2 nét", word: "几", pinyin: "jī", meaning: "KỶ — Cái bàn nhỏ, cái ghế", example: { zh: "几", pinyin: "jǐ", vi: "mấy" } },
      { type: "2 nét", word: "凵", pinyin: "kǎn", meaning: "KHẢM — Há miệng", example: { zh: "凶", pinyin: "xiōng", vi: "hung, dữ" } },
      { type: "2 nét", word: "刀 (刂)", pinyin: "dāo", meaning: "ĐAO — Con dao, cây đao", example: { zh: "分", pinyin: "fēn", vi: "phân chia" } },
      { type: "2 nét", word: "力", pinyin: "lì", meaning: "LỰC — Sức mạnh, sức lực", example: { zh: "努力", pinyin: "nǔlì", vi: "nỗ lực" } },
      { type: "2 nét", word: "勹", pinyin: "bāo", meaning: "BAO — Bao bọc", example: { zh: "包", pinyin: "bāo", vi: "bao, gói" } },
    ],
  },
  {
    id: 3,
    hsk: 1,
    theme: "Bộ thủ 21-30",
    themeZh: "部首 21-30",
    cards: [
      { type: "2 nét", word: "匕", pinyin: "bǐ", meaning: "CHỦY — Cái thìa (cái muỗng)", example: { zh: "化", pinyin: "huà", vi: "biến hóa" } },
      { type: "2 nét", word: "匚", pinyin: "fāng", meaning: "PHƯƠNG — Tủ đựng", example: { zh: "区", pinyin: "qū", vi: "khu vực" } },
      { type: "2 nét", word: "匸", pinyin: "xǐ", meaning: "HỆ — Che đậy, giấu giếm", example: { zh: "医", pinyin: "yī", vi: "y, bác sĩ" } },
      { type: "2 nét", word: "十", pinyin: "shí", meaning: "THẬP — Số 10", example: { zh: "十", pinyin: "shí", vi: "mười" } },
      { type: "2 nét", word: "卜", pinyin: "bǔ", meaning: "BỐC — Xem bói", example: { zh: "卡", pinyin: "kǎ", vi: "thẻ" } },
      { type: "2 nét", word: "卩", pinyin: "jié", meaning: "TIẾT — Cái ấn, dấu", example: { zh: "印", pinyin: "yìn", vi: "in, dấu" } },
      { type: "2 nét", word: "厂", pinyin: "hǎn", meaning: "HÁN/XƯỞNG — Sườn núi, vách đá", example: { zh: "厂", pinyin: "chǎng", vi: "nhà máy" } },
      { type: "2 nét", word: "厶", pinyin: "sī", meaning: "KHƯ/TƯ — Riêng tư", example: { zh: "去", pinyin: "qù", vi: "đi" } },
      { type: "2 nét", word: "又", pinyin: "yòu", meaning: "HỰU — Lại nữa, bàn tay", example: { zh: "友", pinyin: "yǒu", vi: "bạn" } },
      { type: "3 nét", word: "口", pinyin: "kǒu", meaning: "KHẨU — Cái miệng", example: { zh: "吃", pinyin: "chī", vi: "ăn" } },
    ],
  },
  {
    id: 4,
    hsk: 1,
    theme: "Bộ thủ 31-40",
    themeZh: "部首 31-40",
    cards: [
      { type: "3 nét", word: "囗", pinyin: "wéi", meaning: "VI — Vây quanh", example: { zh: "国", pinyin: "guó", vi: "quốc gia" } },
      { type: "3 nét", word: "土", pinyin: "tǔ", meaning: "THỔ — Đất", example: { zh: "地", pinyin: "dì", vi: "đất" } },
      { type: "3 nét", word: "士", pinyin: "shì", meaning: "SĨ — Kẻ sĩ", example: { zh: "士", pinyin: "shì", vi: "kẻ sĩ" } },
      { type: "3 nét", word: "夂", pinyin: "zhǐ", meaning: "TRĨ — Theo sau mà đến", example: { zh: "处", pinyin: "chù", vi: "nơi" } },
      { type: "3 nét", word: "夊", pinyin: "suī", meaning: "TUY — Đi chậm", example: { zh: "夏", pinyin: "xià", vi: "mùa hè" } },
      { type: "3 nét", word: "夕", pinyin: "xī", meaning: "TỊCH — Buổi tối", example: { zh: "多", pinyin: "duō", vi: "nhiều" } },
      { type: "3 nét", word: "大", pinyin: "dà", meaning: "ĐẠI — To lớn", example: { zh: "大", pinyin: "dà", vi: "to, lớn" } },
      { type: "3 nét", word: "女", pinyin: "nǚ", meaning: "NỮ — Nữ giới, con gái, đàn bà", example: { zh: "妈妈", pinyin: "māma", vi: "mẹ" } },
      { type: "3 nét", word: "子", pinyin: "zǐ", meaning: "TỬ — Con", example: { zh: "孩子", pinyin: "háizi", vi: "đứa trẻ" } },
      { type: "3 nét", word: "宀", pinyin: "mián", meaning: "MIÊN — Mái nhà, mái che", example: { zh: "家", pinyin: "jiā", vi: "nhà" } },
    ],
  },
  {
    id: 5,
    hsk: 1,
    theme: "Bộ thủ 41-50",
    themeZh: "部首 41-50",
    cards: [
      { type: "3 nét", word: "寸", pinyin: "cùn", meaning: "THỐN — Đơn vị 'tấc' (đo chiều dài)", example: { zh: "对", pinyin: "duì", vi: "đúng" } },
      { type: "3 nét", word: "小", pinyin: "xiǎo", meaning: "TIỂU — Nhỏ bé", example: { zh: "小", pinyin: "xiǎo", vi: "nhỏ" } },
      { type: "3 nét", word: "尢", pinyin: "wāng", meaning: "UÔNG — Yếu đuối, khập khiễng", example: { zh: "尤", pinyin: "yóu", vi: "nhất là" } },
      { type: "3 nét", word: "尸", pinyin: "shī", meaning: "THI — Thây, xác chết", example: { zh: "屋", pinyin: "wū", vi: "nhà, phòng" } },
      { type: "3 nét", word: "屮", pinyin: "chè", meaning: "TRIỆT — Mầm non, cỏ non mới mọc", example: { zh: "屯", pinyin: "tún", vi: "đóng quân" } },
      { type: "3 nét", word: "山", pinyin: "shān", meaning: "SƠN — Núi non", example: { zh: "山", pinyin: "shān", vi: "núi" } },
      { type: "3 nét", word: "巛 (川)", pinyin: "chuān", meaning: "XUYÊN — Sông ngòi", example: { zh: "河", pinyin: "hé", vi: "sông" } },
      { type: "3 nét", word: "工", pinyin: "gōng", meaning: "CÔNG — Người thợ, công việc", example: { zh: "工人", pinyin: "gōngrén", vi: "công nhân" } },
      { type: "3 nét", word: "己", pinyin: "jǐ", meaning: "KỶ — Bản thân mình", example: { zh: "自己", pinyin: "zìjǐ", vi: "tự mình" } },
      { type: "3 nét", word: "巾", pinyin: "jīn", meaning: "CÂN — Cái khăn", example: { zh: "毛巾", pinyin: "máojīn", vi: "khăn lông" } },
    ],
  },
  {
    id: 6,
    hsk: 1,
    theme: "Bộ thủ 51-60",
    themeZh: "部首 51-60",
    cards: [
      { type: "3 nét", word: "干", pinyin: "gān", meaning: "CAN — Phạm vào", example: { zh: "干净", pinyin: "gānjìng", vi: "sạch sẽ" } },
      { type: "3 nét", word: "幺", pinyin: "yāo", meaning: "YÊU — Nhỏ, ít", example: { zh: "幼", pinyin: "yòu", vi: "thơ ấu" } },
      { type: "3 nét", word: "广", pinyin: "yǎn", meaning: "NGHIỄM — Mái nhà", example: { zh: "广", pinyin: "guǎng", vi: "rộng" } },
      { type: "3 nét", word: "廴", pinyin: "yǐn", meaning: "DẪN — Bước dài", example: { zh: "建", pinyin: "jiàn", vi: "xây dựng" } },
      { type: "3 nét", word: "廾", pinyin: "gǒng", meaning: "CỦNG — Chắp tay", example: { zh: "开", pinyin: "kāi", vi: "mở" } },
      { type: "3 nét", word: "弋", pinyin: "yì", meaning: "DỰC — Bắn, cây cọc gỗ", example: { zh: "式", pinyin: "shì", vi: "kiểu, dạng" } },
      { type: "3 nét", word: "弓", pinyin: "gōng", meaning: "CUNG — Cây cung", example: { zh: "弟弟", pinyin: "dìdi", vi: "em trai" } },
      { type: "3 nét", word: "彐 (彑)", pinyin: "jì", meaning: "KÝ — Đầu con nhím", example: { zh: "当", pinyin: "dāng", vi: "đang, làm" } },
      { type: "3 nét", word: "彡", pinyin: "shān", meaning: "SAM — Lông tóc dài", example: { zh: "形", pinyin: "xíng", vi: "hình" } },
      { type: "3 nét", word: "彳", pinyin: "chì", meaning: "XÍCH — Bước chân trái", example: { zh: "行", pinyin: "xíng", vi: "đi, hành" } },
    ],
  },
  {
    id: 7,
    hsk: 1,
    theme: "Bộ thủ 61-70",
    themeZh: "部首 61-70",
    cards: [
      { type: "4 nét", word: "心 (忄)", pinyin: "xīn", meaning: "TÂM — Tim, tâm", example: { zh: "想", pinyin: "xiǎng", vi: "nghĩ" } },
      { type: "4 nét", word: "戈", pinyin: "gē", meaning: "QUA — Cây qua (vũ khí)", example: { zh: "我", pinyin: "wǒ", vi: "tôi" } },
      { type: "4 nét", word: "戶 (户)", pinyin: "hù", meaning: "HỘ — Cửa một cánh", example: { zh: "房", pinyin: "fáng", vi: "phòng" } },
      { type: "4 nét", word: "手 (扌)", pinyin: "shǒu", meaning: "THỦ — Tay", example: { zh: "打", pinyin: "dǎ", vi: "đánh" } },
      { type: "4 nét", word: "支", pinyin: "zhī", meaning: "CHI — Cành nhánh, chống đỡ", example: { zh: "支", pinyin: "zhī", vi: "chống đỡ" } },
      { type: "4 nét", word: "攴 (攵)", pinyin: "pū", meaning: "PHỘC — Gõ nhẹ, đánh khẽ", example: { zh: "教", pinyin: "jiāo", vi: "dạy" } },
      { type: "4 nét", word: "文", pinyin: "wén", meaning: "VĂN — Văn vẻ, văn chương", example: { zh: "文", pinyin: "wén", vi: "văn" } },
      { type: "4 nét", word: "斗", pinyin: "dǒu", meaning: "ĐẨU — Cái đấu, chọi", example: { zh: "斗", pinyin: "dòu", vi: "đấu, chọi" } },
      { type: "4 nét", word: "斤", pinyin: "jīn", meaning: "CÂN — Cái rìu, 1/2 kg", example: { zh: "新", pinyin: "xīn", vi: "mới" } },
      { type: "4 nét", word: "方", pinyin: "fāng", meaning: "PHƯƠNG — Vuông", example: { zh: "方", pinyin: "fāng", vi: "vuông" } },
    ],
  },
  {
    id: 8,
    hsk: 2,
    theme: "Bộ thủ 71-80",
    themeZh: "部首 71-80",
    cards: [
      { type: "4 nét", word: "无 (旡)", pinyin: "wú", meaning: "VÔ — Không", example: { zh: "无", pinyin: "wú", vi: "không" } },
      { type: "4 nét", word: "日", pinyin: "rì", meaning: "NHẬT — Mặt trời, ngày", example: { zh: "明", pinyin: "míng", vi: "sáng" } },
      { type: "4 nét", word: "曰", pinyin: "yuē", meaning: "VIẾT — Nói rằng", example: { zh: "曰", pinyin: "yuē", vi: "nói rằng" } },
      { type: "4 nét", word: "月", pinyin: "yuè", meaning: "NGUYỆT — Mặt trăng, tháng", example: { zh: "朋友", pinyin: "péngyǒu", vi: "bạn bè" } },
      { type: "4 nét", word: "木", pinyin: "mù", meaning: "MỘC — Cây", example: { zh: "树", pinyin: "shù", vi: "cây" } },
      { type: "4 nét", word: "欠", pinyin: "qiàn", meaning: "KHIẾM — Thiếu, nợ", example: { zh: "歌", pinyin: "gē", vi: "hát" } },
      { type: "4 nét", word: "止", pinyin: "zhǐ", meaning: "CHỈ — Dừng", example: { zh: "正", pinyin: "zhèng", vi: "đúng" } },
      { type: "4 nét", word: "歹", pinyin: "dǎi", meaning: "ĐÃI/NGẠT — Xương tàn, xấu xa", example: { zh: "死", pinyin: "sǐ", vi: "chết" } },
      { type: "4 nét", word: "殳", pinyin: "shū", meaning: "THÙ — Binh khí có cán", example: { zh: "段", pinyin: "duàn", vi: "đoạn" } },
      { type: "4 nét", word: "毋", pinyin: "wú", meaning: "VÔ — Chớ, đừng", example: { zh: "母", pinyin: "mǔ", vi: "mẹ" } },
    ],
  },
  {
    id: 9,
    hsk: 2,
    theme: "Bộ thủ 81-90",
    themeZh: "部首 81-90",
    cards: [
      { type: "4 nét", word: "比", pinyin: "bǐ", meaning: "TỶ — So sánh", example: { zh: "比", pinyin: "bǐ", vi: "so" } },
      { type: "4 nét", word: "毛", pinyin: "máo", meaning: "MAO — Lông", example: { zh: "毛", pinyin: "máo", vi: "lông" } },
      { type: "4 nét", word: "氏", pinyin: "shì", meaning: "THỊ — Họ", example: { zh: "民", pinyin: "mín", vi: "dân" } },
      { type: "4 nét", word: "气", pinyin: "qì", meaning: "KHÍ — Không khí", example: { zh: "气", pinyin: "qì", vi: "khí" } },
      { type: "4 nét", word: "水 (氵)", pinyin: "shuǐ", meaning: "THỦY — Nước", example: { zh: "河", pinyin: "hé", vi: "sông" } },
      { type: "4 nét", word: "火 (灬)", pinyin: "huǒ", meaning: "HỎA — Lửa", example: { zh: "热", pinyin: "rè", vi: "nóng" } },
      { type: "4 nét", word: "爪 (爫)", pinyin: "zhǎo", meaning: "TRẢO — Móng vuốt", example: { zh: "爬", pinyin: "pá", vi: "bò, leo" } },
      { type: "4 nét", word: "父", pinyin: "fù", meaning: "PHỤ — Cha", example: { zh: "父亲", pinyin: "fùqīn", vi: "cha, bố" } },
      { type: "4 nét", word: "爻", pinyin: "yáo", meaning: "HÀO — Hào âm hào dương (Kinh Dịch)", example: { zh: "爽", pinyin: "shuǎng", vi: "thoải mái" } },
      { type: "4 nét", word: "爿 (丬)", pinyin: "qiáng", meaning: "TƯỜNG — Mảnh gỗ, cái giường", example: { zh: "床", pinyin: "chuáng", vi: "giường" } },
    ],
  },
  {
    id: 10,
    hsk: 2,
    theme: "Bộ thủ 91-100",
    themeZh: "部首 91-100",
    cards: [
      { type: "4 nét", word: "片", pinyin: "piàn", meaning: "PHIẾN — Mảnh, tấm, miếng", example: { zh: "照片", pinyin: "zhàopiàn", vi: "bức ảnh" } },
      { type: "4 nét", word: "牙", pinyin: "yá", meaning: "NHA — Răng nanh", example: { zh: "牙齿", pinyin: "yáchǐ", vi: "răng" } },
      { type: "4 nét", word: "牛 (牜)", pinyin: "niú", meaning: "NGƯU — Con trâu, bò", example: { zh: "牛奶", pinyin: "niúnǎi", vi: "sữa bò" } },
      { type: "4 nét", word: "犬 (犭)", pinyin: "quǎn", meaning: "KHUYỂN — Con chó", example: { zh: "狗", pinyin: "gǒu", vi: "con chó" } },
      { type: "5 nét", word: "玄", pinyin: "xuán", meaning: "HUYỀN — Đen huyền, huyền bí", example: { zh: "玄", pinyin: "xuán", vi: "huyền bí" } },
      { type: "5 nét", word: "玉 (王)", pinyin: "yù", meaning: "NGỌC — Đá quý, ngọc", example: { zh: "玉", pinyin: "yù", vi: "ngọc" } },
      { type: "5 nét", word: "瓜", pinyin: "guā", meaning: "QUA — Quả dưa", example: { zh: "西瓜", pinyin: "xīguā", vi: "dưa hấu" } },
      { type: "5 nét", word: "瓦", pinyin: "wǎ", meaning: "NGÕA — Ngói", example: { zh: "瓦", pinyin: "wǎ", vi: "ngói" } },
      { type: "5 nét", word: "甘", pinyin: "gān", meaning: "CAM — Ngọt", example: { zh: "甜", pinyin: "tián", vi: "ngọt" } },
      { type: "5 nét", word: "生", pinyin: "shēng", meaning: "SINH — Sinh đẻ, sinh sống", example: { zh: "生日", pinyin: "shēngrì", vi: "sinh nhật" } },
    ],
  },
  {
    id: 11,
    hsk: 2,
    theme: "Bộ thủ 101-110",
    themeZh: "部首 101-110",
    cards: [
      { type: "5 nét", word: "用", pinyin: "yòng", meaning: "DỤNG — Dùng", example: { zh: "用", pinyin: "yòng", vi: "dùng" } },
      { type: "5 nét", word: "田", pinyin: "tián", meaning: "ĐIỀN — Ruộng", example: { zh: "男", pinyin: "nán", vi: "nam" } },
      { type: "5 nét", word: "疋", pinyin: "pǐ", meaning: "THẤT — Đơn vị đo chiều dài", example: { zh: "疏", pinyin: "shū", vi: "thưa, sơ" } },
      { type: "5 nét", word: "疒", pinyin: "nè", meaning: "NẠCH — Bệnh tật", example: { zh: "病", pinyin: "bìng", vi: "bệnh" } },
      { type: "5 nét", word: "癶", pinyin: "bō", meaning: "BÁT — Đôi chân giạng ra", example: { zh: "登", pinyin: "dēng", vi: "leo lên" } },
      { type: "5 nét", word: "白", pinyin: "bái", meaning: "BẠCH — Màu trắng", example: { zh: "白", pinyin: "bái", vi: "trắng" } },
      { type: "5 nét", word: "皮", pinyin: "pí", meaning: "BÌ — Da", example: { zh: "皮", pinyin: "pí", vi: "da" } },
      { type: "5 nét", word: "皿", pinyin: "mǐn", meaning: "MÃNH — Bát đĩa", example: { zh: "盘", pinyin: "pán", vi: "đĩa" } },
      { type: "5 nét", word: "目", pinyin: "mù", meaning: "MỤC — Mắt", example: { zh: "看", pinyin: "kàn", vi: "nhìn" } },
      { type: "5 nét", word: "矛", pinyin: "máo", meaning: "MÂU — Cây giáo để đâm", example: { zh: "矛", pinyin: "máo", vi: "giáo, mâu" } },
    ],
  },
  {
    id: 12,
    hsk: 2,
    theme: "Bộ thủ 111-120",
    themeZh: "部首 111-120",
    cards: [
      { type: "5 nét", word: "矢", pinyin: "shǐ", meaning: "THỈ — Mũi tên", example: { zh: "知", pinyin: "zhī", vi: "biết" } },
      { type: "5 nét", word: "石", pinyin: "shí", meaning: "THẠCH — Đá", example: { zh: "石头", pinyin: "shítou", vi: "đá" } },
      { type: "5 nét", word: "示 (礻)", pinyin: "shì", meaning: "THỊ/KỲ — Chỉ thị, thần đất", example: { zh: "礼", pinyin: "lǐ", vi: "lễ" } },
      { type: "5 nét", word: "禸", pinyin: "róu", meaning: "NHỮU — Vết chân thú", example: { zh: "禽", pinyin: "qín", vi: "chim muông" } },
      { type: "5 nét", word: "禾", pinyin: "hé", meaning: "HÒA — Lúa", example: { zh: "和", pinyin: "hé", vi: "hòa, và" } },
      { type: "5 nét", word: "穴", pinyin: "xué", meaning: "HUYỆT — Cái hang", example: { zh: "空", pinyin: "kōng", vi: "trống, không" } },
      { type: "5 nét", word: "立", pinyin: "lì", meaning: "LẬP — Đứng, thành lập", example: { zh: "立", pinyin: "lì", vi: "đứng" } },
      { type: "6 nét", word: "竹", pinyin: "zhú", meaning: "TRÚC — Tre trúc", example: { zh: "笔", pinyin: "bǐ", vi: "bút" } },
      { type: "6 nét", word: "米", pinyin: "mǐ", meaning: "MỄ — Gạo", example: { zh: "米饭", pinyin: "mǐfàn", vi: "cơm" } },
      { type: "6 nét", word: "糸 (纟)", pinyin: "mì", meaning: "MỊCH — Sợi tơ nhỏ", example: { zh: "红", pinyin: "hóng", vi: "đỏ" } },
    ],
  },
  {
    id: 13,
    hsk: 2,
    theme: "Bộ thủ 121-130",
    themeZh: "部首 121-130",
    cards: [
      { type: "6 nét", word: "缶", pinyin: "fǒu", meaning: "PHẪU — Đồ sành", example: { zh: "缸", pinyin: "gāng", vi: "vại, lu" } },
      { type: "6 nét", word: "网 (罒)", pinyin: "wǎng", meaning: "VÕNG — Cái lưới", example: { zh: "网", pinyin: "wǎng", vi: "lưới, mạng" } },
      { type: "6 nét", word: "羊 (⺶)", pinyin: "yáng", meaning: "DƯƠNG — Con dê", example: { zh: "羊", pinyin: "yáng", vi: "dê" } },
      { type: "6 nét", word: "羽", pinyin: "yǔ", meaning: "VŨ — Lông vũ", example: { zh: "习", pinyin: "xí", vi: "học, tập" } },
      { type: "6 nét", word: "老 (耂)", pinyin: "lǎo", meaning: "LÃO — Già", example: { zh: "老", pinyin: "lǎo", vi: "già" } },
      { type: "6 nét", word: "而", pinyin: "ér", meaning: "NHI — Mà, và", example: { zh: "而", pinyin: "ér", vi: "mà, và" } },
      { type: "6 nét", word: "耒", pinyin: "lěi", meaning: "LỖI — Cái cày", example: { zh: "耕", pinyin: "gēng", vi: "cày" } },
      { type: "6 nét", word: "耳", pinyin: "ěr", meaning: "NHĨ — Tai", example: { zh: "耳朵", pinyin: "ěrduo", vi: "tai" } },
      { type: "6 nét", word: "聿", pinyin: "yù", meaning: "DUẬT — Cây bút", example: { zh: "书", pinyin: "shū", vi: "sách" } },
      { type: "6 nét", word: "肉 (月)", pinyin: "ròu", meaning: "NHỤC — Thịt", example: { zh: "肉", pinyin: "ròu", vi: "thịt" } },
    ],
  },
  {
    id: 14,
    hsk: 2,
    theme: "Bộ thủ 131-140",
    themeZh: "部首 131-140",
    cards: [
      { type: "6 nét", word: "臣", pinyin: "chén", meaning: "THẦN — Bầy tôi", example: { zh: "臣", pinyin: "chén", vi: "bề tôi" } },
      { type: "6 nét", word: "自", pinyin: "zì", meaning: "TỰ — Tự bản thân, kể từ", example: { zh: "自己", pinyin: "zìjǐ", vi: "tự mình" } },
      { type: "6 nét", word: "至", pinyin: "zhì", meaning: "CHÍ — Đến", example: { zh: "到", pinyin: "dào", vi: "đến, tới" } },
      { type: "6 nét", word: "臼", pinyin: "jiù", meaning: "CỮU — Cái cối giã gạo", example: { zh: "舀", pinyin: "yǎo", vi: "múc" } },
      { type: "6 nét", word: "舌", pinyin: "shé", meaning: "THIỆT — Cái lưỡi", example: { zh: "舌头", pinyin: "shétou", vi: "lưỡi" } },
      { type: "6 nét", word: "舛", pinyin: "chuǎn", meaning: "SUYỄN — Sai lầm", example: { zh: "舞", pinyin: "wǔ", vi: "múa" } },
      { type: "6 nét", word: "舟", pinyin: "zhōu", meaning: "CHU — Cái thuyền", example: { zh: "船", pinyin: "chuán", vi: "thuyền" } },
      { type: "6 nét", word: "艮", pinyin: "gěn", meaning: "CẤN — Dừng, ngừng", example: { zh: "很", pinyin: "hěn", vi: "rất" } },
      { type: "6 nét", word: "色", pinyin: "sè", meaning: "SẮC — Màu, dáng vẻ, nữ sắc", example: { zh: "颜色", pinyin: "yánsè", vi: "màu sắc" } },
      { type: "6 nét", word: "艸 (艹)", pinyin: "cǎo", meaning: "THẢO — Cỏ", example: { zh: "花", pinyin: "huā", vi: "hoa" } },
    ],
  },
  {
    id: 15,
    hsk: 3,
    theme: "Bộ thủ 141-150",
    themeZh: "部首 141-150",
    cards: [
      { type: "6 nét", word: "虍", pinyin: "hū", meaning: "HỔ — Vằn của con hổ", example: { zh: "虎", pinyin: "hǔ", vi: "hổ" } },
      { type: "6 nét", word: "虫", pinyin: "chóng", meaning: "TRÙNG — Sâu bọ, côn trùng", example: { zh: "虫", pinyin: "chóng", vi: "sâu" } },
      { type: "6 nét", word: "血", pinyin: "xuè", meaning: "HUYẾT — Máu", example: { zh: "血", pinyin: "xuè", vi: "máu" } },
      { type: "6 nét", word: "行", pinyin: "xíng", meaning: "HÀNH — Đi, thi hành, làm được", example: { zh: "行", pinyin: "xíng", vi: "được" } },
      { type: "6 nét", word: "衣 (衤)", pinyin: "yī", meaning: "Y — Áo", example: { zh: "衣服", pinyin: "yīfu", vi: "quần áo" } },
      { type: "6 nét", word: "襾", pinyin: "yà", meaning: "Á — Che đậy, úp lên", example: { zh: "西", pinyin: "xī", vi: "tây" } },
      { type: "7 nét", word: "見 (见)", pinyin: "jiàn", meaning: "KIẾN — Trông thấy", example: { zh: "看见", pinyin: "kànjiàn", vi: "trông thấy" } },
      { type: "7 nét", word: "角", pinyin: "jiǎo", meaning: "GIÁC — Góc, sừng thú", example: { zh: "角", pinyin: "jiǎo", vi: "góc" } },
      { type: "7 nét", word: "言 (讠)", pinyin: "yán", meaning: "NGÔN — Nói", example: { zh: "说", pinyin: "shuō", vi: "nói" } },
      { type: "7 nét", word: "谷", pinyin: "gǔ", meaning: "CỐC — Khe nước, thung lũng", example: { zh: "谷", pinyin: "gǔ", vi: "thung lũng" } },
    ],
  },
  {
    id: 16,
    hsk: 3,
    theme: "Bộ thủ 151-160",
    themeZh: "部首 151-160",
    cards: [
      { type: "7 nét", word: "豆", pinyin: "dòu", meaning: "ĐẬU — Hạt đậu", example: { zh: "豆", pinyin: "dòu", vi: "đậu" } },
      { type: "7 nét", word: "豕", pinyin: "shǐ", meaning: "THỈ — Con heo, con lợn", example: { zh: "家", pinyin: "jiā", vi: "nhà" } },
      { type: "7 nét", word: "豸", pinyin: "zhì", meaning: "TRÃI — Loài sâu không chân", example: { zh: "豹", pinyin: "bào", vi: "báo" } },
      { type: "7 nét", word: "貝 (贝)", pinyin: "bèi", meaning: "BỐI — Vỏ sò, vỏ ốc", example: { zh: "贵", pinyin: "guì", vi: "quý, đắt" } },
      { type: "7 nét", word: "赤", pinyin: "chì", meaning: "XÍCH — Màu đỏ", example: { zh: "赤", pinyin: "chì", vi: "đỏ" } },
      { type: "7 nét", word: "走", pinyin: "zǒu", meaning: "TẨU — Đi, chạy", example: { zh: "走", pinyin: "zǒu", vi: "đi" } },
      { type: "7 nét", word: "足 (⻊)", pinyin: "zú", meaning: "TÚC — Chân, đầy đủ", example: { zh: "足球", pinyin: "zúqiú", vi: "bóng đá" } },
      { type: "7 nét", word: "身", pinyin: "shēn", meaning: "THÂN — Thân thể, thân mình", example: { zh: "身体", pinyin: "shēntǐ", vi: "thân thể" } },
      { type: "7 nét", word: "車 (车)", pinyin: "chē", meaning: "XA — Chiếc xe", example: { zh: "车", pinyin: "chē", vi: "xe" } },
      { type: "7 nét", word: "辛", pinyin: "xīn", meaning: "TÂN — Cay, vất vả", example: { zh: "辛苦", pinyin: "xīnkǔ", vi: "vất vả" } },
    ],
  },
  {
    id: 17,
    hsk: 3,
    theme: "Bộ thủ 161-170",
    themeZh: "部首 161-170",
    cards: [
      { type: "7 nét", word: "辰", pinyin: "chén", meaning: "THÌN/THẦN — Thìn, chi thứ năm trong 12 địa chi", example: { zh: "辰", pinyin: "chén", vi: "thìn" } },
      { type: "7 nét", word: "辵 (辶)", pinyin: "chuò", meaning: "SƯỚC — Chợt bước đi chợt dừng", example: { zh: "道", pinyin: "dào", vi: "đường" } },
      { type: "7 nét", word: "邑 (⻏)", pinyin: "yì", meaning: "ẤP — Đất, làng xóm", example: { zh: "都", pinyin: "dōu", vi: "đều, thủ đô" } },
      { type: "7 nét", word: "酉", pinyin: "yǒu", meaning: "DẬU — Dậu, chi thứ mười trong 12 địa chi", example: { zh: "酒", pinyin: "jiǔ", vi: "rượu" } },
      { type: "7 nét", word: "釆", pinyin: "biàn", meaning: "BIỆN — Phân biệt", example: { zh: "释", pinyin: "shì", vi: "giải thích" } },
      { type: "7 nét", word: "里", pinyin: "lǐ", meaning: "LÝ — Dặm, làng xóm", example: { zh: "里", pinyin: "lǐ", vi: "trong, dặm" } },
      { type: "8 nét", word: "金 (钅)", pinyin: "jīn", meaning: "KIM — Kim loại, vàng", example: { zh: "金", pinyin: "jīn", vi: "vàng" } },
      { type: "8 nét", word: "長 (长)", pinyin: "cháng", meaning: "TRƯỜNG — Dài, lớn (trưởng)", example: { zh: "长", pinyin: "cháng", vi: "dài" } },
      { type: "8 nét", word: "門 (门)", pinyin: "mén", meaning: "MÔN — Cửa hai cánh", example: { zh: "门", pinyin: "mén", vi: "cửa" } },
      { type: "8 nét", word: "阜 (⻖)", pinyin: "fù", meaning: "PHỤ — Đụn đất, gò đất", example: { zh: "阴", pinyin: "yīn", vi: "âm, mát" } },
    ],
  },
  {
    id: 18,
    hsk: 3,
    theme: "Bộ thủ 171-180",
    themeZh: "部首 171-180",
    cards: [
      { type: "8 nét", word: "隶", pinyin: "dài", meaning: "ĐÃI — Kịp, lệ thuộc", example: { zh: "隶", pinyin: "lì", vi: "nô lệ" } },
      { type: "8 nét", word: "隹", pinyin: "zhuī", meaning: "CHUY — Chim đuôi ngắn", example: { zh: "雀", pinyin: "què", vi: "chim sẻ" } },
      { type: "8 nét", word: "雨", pinyin: "yǔ", meaning: "VŨ — Mưa", example: { zh: "雨", pinyin: "yǔ", vi: "mưa" } },
      { type: "8 nét", word: "青", pinyin: "qīng", meaning: "THANH — Màu xanh", example: { zh: "青", pinyin: "qīng", vi: "xanh" } },
      { type: "8 nét", word: "非", pinyin: "fēi", meaning: "PHI — Không, sai", example: { zh: "非常", pinyin: "fēicháng", vi: "rất, phi thường" } },
      { type: "9 nét", word: "面", pinyin: "miàn", meaning: "DIỆN — Mặt, bề mặt", example: { zh: "面", pinyin: "miàn", vi: "mặt" } },
      { type: "9 nét", word: "革", pinyin: "gé", meaning: "CÁCH — Da thú, thay đổi", example: { zh: "革命", pinyin: "gémìng", vi: "cách mạng" } },
      { type: "9 nét", word: "韋 (韦)", pinyin: "wéi", meaning: "VI — Da đã thuộc rồi", example: { zh: "韦", pinyin: "wéi", vi: "họ Vi" } },
      { type: "9 nét", word: "韭", pinyin: "jiǔ", meaning: "CỬU — Rau hẹ", example: { zh: "韭菜", pinyin: "jiǔcài", vi: "rau hẹ" } },
      { type: "9 nét", word: "音", pinyin: "yīn", meaning: "ÂM — Âm thanh, tiếng", example: { zh: "音乐", pinyin: "yīnyuè", vi: "âm nhạc" } },
    ],
  },
  {
    id: 19,
    hsk: 3,
    theme: "Bộ thủ 181-190",
    themeZh: "部首 181-190",
    cards: [
      { type: "9 nét", word: "頁 (页)", pinyin: "yè", meaning: "HIỆT — Đầu, trang giấy", example: { zh: "页", pinyin: "yè", vi: "trang" } },
      { type: "9 nét", word: "風 (风)", pinyin: "fēng", meaning: "PHONG — Gió", example: { zh: "风", pinyin: "fēng", vi: "gió" } },
      { type: "9 nét", word: "飛 (飞)", pinyin: "fēi", meaning: "PHI — Bay", example: { zh: "飞", pinyin: "fēi", vi: "bay" } },
      { type: "9 nét", word: "食 (饣)", pinyin: "shí", meaning: "THỰC — Ăn", example: { zh: "饭", pinyin: "fàn", vi: "cơm" } },
      { type: "9 nét", word: "首", pinyin: "shǒu", meaning: "THỦ — Đầu", example: { zh: "首", pinyin: "shǒu", vi: "đầu" } },
      { type: "9 nét", word: "香", pinyin: "xiāng", meaning: "HƯƠNG — Mùi hương thơm", example: { zh: "香", pinyin: "xiāng", vi: "thơm" } },
      { type: "10 nét", word: "馬 (马)", pinyin: "mǎ", meaning: "MÃ — Con ngựa", example: { zh: "马", pinyin: "mǎ", vi: "ngựa" } },
      { type: "10 nét", word: "骨", pinyin: "gǔ", meaning: "CỐT — Xương", example: { zh: "骨", pinyin: "gǔ", vi: "xương" } },
      { type: "10 nét", word: "高", pinyin: "gāo", meaning: "CAO — Cao", example: { zh: "高", pinyin: "gāo", vi: "cao" } },
      { type: "10 nét", word: "髟", pinyin: "biāo", meaning: "BƯU — Tóc dài, sam cỏ phủ mái nhà", example: { zh: "髮", pinyin: "fà", vi: "tóc" } },
    ],
  },
  {
    id: 20,
    hsk: 3,
    theme: "Bộ thủ 191-200",
    themeZh: "部首 191-200",
    cards: [
      { type: "10 nét", word: "鬥", pinyin: "dòu", meaning: "ĐẤU — Chống nhau, chiến đấu", example: { zh: "鬥", pinyin: "dòu", vi: "đấu, đánh" } },
      { type: "10 nét", word: "鬯", pinyin: "chàng", meaning: "SƯỞNG — Rượu nếp, bao đựng cung", example: { zh: "鬯", pinyin: "chàng", vi: "rượu nếp" } },
      { type: "10 nét", word: "鬲", pinyin: "gé", meaning: "CÁCH/LỊCH — Tên một con sông xưa, cái đỉnh", example: { zh: "鬲", pinyin: "gé", vi: "đỉnh" } },
      { type: "10 nét", word: "鬼", pinyin: "guǐ", meaning: "QUỶ — Con quỷ", example: { zh: "鬼", pinyin: "guǐ", vi: "quỷ" } },
      { type: "11 nét", word: "魚 (鱼)", pinyin: "yú", meaning: "NGƯ — Con cá", example: { zh: "鱼", pinyin: "yú", vi: "cá" } },
      { type: "11 nét", word: "鳥 (鸟)", pinyin: "niǎo", meaning: "ĐIỂU — Con chim", example: { zh: "鸟", pinyin: "niǎo", vi: "chim" } },
      { type: "11 nét", word: "鹵 (卤)", pinyin: "lǔ", meaning: "LỖ — Đất mặn", example: { zh: "鹵", pinyin: "lǔ", vi: "đất mặn" } },
      { type: "11 nét", word: "鹿", pinyin: "lù", meaning: "LỘC — Con hươu", example: { zh: "鹿", pinyin: "lù", vi: "hươu" } },
      { type: "11 nét", word: "麥 (麦)", pinyin: "mài", meaning: "MẠCH — Lúa mạch", example: { zh: "麦", pinyin: "mài", vi: "lúa mì" } },
      { type: "11 nét", word: "麻", pinyin: "má", meaning: "MA — Cây gai", example: { zh: "麻", pinyin: "má", vi: "gai" } },
    ],
  },
  {
    id: 21,
    hsk: 3,
    theme: "Bộ thủ 201-210",
    themeZh: "部首 201-210",
    cards: [
      { type: "12 nét", word: "黃 (黄)", pinyin: "huáng", meaning: "HOÀNG — Màu vàng", example: { zh: "黄", pinyin: "huáng", vi: "vàng" } },
      { type: "12 nét", word: "黍", pinyin: "shǔ", meaning: "THỬ — Lúa nếp, kê", example: { zh: "黍", pinyin: "shǔ", vi: "kê" } },
      { type: "12 nét", word: "黑", pinyin: "hēi", meaning: "HẮC — Màu đen", example: { zh: "黑", pinyin: "hēi", vi: "đen" } },
      { type: "12 nét", word: "黹", pinyin: "zhǐ", meaning: "CHỈ — May áo, khâu vá", example: { zh: "黹", pinyin: "zhǐ", vi: "thêu" } },
      { type: "13 nét", word: "黽 (黾)", pinyin: "mǐn", meaning: "MÃNH — Con ếch, cố gắng", example: { zh: "黽", pinyin: "mǐn", vi: "ếch" } },
      { type: "13 nét", word: "鼎", pinyin: "dǐng", meaning: "ĐỈNH — Cái đỉnh (vạc)", example: { zh: "鼎", pinyin: "dǐng", vi: "đỉnh" } },
      { type: "13 nét", word: "鼓", pinyin: "gǔ", meaning: "CỔ — Cái trống", example: { zh: "鼓", pinyin: "gǔ", vi: "trống" } },
      { type: "13 nét", word: "鼠", pinyin: "shǔ", meaning: "THỬ — Con chuột", example: { zh: "老鼠", pinyin: "lǎoshǔ", vi: "chuột" } },
      { type: "14 nét", word: "鼻", pinyin: "bí", meaning: "TỴ — Cái mũi", example: { zh: "鼻子", pinyin: "bízi", vi: "mũi" } },
      { type: "14 nét", word: "齊 (齐)", pinyin: "qí", meaning: "TỀ — Ngang bằng, đều", example: { zh: "齐", pinyin: "qí", vi: "đều" } },
    ],
  },
  {
    id: 22,
    hsk: 3,
    theme: "Bộ thủ 211-214",
    themeZh: "部首 211-214",
    cards: [
      { type: "15 nét", word: "齒 (齿)", pinyin: "chǐ", meaning: "XỈ — Răng", example: { zh: "齿", pinyin: "chǐ", vi: "răng" } },
      { type: "16 nét", word: "龍 (龙)", pinyin: "lóng", meaning: "LONG — Con rồng", example: { zh: "龙", pinyin: "lóng", vi: "rồng" } },
      { type: "16 nét", word: "龜 (龟)", pinyin: "guī", meaning: "QUY — Con rùa", example: { zh: "龟", pinyin: "guī", vi: "rùa" } },
      { type: "17 nét", word: "龠", pinyin: "yuè", meaning: "DƯỢC — Sáo ba lỗ", example: { zh: "龠", pinyin: "yuè", vi: "sáo" } },
    ],
  },
];

const data = { days: FULL_DAYS };

window.data = data;
