window.VOCAB_DATA = {
  "topics": [
    { "id": "basics", "name_vi": "Cơ bản", "name_en": "Basics", "emoji": "🌱" },
    { "id": "api", "name_vi": "API", "name_en": "API", "emoji": "🔌" },
    { "id": "conversation", "name_vi": "Hội thoại", "name_en": "Conversation", "emoji": "💬" },
    { "id": "models", "name_vi": "Mô hình Claude", "name_en": "Models", "emoji": "🤖" },
    { "id": "tokens", "name_vi": "Token & Context", "name_en": "Tokens", "emoji": "🧩" },
    { "id": "prompting", "name_vi": "Kỹ thuật Prompt", "name_en": "Prompting", "emoji": "✍️" },
    { "id": "tools", "name_vi": "Tool use", "name_en": "Tools", "emoji": "🛠️" },
    { "id": "safety", "name_vi": "An toàn", "name_en": "Safety", "emoji": "🛡️" },
    { "id": "advanced", "name_vi": "Nâng cao", "name_en": "Advanced", "emoji": "🚀" }
  ],
  "words": [
    { "id": "ai", "word": "AI", "ipa": "/ˌeɪˈaɪ/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "viết tắt của Artificial Intelligence",
      "meaning_ai_vi": "trí tuệ nhân tạo — máy tính có khả năng suy nghĩ, học hỏi",
      "example_en": "Claude is an AI assistant.",
      "example_vi": "Claude là một trợ lý AI.",
      "tip_vi": "Đọc là 'ây-ai', không phải 'ai' trong tiếng Việt." },

    { "id": "model", "word": "model", "ipa": "/ˈmɒdəl/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "người mẫu; mô hình thu nhỏ (xe, máy bay)",
      "meaning_ai_vi": "mô hình AI — chương trình đã được huấn luyện để hiểu và sinh văn bản",
      "example_en": "Claude is a large language model.",
      "example_vi": "Claude là một mô hình ngôn ngữ lớn.",
      "tip_vi": "Trong AI, 'model' = mô hình, không phải người mẫu." },

    { "id": "prompt", "word": "prompt", "ipa": "/prɒmpt/", "pos": "noun, verb", "topic": "basics",
      "meaning_everyday_vi": "(tính từ) nhanh chóng, đúng giờ; (động từ) thúc giục",
      "meaning_ai_vi": "lời nhắc / câu lệnh bạn gửi cho AI để nó làm gì đó",
      "example_en": "Write a clear prompt for Claude.",
      "example_vi": "Viết một lời nhắc rõ ràng cho Claude.",
      "tip_vi": "Đây là từ quan trọng nhất khi dùng AI. Học kỹ từ này." },

    { "id": "response", "word": "response", "ipa": "/rɪˈspɒns/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "câu trả lời, phản ứng",
      "meaning_ai_vi": "câu trả lời mà AI gửi lại cho bạn",
      "example_en": "Claude gave a helpful response.",
      "example_vi": "Claude đã đưa ra một câu trả lời hữu ích.",
      "tip_vi": "Đối ngược của 'request' (yêu cầu)." },

    { "id": "input", "word": "input", "ipa": "/ˈɪnpʊt/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "đầu vào, ý kiến đóng góp",
      "meaning_ai_vi": "thông tin bạn đưa vào cho AI (text, hình ảnh...)",
      "example_en": "The input is a question.",
      "example_vi": "Đầu vào là một câu hỏi.",
      "tip_vi": "Cặp đôi: input ↔ output." },

    { "id": "output", "word": "output", "ipa": "/ˈaʊtpʊt/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "đầu ra, sản lượng",
      "meaning_ai_vi": "kết quả AI tạo ra cho bạn",
      "example_en": "The output is a long text.",
      "example_vi": "Đầu ra là một đoạn văn dài.",
      "tip_vi": "Cặp đôi: input ↔ output." },

    { "id": "generate", "word": "generate", "ipa": "/ˈdʒenəreɪt/", "pos": "verb", "topic": "basics",
      "meaning_everyday_vi": "sinh ra, tạo ra (điện, tiền, ý tưởng)",
      "meaning_ai_vi": "AI tạo ra văn bản, hình ảnh, code...",
      "example_en": "Claude can generate code.",
      "example_vi": "Claude có thể tạo ra code.",
      "tip_vi": "Từ này thường gặp: 'generative AI' = AI sinh nội dung." },

    { "id": "instruction", "word": "instruction", "ipa": "/ɪnˈstrʌkʃən/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "chỉ dẫn, hướng dẫn (sách, lớp học)",
      "meaning_ai_vi": "lời chỉ dẫn bạn cho AI biết nó cần làm gì",
      "example_en": "Give Claude clear instructions.",
      "example_vi": "Hãy cho Claude lời chỉ dẫn rõ ràng.",
      "tip_vi": "Số nhiều 'instructions' thường dùng hơn." },

    { "id": "language", "word": "language", "ipa": "/ˈlæŋɡwɪdʒ/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "ngôn ngữ (tiếng Việt, tiếng Anh...)",
      "meaning_ai_vi": "ngôn ngữ — tự nhiên (Anh, Việt) hoặc lập trình (Python)",
      "example_en": "Claude understands many languages.",
      "example_vi": "Claude hiểu nhiều ngôn ngữ.",
      "tip_vi": "Phát âm: 'LANG-gwij', không phải 'lan-guêjơ'." },

    { "id": "example", "word": "example", "ipa": "/ɪɡˈzɑːmpəl/", "pos": "noun", "topic": "basics",
      "meaning_everyday_vi": "ví dụ, minh họa",
      "meaning_ai_vi": "ví dụ bạn đưa cho AI để nó hiểu mẫu (gọi là 'few-shot')",
      "example_en": "Give Claude two examples.",
      "example_vi": "Hãy cho Claude hai ví dụ.",
      "tip_vi": "'For example' = 'ví dụ như', dùng cực kỳ thường xuyên." },

    { "id": "api", "word": "API", "ipa": "/ˌeɪ piː ˈaɪ/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "viết tắt của Application Programming Interface",
      "meaning_ai_vi": "cách lập trình viên gọi AI bằng code (thay vì chat thường)",
      "example_en": "Use the Claude API in your app.",
      "example_vi": "Dùng API của Claude trong ứng dụng của bạn.",
      "tip_vi": "Đọc là 'ây-pi-ai', từng chữ một." },

    { "id": "endpoint", "word": "endpoint", "ipa": "/ˈendpɔɪnt/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "điểm cuối (đường, hành trình)",
      "meaning_ai_vi": "địa chỉ URL bạn gọi để dùng API",
      "example_en": "The API has many endpoints.",
      "example_vi": "API có nhiều endpoint.",
      "tip_vi": "Ví dụ endpoint của Claude: api.anthropic.com/v1/messages" },

    { "id": "request", "word": "request", "ipa": "/rɪˈkwest/", "pos": "noun, verb", "topic": "api",
      "meaning_everyday_vi": "yêu cầu, đề nghị",
      "meaning_ai_vi": "lệnh bạn gửi đến API (đối ngược: response)",
      "example_en": "Send a request to the API.",
      "example_vi": "Gửi một yêu cầu đến API.",
      "tip_vi": "Cặp: request (gửi đi) ↔ response (nhận về)." },

    { "id": "key", "word": "key", "ipa": "/kiː/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "chìa khóa; phím (bàn phím)",
      "meaning_ai_vi": "chuỗi bí mật để xác thực bạn (API key)",
      "example_en": "Keep your API key secret.",
      "example_vi": "Giữ bí mật khóa API của bạn.",
      "tip_vi": "Lộ API key = mất tiền. Giống mật khẩu." },

    { "id": "authentication", "word": "authentication", "ipa": "/ɔːˌθentɪˈkeɪʃən/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "việc xác thực (đăng nhập, kiểm tra danh tính)",
      "meaning_ai_vi": "kiểm tra xem bạn có phải người được phép gọi API không",
      "example_en": "Authentication uses an API key.",
      "example_vi": "Xác thực dùng một khóa API.",
      "tip_vi": "Viết tắt 'auth' rất hay gặp trong code." },

    { "id": "parameter", "word": "parameter", "ipa": "/pəˈræmɪtə/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "tham số, giới hạn (toán học)",
      "meaning_ai_vi": "giá trị bạn truyền vào API để điều chỉnh kết quả",
      "example_en": "Set the temperature parameter to 0.7.",
      "example_vi": "Đặt tham số temperature là 0.7.",
      "tip_vi": "Viết tắt 'param' rất hay gặp." },

    { "id": "header", "word": "header", "ipa": "/ˈhedə/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "tiêu đề, đầu trang",
      "meaning_ai_vi": "phần đầu của request, chứa thông tin xác thực",
      "example_en": "The header has the API key.",
      "example_vi": "Phần header chứa khóa API.",
      "tip_vi": "Header thường có: Authorization, Content-Type." },

    { "id": "body", "word": "body", "ipa": "/ˈbɒdi/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "cơ thể; thân (xe, máy)",
      "meaning_ai_vi": "phần nội dung chính của request (thường là JSON)",
      "example_en": "The body contains the prompt.",
      "example_vi": "Phần body chứa lời nhắc.",
      "tip_vi": "Header = phong bì, Body = nội dung thư." },

    { "id": "json", "word": "JSON", "ipa": "/ˈdʒeɪsən/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "viết tắt JavaScript Object Notation",
      "meaning_ai_vi": "định dạng dữ liệu phổ biến nhất khi gọi API",
      "example_en": "The API returns JSON.",
      "example_vi": "API trả về dữ liệu JSON.",
      "tip_vi": "Đọc là 'JAY-sun', không phải 'jơ-sôn'." },

    { "id": "status", "word": "status", "ipa": "/ˈsteɪtəs/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "trạng thái, tình trạng",
      "meaning_ai_vi": "mã số cho biết request thành công hay lỗi (200, 404...)",
      "example_en": "Status 200 means success.",
      "example_vi": "Trạng thái 200 nghĩa là thành công.",
      "tip_vi": "200 = OK, 401 = chưa xác thực, 500 = lỗi server." },

    { "id": "error", "word": "error", "ipa": "/ˈerə/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "lỗi, sai sót",
      "meaning_ai_vi": "khi API gọi không thành công",
      "example_en": "The API returned an error.",
      "example_vi": "API trả về một lỗi.",
      "tip_vi": "'Error message' = thông báo lỗi, đọc kỹ để biết sai gì." },

    { "id": "rate", "word": "rate", "ipa": "/reɪt/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "tỷ lệ, mức (giá, lãi suất)",
      "meaning_ai_vi": "tốc độ — thường gặp 'rate limit' (số request tối đa/phút)",
      "example_en": "Don't hit the rate limit.",
      "example_vi": "Đừng vượt giới hạn tốc độ.",
      "tip_vi": "'Rate limit exceeded' = bạn gọi quá nhanh, phải chờ." },

    { "id": "limit", "word": "limit", "ipa": "/ˈlɪmɪt/", "pos": "noun, verb", "topic": "api",
      "meaning_everyday_vi": "giới hạn, hạn mức (tốc độ, tiền)",
      "meaning_ai_vi": "giới hạn về số request, token, hoặc tiền",
      "example_en": "There is a daily limit.",
      "example_vi": "Có một giới hạn hằng ngày.",
      "tip_vi": "Phát âm: 'LI-mít', nhấn vào âm đầu." },

    { "id": "version", "word": "version", "ipa": "/ˈvɜːʃən/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "phiên bản (phần mềm, sách)",
      "meaning_ai_vi": "phiên bản của API hoặc model (v1, v2...)",
      "example_en": "Use the latest version.",
      "example_vi": "Hãy dùng phiên bản mới nhất.",
      "tip_vi": "Phát âm: 'VƠ-shần', không phải 'VƠ-xần'." },

    { "id": "sdk", "word": "SDK", "ipa": "/ˌes diː ˈkeɪ/", "pos": "noun", "topic": "api",
      "meaning_everyday_vi": "viết tắt Software Development Kit",
      "meaning_ai_vi": "thư viện code giúp gọi API dễ hơn (Python SDK, JS SDK)",
      "example_en": "Install the Python SDK.",
      "example_vi": "Cài thư viện SDK cho Python.",
      "tip_vi": "Anthropic có SDK cho Python và TypeScript." },

    { "id": "message", "word": "message", "ipa": "/ˈmesɪdʒ/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "tin nhắn, lời nhắn",
      "meaning_ai_vi": "một lượt nói trong cuộc trò chuyện với AI",
      "example_en": "Send a message to Claude.",
      "example_vi": "Gửi một tin nhắn cho Claude.",
      "tip_vi": "Phát âm: 'ME-sij'. Cuối có /j/, không phải /s/." },

    { "id": "role", "word": "role", "ipa": "/rəʊl/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "vai diễn (phim, kịch); vai trò",
      "meaning_ai_vi": "vai trong hội thoại: 'user', 'assistant', hoặc 'system'",
      "example_en": "Each message has a role.",
      "example_vi": "Mỗi tin nhắn có một vai.",
      "tip_vi": "Đừng nhầm 'role' (vai) với 'roll' (cuộn)." },

    { "id": "system", "word": "system", "ipa": "/ˈsɪstəm/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "hệ thống (điện, máy tính)",
      "meaning_ai_vi": "vai 'system' — lời chỉ dẫn nền cho AI (tính cách, quy tắc)",
      "example_en": "The system prompt sets the tone.",
      "example_vi": "System prompt đặt phong cách trả lời.",
      "tip_vi": "'System prompt' là cài đặt đầu tiên cho AI." },

    { "id": "user", "word": "user", "ipa": "/ˈjuːzə/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "người dùng (app, web)",
      "meaning_ai_vi": "vai 'user' — chính là bạn, người nói với AI",
      "example_en": "The user asks a question.",
      "example_vi": "Người dùng đặt một câu hỏi.",
      "tip_vi": "Phát âm: 'IU-zơ', không phải 'iu-sờ'." },

    { "id": "assistant", "word": "assistant", "ipa": "/əˈsɪstənt/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "trợ lý, người giúp việc",
      "meaning_ai_vi": "vai 'assistant' — chính là AI trả lời bạn",
      "example_en": "The assistant gives an answer.",
      "example_vi": "Trợ lý đưa ra câu trả lời.",
      "tip_vi": "Phát âm: 'ờ-SIS-tần', âm 't' cuối nhẹ." },

    { "id": "context", "word": "context", "ipa": "/ˈkɒntekst/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "bối cảnh, ngữ cảnh",
      "meaning_ai_vi": "toàn bộ thông tin AI thấy được khi trả lời (lịch sử + lời nhắc)",
      "example_en": "Give Claude more context.",
      "example_vi": "Cho Claude thêm ngữ cảnh.",
      "tip_vi": "Càng nhiều context tốt → AI trả lời càng đúng." },

    { "id": "history", "word": "history", "ipa": "/ˈhɪstəri/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "lịch sử (môn học, sự kiện)",
      "meaning_ai_vi": "các tin nhắn trước đó trong cuộc trò chuyện",
      "example_en": "The chat history is long.",
      "example_vi": "Lịch sử trò chuyện rất dài.",
      "tip_vi": "Phát âm: 'HIS-tơ-ri', 3 âm tiết." },

    { "id": "turn", "word": "turn", "ipa": "/tɜːn/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "lượt; rẽ (lái xe)",
      "meaning_ai_vi": "một lượt nói trong hội thoại (1 user + 1 assistant)",
      "example_en": "It's the user's turn.",
      "example_vi": "Đến lượt người dùng.",
      "tip_vi": "'Multi-turn' = nhiều lượt qua lại." },

    { "id": "reply", "word": "reply", "ipa": "/rɪˈplaɪ/", "pos": "noun, verb", "topic": "conversation",
      "meaning_everyday_vi": "trả lời, hồi đáp",
      "meaning_ai_vi": "câu trả lời của AI (giống response, nhưng thân mật hơn)",
      "example_en": "Claude's reply was short.",
      "example_vi": "Câu trả lời của Claude rất ngắn.",
      "tip_vi": "Reply ≈ response, nhưng reply hay dùng khi chat." },

    { "id": "follow-up", "word": "follow-up", "ipa": "/ˈfɒləʊ ʌp/", "pos": "noun, adj", "topic": "conversation",
      "meaning_everyday_vi": "tiếp nối, theo sau",
      "meaning_ai_vi": "câu hỏi/lệnh tiếp theo trong cuộc trò chuyện",
      "example_en": "I have a follow-up question.",
      "example_vi": "Tôi có một câu hỏi tiếp theo.",
      "tip_vi": "Có dấu gạch nối khi làm tính từ/danh từ." },

    { "id": "clarify", "word": "clarify", "ipa": "/ˈklærɪfaɪ/", "pos": "verb", "topic": "conversation",
      "meaning_everyday_vi": "làm rõ, giải thích cho rõ",
      "meaning_ai_vi": "yêu cầu AI giải thích thêm khi câu trả lời chưa rõ",
      "example_en": "Can you clarify your answer?",
      "example_vi": "Bạn có thể làm rõ câu trả lời không?",
      "tip_vi": "'Clear' (rõ) + 'fy' (làm) = clarify (làm rõ)." },

    { "id": "refine", "word": "refine", "ipa": "/rɪˈfaɪn/", "pos": "verb", "topic": "conversation",
      "meaning_everyday_vi": "tinh luyện, làm tinh tế hơn",
      "meaning_ai_vi": "chỉnh lại câu trả lời cho tốt hơn",
      "example_en": "Refine the answer, please.",
      "example_vi": "Hãy tinh chỉnh câu trả lời.",
      "tip_vi": "'Refine' < 'rewrite' về độ thay đổi." },

    { "id": "iterate", "word": "iterate", "ipa": "/ˈɪtəreɪt/", "pos": "verb", "topic": "conversation",
      "meaning_everyday_vi": "lặp lại, làm đi làm lại",
      "meaning_ai_vi": "thử-sửa-thử lại nhiều lần để có kết quả tốt",
      "example_en": "Iterate on your prompt.",
      "example_vi": "Hãy lặp lại tinh chỉnh prompt.",
      "tip_vi": "Phát âm: 'I-tơ-rết', nhấn âm đầu." },

    { "id": "dialogue", "word": "dialogue", "ipa": "/ˈdaɪəlɒɡ/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "đối thoại (giữa hai người, trong phim)",
      "meaning_ai_vi": "cuộc trò chuyện qua lại giữa bạn và AI",
      "example_en": "We had a long dialogue.",
      "example_vi": "Chúng tôi có một cuộc đối thoại dài.",
      "tip_vi": "Viết kiểu Mỹ: 'dialog' (không có 'ue')." },

    { "id": "conversation", "word": "conversation", "ipa": "/ˌkɒnvəˈseɪʃən/", "pos": "noun", "topic": "conversation",
      "meaning_everyday_vi": "cuộc trò chuyện, nói chuyện",
      "meaning_ai_vi": "toàn bộ tin nhắn qua lại với AI",
      "example_en": "This is a new conversation.",
      "example_vi": "Đây là một cuộc trò chuyện mới.",
      "tip_vi": "Phát âm: 'con-vơ-SÂY-shần', 4 âm tiết." },

    { "id": "claude", "word": "Claude", "ipa": "/klɔːd/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "tên riêng (người Pháp)",
      "meaning_ai_vi": "tên family model AI của công ty Anthropic",
      "example_en": "Claude was made by Anthropic.",
      "example_vi": "Claude do công ty Anthropic làm ra.",
      "tip_vi": "Đọc là 'KLỐT', không phải 'CLAU-đơ'." },

    { "id": "opus", "word": "Opus", "ipa": "/ˈəʊpəs/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "tác phẩm lớn (âm nhạc cổ điển)",
      "meaning_ai_vi": "model Claude lớn nhất, thông minh nhất, chậm hơn",
      "example_en": "Use Opus for hard tasks.",
      "example_vi": "Dùng Opus cho việc khó.",
      "tip_vi": "Opus = thông minh nhất, dùng cho task khó." },

    { "id": "sonnet", "word": "Sonnet", "ipa": "/ˈsɒnɪt/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "bài thơ sonnet 14 câu",
      "meaning_ai_vi": "model Claude cỡ vừa, cân bằng thông minh và tốc độ",
      "example_en": "Sonnet is a good default choice.",
      "example_vi": "Sonnet là lựa chọn mặc định tốt.",
      "tip_vi": "Sonnet = cân bằng nhất, dùng cho phần lớn việc." },

    { "id": "haiku", "word": "Haiku", "ipa": "/ˈhaɪkuː/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "bài thơ haiku Nhật Bản 3 câu",
      "meaning_ai_vi": "model Claude nhỏ nhất, nhanh nhất, rẻ nhất",
      "example_en": "Haiku is fast and cheap.",
      "example_vi": "Haiku nhanh và rẻ.",
      "tip_vi": "Haiku = nhanh & rẻ, dùng cho task đơn giản." },

    { "id": "release", "word": "release", "ipa": "/rɪˈliːs/", "pos": "noun, verb", "topic": "models",
      "meaning_everyday_vi": "phát hành (phim, album); thả ra",
      "meaning_ai_vi": "đợt ra mắt model mới",
      "example_en": "The new release is faster.",
      "example_vi": "Phiên bản mới nhanh hơn.",
      "tip_vi": "Phát âm: 'rì-LÍT', nhấn âm sau." },

    { "id": "capability", "word": "capability", "ipa": "/ˌkeɪpəˈbɪlɪti/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "khả năng, năng lực",
      "meaning_ai_vi": "khả năng của model (làm toán, viết code, đọc ảnh...)",
      "example_en": "Claude has vision capabilities.",
      "example_vi": "Claude có khả năng nhìn ảnh.",
      "tip_vi": "Cùng họ với 'capable' (có khả năng)." },

    { "id": "performance", "word": "performance", "ipa": "/pəˈfɔːməns/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "buổi biểu diễn; hiệu suất làm việc",
      "meaning_ai_vi": "model làm việc tốt thế nào (đúng/sai, nhanh/chậm)",
      "example_en": "Opus has the best performance.",
      "example_vi": "Opus có hiệu suất tốt nhất.",
      "tip_vi": "Phát âm: 'pơ-PHO-mần'." },

    { "id": "speed", "word": "speed", "ipa": "/spiːd/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "tốc độ (xe, internet)",
      "meaning_ai_vi": "model trả lời nhanh hay chậm",
      "example_en": "Haiku has high speed.",
      "example_vi": "Haiku có tốc độ cao.",
      "tip_vi": "Đối ngược: 'slow' (chậm)." },

    { "id": "accuracy", "word": "accuracy", "ipa": "/ˈækjərəsi/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "độ chính xác (đồng hồ, súng)",
      "meaning_ai_vi": "tỷ lệ trả lời đúng của model",
      "example_en": "Higher accuracy is better.",
      "example_vi": "Độ chính xác cao hơn thì tốt hơn.",
      "tip_vi": "Tính từ: 'accurate' (chính xác)." },

    { "id": "benchmark", "word": "benchmark", "ipa": "/ˈbentʃmɑːk/", "pos": "noun", "topic": "models",
      "meaning_everyday_vi": "chuẩn so sánh, mốc đánh giá",
      "meaning_ai_vi": "bài kiểm tra chuẩn để so sánh các model",
      "example_en": "Claude scores high on benchmarks.",
      "example_vi": "Claude đạt điểm cao trên các benchmark.",
      "tip_vi": "Ví dụ: MMLU, HumanEval — đều là benchmark." },

    { "id": "token", "word": "token", "ipa": "/ˈtəʊkən/", "pos": "noun", "topic": "tokens",
      "meaning_everyday_vi": "đồng xèng, dấu hiệu, kỉ vật",
      "meaning_ai_vi": "đơn vị nhỏ AI 'đọc' (khoảng 0.75 từ tiếng Anh = 1 token)",
      "example_en": "This sentence is ten tokens.",
      "example_vi": "Câu này là 10 token.",
      "tip_vi": "Tính tiền API dựa trên số token." },

    { "id": "count", "word": "count", "ipa": "/kaʊnt/", "pos": "verb, noun", "topic": "tokens",
      "meaning_everyday_vi": "đếm; sự đếm",
      "meaning_ai_vi": "đếm số token (token count)",
      "example_en": "Count the tokens before sending.",
      "example_vi": "Hãy đếm token trước khi gửi.",
      "tip_vi": "Phát âm có /aʊ/, giống 'cao'." },

    { "id": "window", "word": "window", "ipa": "/ˈwɪndəʊ/", "pos": "noun", "topic": "tokens",
      "meaning_everyday_vi": "cửa sổ (nhà, máy tính)",
      "meaning_ai_vi": "'context window' = số token tối đa AI nhớ được",
      "example_en": "Claude has a large context window.",
      "example_vi": "Claude có cửa sổ ngữ cảnh lớn.",
      "tip_vi": "Window càng lớn → AI nhớ càng nhiều." },

    { "id": "length", "word": "length", "ipa": "/leŋθ/", "pos": "noun", "topic": "tokens",
      "meaning_everyday_vi": "chiều dài, độ dài",
      "meaning_ai_vi": "độ dài văn bản (đo bằng token)",
      "example_en": "What is the prompt length?",
      "example_vi": "Lời nhắc dài bao nhiêu?",
      "tip_vi": "Tính từ: 'long' (dài). Danh từ: 'length'." },

    { "id": "truncate", "word": "truncate", "ipa": "/trʌŋˈkeɪt/", "pos": "verb", "topic": "tokens",
      "meaning_everyday_vi": "cắt cụt, rút ngắn",
      "meaning_ai_vi": "cắt bớt văn bản khi nó dài quá giới hạn",
      "example_en": "The output was truncated.",
      "example_vi": "Đầu ra đã bị cắt bớt.",
      "tip_vi": "Hay gặp lỗi 'response truncated' = bị cắt giữa chừng." },

    { "id": "fit", "word": "fit", "ipa": "/fɪt/", "pos": "verb", "topic": "tokens",
      "meaning_everyday_vi": "vừa vặn (quần áo); phù hợp",
      "meaning_ai_vi": "văn bản 'vừa' vào context window không",
      "example_en": "Does it fit in the window?",
      "example_vi": "Nó có vừa cửa sổ không?",
      "tip_vi": "'Fit in' = vừa vào, 'fit into'." },

    { "id": "exceed", "word": "exceed", "ipa": "/ɪkˈsiːd/", "pos": "verb", "topic": "tokens",
      "meaning_everyday_vi": "vượt quá (giới hạn, tốc độ)",
      "meaning_ai_vi": "vượt quá giới hạn token cho phép",
      "example_en": "Don't exceed the token limit.",
      "example_vi": "Đừng vượt quá giới hạn token.",
      "tip_vi": "Đối ngược: 'be within' (trong giới hạn)." },

    { "id": "budget", "word": "budget", "ipa": "/ˈbʌdʒɪt/", "pos": "noun", "topic": "tokens",
      "meaning_everyday_vi": "ngân sách (tiền)",
      "meaning_ai_vi": "ngân sách token — số token bạn dự định dùng",
      "example_en": "Plan your token budget.",
      "example_vi": "Lập kế hoạch ngân sách token.",
      "tip_vi": "Phát âm: 'BÂ-jịt'." },

    { "id": "compress", "word": "compress", "ipa": "/kəmˈpres/", "pos": "verb", "topic": "tokens",
      "meaning_everyday_vi": "nén lại (file, không khí)",
      "meaning_ai_vi": "tóm gọn nội dung để dùng ít token hơn",
      "example_en": "Compress the long history.",
      "example_vi": "Nén bớt lịch sử dài.",
      "tip_vi": "Danh từ: 'compression' (sự nén)." },

    { "id": "tokenize", "word": "tokenize", "ipa": "/ˈtəʊkənaɪz/", "pos": "verb", "topic": "tokens",
      "meaning_everyday_vi": "không có nghĩa thường ngày",
      "meaning_ai_vi": "tách văn bản thành các token",
      "example_en": "Tokenize the text first.",
      "example_vi": "Hãy token hóa văn bản trước.",
      "tip_vi": "Cùng họ: token → tokenize → tokenization." },

    { "id": "zero-shot", "word": "zero-shot", "ipa": "/ˈzɪərəʊ ʃɒt/", "pos": "adj", "topic": "prompting",
      "meaning_everyday_vi": "không có nghĩa thường ngày",
      "meaning_ai_vi": "yêu cầu AI làm mà không cho ví dụ nào",
      "example_en": "Try a zero-shot prompt first.",
      "example_vi": "Thử lời nhắc không ví dụ trước.",
      "tip_vi": "'Zero' = 0 ví dụ. Đối ngược: few-shot." },

    { "id": "few-shot", "word": "few-shot", "ipa": "/fjuː ʃɒt/", "pos": "adj", "topic": "prompting",
      "meaning_everyday_vi": "không có nghĩa thường ngày",
      "meaning_ai_vi": "cho AI vài ví dụ trước để nó hiểu mẫu",
      "example_en": "Use few-shot for better results.",
      "example_vi": "Dùng vài ví dụ để kết quả tốt hơn.",
      "tip_vi": "Thường 2-5 ví dụ là đủ." },

    { "id": "chain-of-thought", "word": "chain-of-thought", "ipa": "/tʃeɪn əv ˈθɔːt/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "chuỗi suy nghĩ",
      "meaning_ai_vi": "yêu cầu AI suy nghĩ từng bước trước khi trả lời",
      "example_en": "Use chain-of-thought for math.",
      "example_vi": "Dùng chuỗi suy nghĩ cho bài toán.",
      "tip_vi": "Viết tắt 'CoT'. Hay dùng cho việc cần logic." },

    { "id": "persona", "word": "persona", "ipa": "/pəˈsəʊnə/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "tính cách thể hiện ra ngoài",
      "meaning_ai_vi": "vai bạn gán cho AI (ví dụ: 'bạn là giáo viên')",
      "example_en": "Give Claude a teacher persona.",
      "example_vi": "Hãy cho Claude vai giáo viên.",
      "tip_vi": "'You are a...' = cách dễ nhất để gán persona." },

    { "id": "constraint", "word": "constraint", "ipa": "/kənˈstreɪnt/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "sự ràng buộc, hạn chế",
      "meaning_ai_vi": "quy tắc bạn đặt cho AI (vd: trả lời ≤ 100 từ)",
      "example_en": "Add a length constraint.",
      "example_vi": "Thêm ràng buộc về độ dài.",
      "tip_vi": "Càng cụ thể, AI càng dễ tuân theo." },

    { "id": "format", "word": "format", "ipa": "/ˈfɔːmæt/", "pos": "noun, verb", "topic": "prompting",
      "meaning_everyday_vi": "định dạng (file, văn bản)",
      "meaning_ai_vi": "cách bạn muốn câu trả lời (JSON, bảng, danh sách...)",
      "example_en": "Reply in JSON format.",
      "example_vi": "Trả lời theo định dạng JSON.",
      "tip_vi": "Yêu cầu format rõ → đỡ phải sửa sau." },

    { "id": "specific", "word": "specific", "ipa": "/spəˈsɪfɪk/", "pos": "adj", "topic": "prompting",
      "meaning_everyday_vi": "cụ thể, rõ ràng",
      "meaning_ai_vi": "lời nhắc cụ thể → AI trả lời cụ thể",
      "example_en": "Be specific in your prompt.",
      "example_vi": "Hãy cụ thể trong lời nhắc.",
      "tip_vi": "Đối ngược: 'vague' (mơ hồ)." },

    { "id": "concise", "word": "concise", "ipa": "/kənˈsaɪs/", "pos": "adj", "topic": "prompting",
      "meaning_everyday_vi": "ngắn gọn, súc tích",
      "meaning_ai_vi": "yêu cầu AI trả lời ngắn gọn",
      "example_en": "Give a concise answer.",
      "example_vi": "Hãy trả lời ngắn gọn.",
      "tip_vi": "Phát âm: 'kân-SAI-sờ'." },

    { "id": "structure", "word": "structure", "ipa": "/ˈstrʌktʃə/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "cấu trúc (tòa nhà, câu)",
      "meaning_ai_vi": "cách tổ chức lời nhắc theo phần (mục tiêu, ví dụ, định dạng)",
      "example_en": "Use a clear structure.",
      "example_vi": "Hãy dùng cấu trúc rõ ràng.",
      "tip_vi": "Hay dùng XML tag để chia phần." },

    { "id": "template", "word": "template", "ipa": "/ˈtempleɪt/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "mẫu, khuôn (sẵn để dùng)",
      "meaning_ai_vi": "lời nhắc mẫu, có chỗ trống để điền",
      "example_en": "Save a prompt template.",
      "example_vi": "Lưu một mẫu lời nhắc.",
      "tip_vi": "Phát âm: 'TEM-plết'." },

    { "id": "variable", "word": "variable", "ipa": "/ˈveəriəbəl/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "biến (toán); thứ thay đổi được",
      "meaning_ai_vi": "phần trong template có thể thay (ví dụ: {tên}, {chủ_đề})",
      "example_en": "Replace the variable name.",
      "example_vi": "Thay biến 'tên' lại.",
      "tip_vi": "Hay viết trong dấu {} hoặc <>." },

    { "id": "placeholder", "word": "placeholder", "ipa": "/ˈpleɪshəʊldə/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "chỗ giữ tạm, vật thay thế",
      "meaning_ai_vi": "chỗ trống chờ điền giá trị thật vào",
      "example_en": "{name} is a placeholder.",
      "example_vi": "{tên} là một chỗ trống.",
      "tip_vi": "Giống 'variable' nhưng nhấn vào tính 'để trống'." },

    { "id": "draft", "word": "draft", "ipa": "/drɑːft/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "bản nháp; gió lùa",
      "meaning_ai_vi": "bản nháp đầu tiên AI viết ra (sẽ sửa lại sau)",
      "example_en": "Claude wrote a first draft.",
      "example_vi": "Claude đã viết bản nháp đầu.",
      "tip_vi": "'Draft' → 'refine' → 'finalize' là 3 bước." },

    { "id": "guideline", "word": "guideline", "ipa": "/ˈɡaɪdlaɪn/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "hướng dẫn, nguyên tắc chỉ đạo",
      "meaning_ai_vi": "quy tắc bạn đặt cho AI tuân theo",
      "example_en": "Follow the writing guidelines.",
      "example_vi": "Hãy tuân theo nguyên tắc viết.",
      "tip_vi": "Số nhiều 'guidelines' thường gặp hơn." },

    { "id": "clarity", "word": "clarity", "ipa": "/ˈklærɪti/", "pos": "noun", "topic": "prompting",
      "meaning_everyday_vi": "sự rõ ràng, trong suốt",
      "meaning_ai_vi": "lời nhắc rõ ràng = chất lượng quan trọng nhất",
      "example_en": "Clarity matters in prompts.",
      "example_vi": "Sự rõ ràng quan trọng trong lời nhắc.",
      "tip_vi": "Cùng họ: clear → clarify → clarity." },

    { "id": "tool", "word": "tool", "ipa": "/tuːl/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "công cụ (búa, kéo)",
      "meaning_ai_vi": "hàm/chức năng AI có thể gọi để làm việc (tìm web, đọc file...)",
      "example_en": "Claude can use tools.",
      "example_vi": "Claude có thể dùng công cụ.",
      "tip_vi": "'Tool use' = một capability quan trọng của Claude." },

    { "id": "function", "word": "function", "ipa": "/ˈfʌŋkʃən/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "chức năng; tiệc (formal)",
      "meaning_ai_vi": "hàm code AI có thể gọi (function calling)",
      "example_en": "Define the function clearly.",
      "example_vi": "Hãy định nghĩa hàm rõ ràng.",
      "tip_vi": "'Function calling' = thuật ngữ cũ của 'tool use'." },

    { "id": "call", "word": "call", "ipa": "/kɔːl/", "pos": "verb", "topic": "tools",
      "meaning_everyday_vi": "gọi điện; gọi ai đó",
      "meaning_ai_vi": "AI 'gọi' một công cụ để thực thi",
      "example_en": "Claude called the tool.",
      "example_vi": "Claude đã gọi công cụ.",
      "tip_vi": "'Tool call' = một lượt AI gọi công cụ." },

    { "id": "argument", "word": "argument", "ipa": "/ˈɑːɡjumənt/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "cuộc tranh cãi; lý lẽ",
      "meaning_ai_vi": "tham số AI truyền khi gọi hàm",
      "example_en": "Pass two arguments.",
      "example_vi": "Truyền hai tham số.",
      "tip_vi": "Trong code: argument = giá trị truyền vào hàm." },

    { "id": "return", "word": "return", "ipa": "/rɪˈtɜːn/", "pos": "verb", "topic": "tools",
      "meaning_everyday_vi": "trở về; trả lại",
      "meaning_ai_vi": "hàm 'trả về' kết quả cho AI sau khi chạy xong",
      "example_en": "The function returns a number.",
      "example_vi": "Hàm trả về một số.",
      "tip_vi": "'Return value' = giá trị trả về." },

    { "id": "execute", "word": "execute", "ipa": "/ˈeksɪkjuːt/", "pos": "verb", "topic": "tools",
      "meaning_everyday_vi": "thi hành (kế hoạch); xử tử",
      "meaning_ai_vi": "chạy / thực thi đoạn code",
      "example_en": "Execute the script.",
      "example_vi": "Hãy chạy đoạn script.",
      "tip_vi": "Phát âm: 'EK-xi-kiut'." },

    { "id": "action", "word": "action", "ipa": "/ˈækʃən/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "hành động, hoạt động",
      "meaning_ai_vi": "việc AI quyết định làm (gọi tool, tìm web...)",
      "example_en": "The agent took an action.",
      "example_vi": "Tác nhân đã thực hiện hành động.",
      "tip_vi": "Phát âm: 'ÉC-shần'." },

    { "id": "agent", "word": "agent", "ipa": "/ˈeɪdʒənt/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "đại lý, điệp viên",
      "meaning_ai_vi": "AI biết tự lập kế hoạch và dùng nhiều tool để đạt mục tiêu",
      "example_en": "Build an AI agent.",
      "example_vi": "Hãy xây một tác nhân AI.",
      "tip_vi": "'Agentic' = mang tính tự chủ." },

    { "id": "autonomous", "word": "autonomous", "ipa": "/ɔːˈtɒnəməs/", "pos": "adj", "topic": "tools",
      "meaning_everyday_vi": "tự trị, tự chủ (xe tự lái)",
      "meaning_ai_vi": "AI làm việc một mình, không cần con người duyệt từng bước",
      "example_en": "An autonomous agent works alone.",
      "example_vi": "Một tác nhân tự chủ làm việc một mình.",
      "tip_vi": "'Auto-' = tự. 'Autonomous' = tự chủ hoàn toàn." },

    { "id": "workflow", "word": "workflow", "ipa": "/ˈwɜːkfləʊ/", "pos": "noun", "topic": "tools",
      "meaning_everyday_vi": "quy trình làm việc",
      "meaning_ai_vi": "chuỗi bước AI làm để hoàn thành task",
      "example_en": "Design a clear workflow.",
      "example_vi": "Hãy thiết kế quy trình rõ ràng.",
      "tip_vi": "Ghép từ: work (việc) + flow (dòng chảy)." },

    { "id": "safety", "word": "safety", "ipa": "/ˈseɪfti/", "pos": "noun", "topic": "safety",
      "meaning_everyday_vi": "sự an toàn",
      "meaning_ai_vi": "đảm bảo AI không gây hại",
      "example_en": "Safety is important.",
      "example_vi": "An toàn rất quan trọng.",
      "tip_vi": "Tính từ: 'safe' (an toàn)." },

    { "id": "harmful", "word": "harmful", "ipa": "/ˈhɑːmfəl/", "pos": "adj", "topic": "safety",
      "meaning_everyday_vi": "có hại (sức khỏe, môi trường)",
      "meaning_ai_vi": "nội dung gây hại — AI sẽ từ chối",
      "example_en": "Claude refuses harmful requests.",
      "example_vi": "Claude từ chối yêu cầu có hại.",
      "tip_vi": "'Harm' (hại) + 'ful' = có hại." },

    { "id": "refuse", "word": "refuse", "ipa": "/rɪˈfjuːz/", "pos": "verb", "topic": "safety",
      "meaning_everyday_vi": "từ chối",
      "meaning_ai_vi": "AI từ chối làm việc có hại / phi đạo đức",
      "example_en": "Claude will refuse to help.",
      "example_vi": "Claude sẽ từ chối giúp.",
      "tip_vi": "Đừng nhầm với 'refuse' /ˈrefjuːs/ = rác." },

    { "id": "bias", "word": "bias", "ipa": "/ˈbaɪəs/", "pos": "noun", "topic": "safety",
      "meaning_everyday_vi": "thiên kiến, định kiến",
      "meaning_ai_vi": "AI ưu tiên/né tránh một nhóm/ý tưởng do dữ liệu huấn luyện",
      "example_en": "AI can have bias.",
      "example_vi": "AI có thể có thiên kiến.",
      "tip_vi": "Phát âm: 'BAI-ợs', không phải 'bi-ờs'." },

    { "id": "hallucination", "word": "hallucination", "ipa": "/həˌluːsɪˈneɪʃən/", "pos": "noun", "topic": "safety",
      "meaning_everyday_vi": "ảo giác (thấy thứ không có)",
      "meaning_ai_vi": "AI bịa thông tin sai nhưng tự tin nói",
      "example_en": "Watch out for hallucinations.",
      "example_vi": "Coi chừng AI bịa thông tin.",
      "tip_vi": "Luôn kiểm tra số liệu/sự kiện AI đưa ra." },

    { "id": "accurate", "word": "accurate", "ipa": "/ˈækjərət/", "pos": "adj", "topic": "safety",
      "meaning_everyday_vi": "chính xác, đúng",
      "meaning_ai_vi": "thông tin AI đưa ra đúng sự thật",
      "example_en": "Make sure the answer is accurate.",
      "example_vi": "Hãy chắc chắn câu trả lời chính xác.",
      "tip_vi": "Danh từ: 'accuracy' (độ chính xác)." },

    { "id": "ethical", "word": "ethical", "ipa": "/ˈeθɪkəl/", "pos": "adj", "topic": "safety",
      "meaning_everyday_vi": "có đạo đức, hợp đạo đức",
      "meaning_ai_vi": "AI hành xử theo nguyên tắc đạo đức",
      "example_en": "Anthropic focuses on ethical AI.",
      "example_vi": "Anthropic tập trung vào AI có đạo đức.",
      "tip_vi": "Danh từ: 'ethics' (đạo đức học)." },

    { "id": "responsible", "word": "responsible", "ipa": "/rɪˈspɒnsəbəl/", "pos": "adj", "topic": "safety",
      "meaning_everyday_vi": "có trách nhiệm",
      "meaning_ai_vi": "phát triển AI một cách có trách nhiệm",
      "example_en": "Responsible AI is the goal.",
      "example_vi": "AI có trách nhiệm là mục tiêu.",
      "tip_vi": "Danh từ: 'responsibility' (trách nhiệm)." },

    { "id": "guardrail", "word": "guardrail", "ipa": "/ˈɡɑːdreɪl/", "pos": "noun", "topic": "safety",
      "meaning_everyday_vi": "rào chắn (đường cao tốc)",
      "meaning_ai_vi": "rào chắn an toàn để AI không đi quá giới hạn",
      "example_en": "Add guardrails to your AI.",
      "example_vi": "Hãy thêm rào chắn cho AI của bạn.",
      "tip_vi": "Ghép: guard (canh) + rail (đường ray)." },

    { "id": "alignment", "word": "alignment", "ipa": "/əˈlaɪnmənt/", "pos": "noun", "topic": "safety",
      "meaning_everyday_vi": "sự thẳng hàng; sự đồng thuận",
      "meaning_ai_vi": "AI căn chỉnh để hành xử theo ý người dùng",
      "example_en": "AI alignment is hard.",
      "example_vi": "Căn chỉnh AI rất khó.",
      "tip_vi": "Chủ đề nghiên cứu lớn của Anthropic." },

    { "id": "cache", "word": "cache", "ipa": "/kæʃ/", "pos": "noun, verb", "topic": "advanced",
      "meaning_everyday_vi": "nơi giấu đồ; bộ nhớ đệm máy tính",
      "meaning_ai_vi": "lưu prompt lại để gọi lần sau rẻ hơn (prompt caching)",
      "example_en": "Use prompt caching to save money.",
      "example_vi": "Dùng prompt caching để tiết kiệm.",
      "tip_vi": "Đọc giống 'cash' (tiền mặt), không phải 'kết-chê'." },

    { "id": "streaming", "word": "streaming", "ipa": "/ˈstriːmɪŋ/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "phát trực tiếp (YouTube, Netflix)",
      "meaning_ai_vi": "AI trả lời từng từ một thay vì chờ xong hết",
      "example_en": "Enable streaming for faster feel.",
      "example_vi": "Bật streaming để cảm giác nhanh hơn.",
      "tip_vi": "Streaming = chữ hiện dần. Non-stream = đợi xong mới hiện." },

    { "id": "batch", "word": "batch", "ipa": "/bætʃ/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "mẻ, lô (bánh, hàng)",
      "meaning_ai_vi": "gửi nhiều request cùng lúc — rẻ hơn nhưng chậm hơn",
      "example_en": "Batch processing is cheaper.",
      "example_vi": "Xử lý theo lô rẻ hơn.",
      "tip_vi": "Batch API của Anthropic giảm 50% giá." },

    { "id": "embedding", "word": "embedding", "ipa": "/ɪmˈbedɪŋ/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "không có nghĩa thường ngày",
      "meaning_ai_vi": "biểu diễn văn bản thành dãy số để máy so sánh ý nghĩa",
      "example_en": "Embeddings help with search.",
      "example_vi": "Embedding giúp tìm kiếm.",
      "tip_vi": "Cùng từ với 'embed' (nhúng vào)." },

    { "id": "vector", "word": "vector", "ipa": "/ˈvektə/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "vector (toán, lý)",
      "meaning_ai_vi": "dãy số biểu diễn ý nghĩa của text/ảnh",
      "example_en": "Store vectors in a database.",
      "example_vi": "Lưu vector vào cơ sở dữ liệu.",
      "tip_vi": "Embedding luôn ở dạng vector." },

    { "id": "retrieval", "word": "retrieval", "ipa": "/rɪˈtriːvəl/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "việc lấy lại, truy xuất",
      "meaning_ai_vi": "tìm thông tin liên quan từ kho tài liệu rồi đưa cho AI",
      "example_en": "Retrieval improves accuracy.",
      "example_vi": "Truy xuất tăng độ chính xác.",
      "tip_vi": "Động từ: 'retrieve' (lấy lại)." },

    { "id": "rag", "word": "RAG", "ipa": "/ræɡ/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "viết tắt Retrieval-Augmented Generation",
      "meaning_ai_vi": "tìm tài liệu rồi đưa cho AI để nó trả lời chính xác hơn",
      "example_en": "RAG reduces hallucinations.",
      "example_vi": "RAG giảm AI bịa thông tin.",
      "tip_vi": "Đọc như từ 'rag' (giẻ rách), 1 âm tiết." },

    { "id": "multimodal", "word": "multimodal", "ipa": "/ˌmʌltiˈməʊdəl/", "pos": "adj", "topic": "advanced",
      "meaning_everyday_vi": "không có nghĩa thường ngày",
      "meaning_ai_vi": "AI hiểu nhiều dạng dữ liệu (text + ảnh + âm thanh)",
      "example_en": "Claude is multimodal.",
      "example_vi": "Claude là AI đa phương thức.",
      "tip_vi": "'Multi' = nhiều, 'modal' = phương thức." },

    { "id": "vision", "word": "vision", "ipa": "/ˈvɪʒən/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "thị giác, tầm nhìn",
      "meaning_ai_vi": "khả năng AI nhìn và hiểu ảnh",
      "example_en": "Claude has vision support.",
      "example_vi": "Claude hỗ trợ thị giác.",
      "tip_vi": "Phát âm: 'VI-zhần', âm 'zh' giống tiếng Pháp." },

    { "id": "image", "word": "image", "ipa": "/ˈɪmɪdʒ/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "hình ảnh, ảnh",
      "meaning_ai_vi": "ảnh bạn gửi cho AI nhìn",
      "example_en": "Upload an image to Claude.",
      "example_vi": "Tải ảnh lên cho Claude.",
      "tip_vi": "Phát âm: 'I-mij', không phải 'i-mê-jơ'." },

    { "id": "document", "word": "document", "ipa": "/ˈdɒkjumənt/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "tài liệu, văn bản",
      "meaning_ai_vi": "file (PDF, Word) bạn đưa cho AI đọc",
      "example_en": "Claude can read documents.",
      "example_vi": "Claude có thể đọc tài liệu.",
      "tip_vi": "Phát âm danh từ: 'ĐO-kiu-mần'." },

    { "id": "citation", "word": "citation", "ipa": "/saɪˈteɪʃən/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "trích dẫn (nguồn, sách)",
      "meaning_ai_vi": "AI chỉ ra phần tài liệu nó dựa vào để trả lời",
      "example_en": "Show citations in the answer.",
      "example_vi": "Hãy hiện trích dẫn trong câu trả lời.",
      "tip_vi": "Citation giúp kiểm tra AI có bịa không." },

    { "id": "latency", "word": "latency", "ipa": "/ˈleɪtənsi/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "độ trễ (mạng, game)",
      "meaning_ai_vi": "thời gian từ lúc gửi đến lúc nhận câu trả lời",
      "example_en": "Low latency feels fast.",
      "example_vi": "Độ trễ thấp cảm giác nhanh.",
      "tip_vi": "Latency thấp = tốt. Latency cao = chậm." },

    { "id": "throughput", "word": "throughput", "ipa": "/ˈθruːpʊt/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "thông lượng (sản xuất, mạng)",
      "meaning_ai_vi": "số request/giây AI xử lý được",
      "example_en": "Higher throughput is better.",
      "example_vi": "Thông lượng cao thì tốt hơn.",
      "tip_vi": "Phát âm âm 'th' /θ/, không phải /t/." },

    { "id": "inference", "word": "inference", "ipa": "/ˈɪnfərəns/", "pos": "noun", "topic": "advanced",
      "meaning_everyday_vi": "suy luận, suy diễn",
      "meaning_ai_vi": "quá trình AI 'chạy' để tạo ra câu trả lời",
      "example_en": "Inference takes time and money.",
      "example_vi": "Suy luận tốn thời gian và tiền.",
      "tip_vi": "Khác với 'training' (huấn luyện). Inference = lúc dùng." }
  ]
}
;
