// Dữ liệu hội thoại Msutong Sơ cấp B2 (Bài 1-10)
// Trích từ hoi-thoai-b2-bai-1-10.md — 20 bài học (mỗi "Bài khóa" = 1 lesson).

(function () {
  window.dialogueBooks = window.dialogueBooks || [];
  window.dialogueBooks.push({
    id: "msutong-b2",
    shortName: "B2",
    name: "Msutong Sơ cấp B2",
    lessons: [
      // ===== Bài 1 =====
      {
        id: "b2-1-1",
        baiNumber: 1,
        baiTitleZh: "你在听什么？",
        baiTitleVi: "Bạn đang nghe gì vậy?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "田中，你在做什么？", pinyin: "tián zhōng， nǐ zài zuò shén me？", vi: "Tanaka, cậu đang làm gì vậy?" },
          { role: "田中", zh: "我在听音乐。", pinyin: "wǒ zài tīng yīn yuè。", vi: "Tớ đang nghe nhạc." },
          { role: "海伦", zh: "听什么音乐？", pinyin: "tīng shén me yīn yuè？", vi: "Nghe nhạc gì vậy?" },
          { role: "田中", zh: "我在听中国音乐，很好听！", pinyin: "wǒ zài tīng zhōng guó yīn yuè， hěn hǎo tīng！", vi: "Tớ đang nghe nhạc Trung Quốc, rất hay!" },
          { role: "海伦", zh: "你喜欢一边看书，一边听音乐？", pinyin: "nǐ xǐ huān yī biān kàn shū， yī biān tīng yīn yuè？", vi: "Cậu thích vừa đọc sách vừa nghe nhạc à?" },
          { role: "田中", zh: "对，你喜欢听音乐吗？", pinyin: "duì， nǐ xǐ huān tīng yīn yuè ma？", vi: "Đúng vậy, cậu có thích nghe nhạc không?" },
          { role: "海伦", zh: "很喜欢，我常常一边走路，一边听音乐。", pinyin: "hěn xǐ huān， wǒ cháng cháng yī biān zǒu lù， yī biān tīng yīn yuè。", vi: "Rất thích, tớ thường vừa đi đường vừa nghe nhạc." },
          { role: "田中", zh: "你喜欢唱歌吗？", pinyin: "nǐ xǐ huān chàng gē ma？", vi: "Cậu có thích hát không?" },
          { role: "海伦", zh: "我不喜欢唱歌，我只喜欢听歌。你呢？", pinyin: "wǒ bù xǐ huān chàng gē， wǒ zhǐ xǐ huān tīng gē。 nǐ ne？", vi: "Tớ không thích hát, tớ chỉ thích nghe thôi. Còn cậu?" },
          { role: "田中", zh: "我很喜欢唱歌，我喜欢唱英文歌。", pinyin: "wǒ hěn xǐ huān chàng gē， wǒ xǐ huān chàng yīng wén gē。", vi: "Tớ rất thích hát, tớ thích hát bài hát tiếng Anh." },
          { role: "海伦", zh: "太好了，我很喜欢听英文歌。你唱一个，好吗？", pinyin: "tài hǎo le， wǒ hěn xǐ huān tīng yīng wén gē。 nǐ chàng yí gè， hǎo ma？", vi: "Hay quá, tớ rất thích nghe bài hát tiếng Anh. Cậu hát một bài đi, được không?" },
          { role: "田中", zh: "不行，不行，下次吧！", pinyin: "bù xíng， bù xíng， xià cì ba！", vi: "Không được, không được, lần sau đi!" },
        ],
      },
      {
        id: "b2-1-2",
        baiNumber: 1,
        baiTitleZh: "你在听什么？",
        baiTitleVi: "Bạn đang nghe gì vậy?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "卡玛拉，你平时喜欢做什么？", pinyin: "kǎ mǎ lā， nǐ píng shí xǐ huān zuò shén me？", vi: "Kamala, ngày thường cậu thích làm gì?" },
          { role: "卡玛拉", zh: "我喜欢打球，还喜欢看电影和电视。你呢？", pinyin: "wǒ xǐ huān dǎ qiú， hái xǐ huān kàn diàn yǐng hé diàn shì。 nǐ ne？", vi: "Tớ thích chơi bóng, còn thích xem phim và xem TV nữa. Còn cậu?" },
          { role: "欧文", zh: "我也喜欢看电影，我还喜欢看书和跳舞。", pinyin: "wǒ yě xǐ huān kàn diàn yǐng， wǒ hái xǐ huān kàn shū hé tiào wǔ。", vi: "Tớ cũng thích xem phim, tớ còn thích đọc sách và nhảy nữa." },
          { role: "卡玛拉", zh: "你喜欢跳什么舞？", pinyin: "nǐ xǐ huān tiào shén me wǔ？", vi: "Cậu thích nhảy điệu gì?" },
          { role: "欧文", zh: "我喜欢跳街舞。你喜欢跳舞吗？", pinyin: "wǒ xǐ huān tiào jiē wǔ。 nǐ xǐ huān tiào wǔ ma？", vi: "Tớ thích nhảy hip-hop. Cậu có thích nhảy không?" },
          { role: "卡玛拉", zh: "不喜欢，我只喜欢看别人跳舞。", pinyin: "bù xǐ huān， wǒ zhǐ xǐ huān kàn bié rén tiào wǔ。", vi: "Không thích, tớ chỉ thích xem người khác nhảy." },
          { role: "欧文", zh: "你喜欢打球吗？", pinyin: "nǐ xǐ huān dǎ qiú ma？", vi: "Cậu có thích chơi bóng không?" },
          { role: "卡玛拉", zh: "我喜欢打篮球。你喜欢吗？", pinyin: "wǒ xǐ huān dǎ lán qiú。 nǐ xǐ huān ma？", vi: "Tớ thích chơi bóng rổ. Cậu có thích không?" },
          { role: "欧文", zh: "我不喜欢打球，我只喜欢看球。", pinyin: "wǒ bù xǐ huān dǎ qiú， wǒ zhǐ xǐ huān kàn qiú。", vi: "Tớ không thích chơi bóng, tớ chỉ thích xem bóng thôi." },
          { role: "卡玛拉", zh: "我也喜欢看球，我很喜欢看NBA。", pinyin: "wǒ yě xǐ huān kàn qiú， wǒ hěn xǐ huān kàn NBA。", vi: "Tớ cũng thích xem bóng, tớ rất thích xem NBA." },
          { role: "欧文", zh: "我也是，下个周末我们一起看吧！", pinyin: "wǒ yě shì， xià gè zhōu mò wǒ men yì qǐ kàn ba！", vi: "Tớ cũng vậy, cuối tuần sau chúng ta cùng xem nhé!" },
        ],
      },

      // ===== Bài 2 =====
      {
        id: "b2-2-1",
        baiNumber: 2,
        baiTitleZh: "你平时几点起床？",
        baiTitleVi: "Bạn thường ngày ngủ dậy lúc mấy giờ?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "欧文，现在几点？", pinyin: "ōu wén， xiàn zài jǐ diǎn？", vi: "Owen, bây giờ là mấy giờ?" },
          { role: "欧文", zh: "八点一刻。你今天几点上课？", pinyin: "bā diǎn yī kè。 nǐ jīn tiān jǐ diǎn shàng kè？", vi: "Tám giờ mười lăm. Hôm nay cậu mấy giờ vào học?" },
          { role: "海伦", zh: "九点。你呢？", pinyin: "jiǔ diǎn。 nǐ ne？", vi: "Chín giờ. Còn cậu?" },
          { role: "欧文", zh: "我今天九点五十五（分）上课。", pinyin: "wǒ jīn tiān jiǔ diǎn wǔ shí wǔ （ fēn ） shàng kè。", vi: "Hôm nay tớ vào học lúc chín giờ năm mươi lăm phút." },
          { role: "海伦", zh: "你几点下课？", pinyin: "nǐ jǐ diǎn xià kè？", vi: "Mấy giờ cậu tan học?" },
          { role: "欧文", zh: "十二点半。你呢？", pinyin: "shí èr diǎn bàn。 nǐ ne？", vi: "Mười hai giờ rưỡi. Còn cậu?" },
          { role: "海伦", zh: "我也是。", pinyin: "wǒ yě shì。", vi: "Tớ cũng vậy." },
          { role: "欧文", zh: "中午我们一起吃饭吧。", pinyin: "zhōng wǔ wǒ men yì qǐ chī fàn ba。", vi: "Trưa nay chúng ta cùng ăn cơm nhé." },
          { role: "海伦", zh: "好！我们吃什么？", pinyin: "hǎo！ wǒ men chī shén me？", vi: "Được! Chúng ta ăn gì?" },
          { role: "欧文", zh: "吃中国菜或者韩国菜吧。", pinyin: "chī zhōng guó cài huò zhě hán guó cài ba。", vi: "Ăn món Trung Quốc hoặc món Hàn Quốc đi." },
          { role: "海伦", zh: "好，中午十二点半在学校门口见！", pinyin: "hǎo， zhōng wǔ shí èr diǎn bàn zài xué xiào mén kǒu jiàn！", vi: "Được, trưa mười hai giờ rưỡi gặp ở cổng trường!" },
          { role: "欧文", zh: "十二点半见！", pinyin: "shí èr diǎn bàn jiàn！", vi: "Hẹn gặp lúc mười hai giờ rưỡi!" },
        ],
      },
      {
        id: "b2-2-2",
        baiNumber: 2,
        baiTitleZh: "你平时几点起床？",
        baiTitleVi: "Bạn thường ngày ngủ dậy lúc mấy giờ?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "欧文，你平时几点起床？", pinyin: "ōu wén， nǐ píng shí jǐ diǎn qǐ chuáng？", vi: "Owen, ngày thường cậu mấy giờ ngủ dậy?" },
          { role: "欧文", zh: "有时候七点左右，有时候八点左右。你呢？", pinyin: "yǒu shí hòu qī diǎn zuǒ yòu， yǒu shí hòu bā diǎn zuǒ yòu。 nǐ ne？", vi: "Có lúc khoảng bảy giờ, có lúc khoảng tám giờ. Còn cậu?" },
          { role: "海伦", zh: "我每天六点一刻起床。", pinyin: "wǒ měi tiān liù diǎn yī kè qǐ chuáng。", vi: "Tớ mỗi ngày dậy lúc sáu giờ mười lăm." },
          { role: "欧文", zh: "这么早！你平时几点睡觉？", pinyin: "zhè me zǎo！ nǐ píng shí jǐ diǎn shuì jiào？", vi: "Sớm vậy! Ngày thường cậu mấy giờ đi ngủ?" },
          { role: "海伦", zh: "九点或者十点左右睡。", pinyin: "jiǔ diǎn huò zhě shí diǎn zuǒ yòu shuì。", vi: "Khoảng chín giờ hoặc mười giờ thì ngủ." },
          { role: "欧文", zh: "怎么这么早？", pinyin: "zěn me zhè me zǎo？", vi: "Sao sớm vậy?" },
          { role: "海伦", zh: "因为我喜欢早睡早起。你呢？", pinyin: "yīn wèi wǒ xǐ huān zǎo shuì zǎo qǐ。 nǐ ne？", vi: "Vì tớ thích ngủ sớm dậy sớm. Còn cậu?" },
          { role: "欧文", zh: "我平时十二点左右睡觉。", pinyin: "wǒ píng shí shí èr diǎn zuǒ yòu shuì jiào。", vi: "Ngày thường tớ đi ngủ khoảng mười hai giờ." },
          { role: "海伦", zh: "怎么这么晚？", pinyin: "zěn me zhè me wǎn？", vi: "Sao muộn vậy?" },
          { role: "欧文", zh: "因为我每天都有很多事。", pinyin: "yīn wèi wǒ měi tiān dōu yǒu hěn duō shì。", vi: "Vì mỗi ngày tớ có rất nhiều việc." },
        ],
      },

      // ===== Bài 3 =====
      {
        id: "b2-3-1",
        baiNumber: 3,
        baiTitleZh: "可以用一下你的手机吗？",
        baiTitleVi: "Có thể mượn điện thoại của bạn một lát được không?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "田中", zh: "美京，我明天可以给你打电话吗？", pinyin: "měi jīng， wǒ míng tiān kě yǐ gěi nǐ dǎ diàn huà ma？", vi: "Mỹ Kinh, mai tớ có thể gọi điện cho cậu không?" },
          { role: "美京", zh: "可以。", pinyin: "kě yǐ。", vi: "Được." },
          { role: "田中", zh: "可是我没有你的电话号码，你的手机号是多少？", pinyin: "kě shì wǒ méi yǒu nǐ de diàn huà hào mǎ， nǐ de shǒu jī hào shì duō shǎo？", vi: "Nhưng tớ không có số điện thoại của cậu, số di động của cậu là bao nhiêu?" },
          { role: "美京", zh: "我的手机号是136-1847-2834。", pinyin: "wǒ de shǒu jī hào shì 136-1847-2834。", vi: "Số di động của tớ là 136-1847-2834." },
          { role: "田中", zh: "等一下，可以借一下你的笔吗？我写一下。", pinyin: "děng yí xià， kě yǐ jiè yī xià nǐ de bǐ ma？ wǒ xiě yī xià。", vi: "Đợi một chút, cho tớ mượn bút được không? Tớ viết lại." },
          { role: "美京", zh: "可以。", pinyin: "kě yǐ。", vi: "Được." },
          { role: "田中", zh: "谢谢。", pinyin: "xiè xiè。", vi: "Cảm ơn." },
          { role: "美京", zh: "我的手机号是136-1847-2834。", pinyin: "wǒ de shǒu jī hào shì 136-1847-2834。", vi: "Số di động của tớ là 136-1847-2834." },
          { role: "田中", zh: "你慢一点儿。", pinyin: "nǐ màn yì diǎn ér。", vi: "Cậu nói chậm một chút." },
          { role: "美京", zh: "136-1847-2834。", pinyin: "136-1847-2834。", vi: "136-1847-2834." },
          { role: "田中", zh: "好，我明天给你打电话。", pinyin: "hǎo， wǒ míng tiān gěi nǐ dǎ diàn huà。", vi: "Được, mai tớ sẽ gọi điện cho cậu." },
        ],
      },
      {
        id: "b2-3-2",
        baiNumber: 3,
        baiTitleZh: "可以用一下你的手机吗？",
        baiTitleVi: "Có thể mượn điện thoại của bạn một lát được không?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "田中，可以用一下你的电脑吗？", pinyin: "tián zhōng， kě yǐ yòng yī xià nǐ de diàn nǎo ma？", vi: "Tanaka, cho tớ mượn máy tính của cậu một lát được không?" },
          { role: "田中", zh: "可以，你用吧。", pinyin: "kě yǐ， nǐ yòng ba。", vi: "Được, cậu dùng đi." },
          { role: "海伦", zh: "谢谢！我用一下，很快就好。", pinyin: "xiè xiè！ wǒ yòng yī xià， hěn kuài jiù hǎo。", vi: "Cảm ơn! Tớ dùng một lát thôi, sẽ xong ngay." },
          { role: "田中", zh: "没关系，我现在不用。对了，可不可以借一下你的手机？我的手机没电了。", pinyin: "méi guān xì， wǒ xiàn zài bù yòng。 duì le， kě bù kě yǐ jiè yī xià nǐ de shǒu jī？ wǒ de shǒu jī méi diàn le。", vi: "Không sao, bây giờ tớ không dùng. À, có thể cho tớ mượn điện thoại của cậu không? Điện thoại của tớ hết pin rồi." },
          { role: "海伦", zh: "没问题，给。", pinyin: "méi wèn tí， gěi。", vi: "Không vấn đề gì, đây." },
          { role: "田中", zh: "谢谢。我想给黄老师打个电话。", pinyin: "xiè xiè。 wǒ xiǎng gěi huáng lǎo shī dǎ gè diàn huà。", vi: "Cảm ơn. Tớ muốn gọi điện cho cô Hoàng." },
          { role: "海伦", zh: "你有黄老师的电话号码吗？", pinyin: "nǐ yǒu huáng lǎo shī de diàn huà hào mǎ ma？", vi: "Cậu có số điện thoại của cô Hoàng không?" },
          { role: "田中", zh: "我没有，你有吗？", pinyin: "wǒ méi yǒu， nǐ yǒu ma？", vi: "Tớ không có, cậu có không?" },
          { role: "海伦", zh: "有，我找一下。……在这儿，你打吧。", pinyin: "yǒu， wǒ zhǎo yī xià。…… zài zhè ér， nǐ dǎ ba。", vi: "Có, để tớ tìm... Đây rồi, cậu gọi đi." },
          { role: "田中", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        ],
      },

      // ===== Bài 4 =====
      {
        id: "b2-4-1",
        baiNumber: 4,
        baiTitleZh: "你想要哪件？",
        baiTitleVi: "Bạn muốn lấy chiếc nào?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "营业员", zh: "先生，您想买什么衣服？", pinyin: "xiān shēng， nín xiǎng mǎi shén me yī fú？", vi: "Anh ơi, anh muốn mua đồ gì ạ?" },
          { role: "田中", zh: "我想买一件衬衫。", pinyin: "wǒ xiǎng mǎi yī jiàn chèn shān。", vi: "Tôi muốn mua một chiếc áo sơ mi." },
          { role: "营业员", zh: "好的，我们有黑色的、红色的和蓝色的，您可以都试一下。", pinyin: "hǎo de， wǒ men yǒu hēi sè de、 hóng sè de hé lán sè de， nín kě yǐ dōu shì yī xià。", vi: "Vâng ạ, chúng tôi có màu đen, màu đỏ và màu xanh, anh có thể thử cả ba." },
          { role: "田中", zh: "我想试一下黑色的和红色的。", pinyin: "wǒ xiǎng shì yī xià hēi sè de hé hóng sè de。", vi: "Tôi muốn thử cái màu đen và cái màu đỏ." },
          { role: "营业员", zh: "好的，您穿什么号的？", pinyin: "hǎo de， nín chuān shén me hào de？", vi: "Vâng, anh mặc cỡ nào ạ?" },
          { role: "田中", zh: "我穿大号的。", pinyin: "wǒ chuān dà hào de。", vi: "Tôi mặc cỡ lớn." },
          { role: "营业员", zh: "给您。", pinyin: "gěi nín。", vi: "Đây ạ." },
          { role: "田中", zh: "谢谢。", pinyin: "xiè xiè。", vi: "Cảm ơn." },
          { role: "营业员", zh: "怎么样？您觉得哪件合适？", pinyin: "zěn me yàng？ nín jué de nǎ jiàn hé shì？", vi: "Thế nào ạ? Anh thấy chiếc nào vừa?" },
          { role: "田中", zh: "我觉得都不太合适。谢谢。", pinyin: "wǒ jué de dōu bù tài hé shì。 xiè xiè。", vi: "Tôi thấy đều không vừa lắm. Cảm ơn." },
          { role: "营业员", zh: "不客气！", pinyin: "bú kè qì！", vi: "Không có gì ạ!" },
        ],
      },
      {
        id: "b2-4-2",
        baiNumber: 4,
        baiTitleZh: "你想要哪件？",
        baiTitleVi: "Bạn muốn lấy chiếc nào?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "美京", zh: "请问，这双鞋有没有蓝色的？", pinyin: "qǐng wèn， zhè shuāng xié yǒu méi yǒu lán sè de？", vi: "Xin hỏi, đôi giày này có màu xanh không?" },
          { role: "营业员", zh: "没有蓝的，只有黑的。", pinyin: "méi yǒu lán de， zhǐ yǒu hēi de。", vi: "Không có màu xanh, chỉ có màu đen thôi." },
          { role: "美京", zh: "我可以试一下黑的吗？", pinyin: "wǒ kě yǐ shì yī xià hēi de ma？", vi: "Tôi có thể thử cái màu đen được không?" },
          { role: "营业员", zh: "可以。您穿多大号的？", pinyin: "kě yǐ。 nín chuān duō dà hào de？", vi: "Được. Chị đi cỡ bao nhiêu?" },
          { role: "美京", zh: "我穿38号的。", pinyin: "wǒ chuān 38 hào de。", vi: "Tôi đi cỡ 38." },
          { role: "营业员", zh: "好的，请等一下。……给您。", pinyin: "hǎo de， qǐng děng yí xià。…… gěi nín。", vi: "Vâng, xin chờ một chút... Đây ạ." },
          { role: "美京", zh: "谢谢。……这双鞋大小很合适，颜色也不错。多少钱？", pinyin: "xiè xiè。…… zhè shuāng xié dà xiǎo hěn hé shì， yán sè yě bù cuò。 duō shǎo qián？", vi: "Cảm ơn... Đôi giày này vừa lắm, màu cũng đẹp. Bao nhiêu tiền vậy?" },
          { role: "营业员", zh: "450块。", pinyin: "450 kuài。", vi: "450 tệ." },
          { role: "美京", zh: "太贵了，可以便宜一点儿吗？", pinyin: "tài guì le， kě yǐ pián yi yì diǎn ér ma？", vi: "Đắt quá, có thể rẻ một chút được không?" },
          { role: "营业员", zh: "可以，400块怎么样？", pinyin: "kě yǐ，400 kuài zěn me yàng？", vi: "Được, 400 tệ thế nào?" },
          { role: "美京", zh: "再便宜一点儿吧！350怎么样？", pinyin: "zài pián yi yì diǎn ér ba！350 zěn me yàng？", vi: "Rẻ thêm một chút nữa đi! 350 thế nào?" },
          { role: "营业员", zh: "行。您还想买什么？", pinyin: "xíng。 nín hái xiǎng mǎi shén me？", vi: "Được. Chị còn muốn mua gì nữa không?" },
        ],
      },

      // ===== Bài 5 =====
      {
        id: "b2-5-1",
        baiNumber: 5,
        baiTitleZh: "你这个周末什么时候有空儿？",
        baiTitleVi: "Cuối tuần này khi nào bạn có thời gian rảnh?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "卡玛拉", zh: "喂，你好！是高小明吗？", pinyin: "wèi， nǐ hǎo！ shì gāo xiǎo míng ma？", vi: "Alô, xin chào! Có phải Cao Tiểu Minh không?" },
          { role: "高小明", zh: "我是，您哪位？", pinyin: "wǒ shì， nín nǎ wèi？", vi: "Tôi đây, bạn là ai?" },
          { role: "卡玛拉", zh: "我是卡玛拉。", pinyin: "wǒ shì kǎ mǎ lā。", vi: "Tớ là Kamala." },
          { role: "高小明", zh: "卡玛拉，你好！", pinyin: "kǎ mǎ lā， nǐ hǎo！", vi: "Kamala, chào cậu!" },
          { role: "卡玛拉", zh: "小明，这个周末你忙不忙？", pinyin: "xiǎo míng， zhè ge zhōu mò nǐ máng bù máng？", vi: "Tiểu Minh, cuối tuần này cậu có bận không?" },
          { role: "高小明", zh: "有点儿忙。什么事？", pinyin: "yǒu diǎn ér máng。 shén me shì？", vi: "Hơi bận một chút. Có chuyện gì vậy?" },
          { role: "卡玛拉", zh: "我下个星期有HSK考试，不知道怎么准备。你可以帮我吗？", pinyin: "wǒ xià gè xīng qī yǒu HSK kǎo shì， bù zhī dào zěn me zhǔn bèi。 nǐ kě yǐ bāng wǒ ma？", vi: "Tuần sau tớ có kỳ thi HSK, không biết chuẩn bị thế nào. Cậu giúp tớ được không?" },
          { role: "高小明", zh: "没问题。", pinyin: "méi wèn tí。", vi: "Không vấn đề gì." },
          { role: "卡玛拉", zh: "太好了。你周末什么时候有空儿？", pinyin: "tài hǎo le。 nǐ zhōu mò shén me shí hòu yǒu kòng er？", vi: "Tuyệt quá. Cuối tuần khi nào cậu có rảnh?" },
          { role: "高小明", zh: "我想一下，星期五晚上我要跟朋友一起吃饭，星期六上午我要跟朋友打篮球，星期天要参加篮球比赛，我只有星期六下午有空儿。", pinyin: "wǒ xiǎng yī xià， xīng qī wǔ wǎn shàng wǒ yào gēn péng yǒu yì qǐ chī fàn， xīng qī liù shàng wǔ wǒ yào gēn péng yǒu dǎ lán qiú， xīng qī tiān yào cān jiā lán qiú bǐ sài， wǒ zhǐ yǒu xīng qī liù xià wǔ yǒu kòng er。", vi: "Để tớ nghĩ xem, tối thứ Sáu tớ phải đi ăn cơm với bạn, sáng thứ Bảy tớ phải chơi bóng rổ với bạn, Chủ nhật phải tham gia giải bóng rổ, tớ chỉ rảnh chiều thứ Bảy thôi." },
          { role: "卡玛拉", zh: "那我们星期六下午三点在图书馆见吧！", pinyin: "nà wǒ men xīng qī liù xià wǔ sān diǎn zài tú shū guǎn jiàn ba！", vi: "Vậy chiều thứ Bảy ba giờ chúng ta gặp ở thư viện nhé!" },
          { role: "高小明", zh: "好！星期六下午见！", pinyin: "hǎo！ xīng qī liù xià wǔ jiàn！", vi: "Được! Hẹn gặp chiều thứ Bảy!" },
        ],
      },
      {
        id: "b2-5-2",
        baiNumber: 5,
        baiTitleZh: "你这个周末什么时候有空儿？",
        baiTitleVi: "Cuối tuần này khi nào bạn có thời gian rảnh?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "卡玛拉", zh: "喂，是小明吗？", pinyin: "wèi， shì xiǎo míng ma？", vi: "Alô, là Tiểu Minh phải không?" },
          { role: "高小明", zh: "我是，是卡玛拉吗？", pinyin: "wǒ shì， shì kǎ mǎ lā ma？", vi: "Tớ đây, là Kamala phải không?" },
          { role: "卡玛拉", zh: "是，你好！", pinyin: "shì， nǐ hǎo！", vi: "Đúng, chào cậu!" },
          { role: "高小明", zh: "你好！你的HSK考试怎么样？难不难？", pinyin: "nǐ hǎo！ nǐ de HSK kǎo shì zěn me yàng？ nán bù nán？", vi: "Chào cậu! Kỳ thi HSK của cậu thế nào? Có khó không?" },
          { role: "卡玛拉", zh: "不太难。谢谢你帮我。", pinyin: "bù tài nán。 xiè xiè nǐ bāng wǒ。", vi: "Không khó lắm. Cảm ơn cậu đã giúp tớ." },
          { role: "高小明", zh: "不客气！", pinyin: "bú kè qì！", vi: "Không có gì!" },
          { role: "卡玛拉", zh: "你明天晚上有空儿吗？我们一起喝咖啡。", pinyin: "nǐ míng tiān wǎn shàng yǒu kòng er ma？ wǒ men yì qǐ hē kā fēi。", vi: "Tối mai cậu có rảnh không? Chúng ta cùng đi uống cà phê." },
          { role: "高小明", zh: "明天晚上不行，我要跟朋友去超市。", pinyin: "míng tiān wǎn shàng bù xíng， wǒ yào gēn péng yǒu qù chāo shì。", vi: "Tối mai không được, tớ phải đi siêu thị với bạn." },
          { role: "卡玛拉", zh: "那星期六怎么样？", pinyin: "nà xīng qī liù zěn me yàng？", vi: "Vậy thứ Bảy thì sao?" },
          { role: "高小明", zh: "星期六也不行，我要跟朋友一起旅行。", pinyin: "xīng qī liù yě bù xíng， wǒ yào gēn péng yǒu yì qǐ lǚ xíng。", vi: "Thứ Bảy cũng không được, tớ phải đi du lịch với bạn." },
          { role: "卡玛拉", zh: "那下次吧！我下个星期再给你打电话！", pinyin: "nà xià cì ba！ wǒ xià gè xīng qī zài gěi nǐ dǎ diàn huà！", vi: "Vậy lần sau vậy! Tuần sau tớ sẽ gọi cho cậu lần nữa!" },
          { role: "高小明", zh: "可以，不好意思！", pinyin: "kě yǐ， bù hǎo yì sī！", vi: "Được, ngại quá!" },
        ],
      },

      // ===== Bài 6 =====
      {
        id: "b2-6-1",
        baiNumber: 6,
        baiTitleZh: "上个周末你做什么了？",
        baiTitleVi: "Cuối tuần trước bạn làm gì?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "田中，上个周末你做什么了？", pinyin: "tián zhōng， shàng gè zhōu mò nǐ zuò shén me le？", vi: "Tanaka, cuối tuần trước cậu làm gì vậy?" },
          { role: "田中", zh: "我买了一些东西。", pinyin: "wǒ mǎi le yī xiē dōng xī。", vi: "Tớ đã mua một số thứ." },
          { role: "海伦", zh: "你买了什么？", pinyin: "nǐ mǎi le shén me？", vi: "Cậu mua những gì?" },
          { role: "田中", zh: "我买了几件衣服和一双鞋，还买了一些吃的。海伦，你呢？", pinyin: "wǒ mǎi le jǐ jiàn yī fú hé yī shuāng xié， hái mǎi le yī xiē chī de。 hǎi lún， nǐ ne？", vi: "Tớ mua mấy bộ quần áo và một đôi giày, còn mua một ít đồ ăn nữa. Helen, còn cậu?" },
          { role: "海伦", zh: "我参观博物馆了。", pinyin: "wǒ cān guān bó wù guǎn le。", vi: "Tớ đi tham quan viện bảo tàng." },
          { role: "田中", zh: "哪个博物馆？", pinyin: "nǎ ge bó wù guǎn？", vi: "Viện bảo tàng nào?" },
          { role: "海伦", zh: "人民公园附近的博物馆。", pinyin: "rén mín gōng yuán fù jìn de bó wù guǎn。", vi: "Viện bảo tàng gần Công viên Nhân Dân." },
          { role: "田中", zh: "怎么样？", pinyin: "zěn me yàng？", vi: "Thế nào?" },
          { role: "海伦", zh: "那个博物馆非常大，也非常漂亮，门票也不贵。", pinyin: "nà ge bó wù guǎn fēi cháng dà， yě fēi cháng piào liàng， mén piào yě bù guì。", vi: "Viện bảo tàng đó rất lớn, cũng rất đẹp, vé vào cũng không đắt." },
          { role: "田中", zh: "下个周末我也去！", pinyin: "xià gè zhōu mò wǒ yě qù！", vi: "Cuối tuần sau tớ cũng đi!" },
        ],
      },
      {
        id: "b2-6-2",
        baiNumber: 6,
        baiTitleZh: "上个周末你做什么了？",
        baiTitleVi: "Cuối tuần trước bạn làm gì?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "高小明", zh: "卡玛拉，你看上去有点儿累，周末做什么了？", pinyin: "kǎ mǎ lā， nǐ kàn shàng qù yǒu diǎn ér lèi， zhōu mò zuò shén me le？", vi: "Kamala, trông cậu hơi mệt, cuối tuần cậu làm gì vậy?" },
          { role: "卡玛拉", zh: "我跟朋友去人民公园了。", pinyin: "wǒ gēn péng yǒu qù rén mín gōng yuán le。", vi: "Tớ cùng bạn đi Công viên Nhân Dân." },
          { role: "高小明", zh: "怎么样？人民公园好玩儿吗？", pinyin: "zěn me yàng？ rén mín gōng yuán hǎo wán ér ma？", vi: "Thế nào? Công viên Nhân Dân có vui không?" },
          { role: "卡玛拉", zh: "很好玩儿。那儿风景很美，空气非常好，人很多。", pinyin: "hěn hǎo wán ér。 nà ér fēng jǐng hěn měi， kōng qì fēi cháng hǎo， rén hěn duō。", vi: "Vui lắm. Phong cảnh ở đó rất đẹp, không khí rất tốt, đông người." },
          { role: "高小明", zh: "你拍照片了吗？", pinyin: "nǐ pāi zhào piān le ma？", vi: "Cậu có chụp ảnh không?" },
          { role: "卡玛拉", zh: "拍了，拍了很多照片。", pinyin: "pāi le， pāi le hěn duō zhào piān。", vi: "Có chụp, chụp rất nhiều ảnh." },
          { role: "高小明", zh: "可以给我看一下吗？", pinyin: "kě yǐ gěi wǒ kàn yī xià ma？", vi: "Cho tớ xem một chút được không?" },
          { role: "卡玛拉", zh: "可以，在我的电脑里，明天给你看。你周末做什么了？", pinyin: "kě yǐ， zài wǒ de diàn nǎo lǐ， míng tiān gěi nǐ kàn。 nǐ zhōu mò zuò shén me le？", vi: "Được, ở trong máy tính của tớ, mai tớ cho cậu xem. Cuối tuần cậu làm gì?" },
          { role: "高小明", zh: "我去书店了，买了几本英文书。", pinyin: "wǒ qù shū diàn le， mǎi le jǐ běn yīng wén shū。", vi: "Tớ đi hiệu sách, mua mấy quyển sách tiếng Anh." },
          { role: "卡玛拉", zh: "你真爱看书！", pinyin: "nǐ zhēn ài kàn shū！", vi: "Cậu thật là thích đọc sách!" },
        ],
      },

      // ===== Bài 7 =====
      {
        id: "b2-7-1",
        baiNumber: 7,
        baiTitleZh: "你是跟谁一起去的？",
        baiTitleVi: "Bạn đi cùng với ai?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "欧文", zh: "卡玛拉，听说你周末去公园玩儿了？", pinyin: "kǎ mǎ lā， tīng shuō nǐ zhōu mò qù gōng yuán wán ér le？", vi: "Kamala, nghe nói cuối tuần cậu đi công viên chơi à?" },
          { role: "卡玛拉", zh: "是啊，是谁告诉你的？", pinyin: "shì a， shì shuí gào sù nǐ de？", vi: "Đúng vậy, ai nói cho cậu biết vậy?" },
          { role: "欧文", zh: "我有你的微信，你忘了？", pinyin: "wǒ yǒu nǐ de wēi xìn， nǐ wàng le？", vi: "Tớ có WeChat của cậu mà, cậu quên rồi à?" },
          { role: "卡玛拉", zh: "哈哈，我忘了。", pinyin: "hā hā， wǒ wàng le。", vi: "Haha, tớ quên rồi." },
          { role: "欧文", zh: "你是跟谁一起去的？一个人？", pinyin: "nǐ shì gēn shuí yì qǐ qù de？ yí gè rén？", vi: "Cậu đi với ai vậy? Một mình à?" },
          { role: "卡玛拉", zh: "当然不是，一个人去公园没意思，我是跟中国朋友一起去的。", pinyin: "dāng rán bú shì， yí gè rén qù gōng yuán méi yì si， wǒ shì gēn zhōng guó péng yǒu yì qǐ qù de。", vi: "Tất nhiên là không, đi công viên một mình thì chán, tớ đi cùng bạn Trung Quốc." },
          { role: "欧文", zh: "你们是怎么去的？", pinyin: "nǐ men shì zěn me qù de？", vi: "Các cậu đi bằng phương tiện gì?" },
          { role: "卡玛拉", zh: "我们是骑自行车去的。", pinyin: "wǒ men shì qí zì xíng chē qù de。", vi: "Chúng tớ đi xe đạp." },
          { role: "欧文", zh: "骑自行车？骑了多长时间？很累吧？", pinyin: "qí zì xíng chē？ qí le duō zhǎng shí jiān？ hěn lèi ba？", vi: "Đi xe đạp? Đi mất bao lâu? Mệt lắm chứ?" },
          { role: "卡玛拉", zh: "不累，骑了一个小时左右。", pinyin: "bù lèi， qí le yí gè xiǎo shí zuǒ yòu。", vi: "Không mệt, đi khoảng một tiếng." },
          { role: "欧文", zh: "你们真行！", pinyin: "nǐ men zhēn xíng！", vi: "Các cậu giỏi thật!" },
        ],
      },
      {
        id: "b2-7-2",
        baiNumber: 7,
        baiTitleZh: "你是跟谁一起去的？",
        baiTitleVi: "Bạn đi cùng với ai?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "海伦，这张照片真好看！是你拍的吗？", pinyin: "hǎi lún， zhè zhāng zhào piān zhēn hǎo kàn！ shì nǐ pāi de ma？", vi: "Helen, tấm ảnh này đẹp quá! Cậu chụp à?" },
          { role: "海伦", zh: "不是我拍的，是我男朋友拍的。我也觉得这张照片很漂亮。", pinyin: "bú shì wǒ pāi de， shì wǒ nán péng yǒu pāi de。 wǒ yě jué de zhè zhāng zhào piān hěn piào liàng。", vi: "Không phải tớ chụp, là bạn trai tớ chụp. Tớ cũng thấy tấm ảnh này đẹp." },
          { role: "欧文", zh: "是什么时候拍的？最近吗？", pinyin: "shì shén me shí hòu pāi de？ zuì jìn ma？", vi: "Chụp khi nào vậy? Gần đây à?" },
          { role: "海伦", zh: "不是最近，是去年拍的。", pinyin: "bú shì zuì jìn， shì qù nián pāi de。", vi: "Không phải gần đây, chụp từ năm ngoái." },
          { role: "欧文", zh: "是在法国拍的吧？", pinyin: "shì zài fǎ guó pāi de ba？", vi: "Chụp ở Pháp đúng không?" },
          { role: "海伦", zh: "对，是去年我们在法国拍的。欧文，你是怎么知道的？", pinyin: "duì， shì qù nián wǒ men zài fǎ guó pāi de。 ōu wén， nǐ shì zěn me zhī dào de？", vi: "Đúng, năm ngoái bọn tớ chụp ở Pháp. Owen, sao cậu biết vậy?" },
          { role: "欧文", zh: "是你自己说的啊！", pinyin: "shì nǐ zì jǐ shuō de a！", vi: "Là chính cậu nói mà!" },
          { role: "海伦", zh: "我什么时候说的？", pinyin: "wǒ shén me shí hòu shuō de？", vi: "Tớ nói khi nào?" },
          { role: "欧文", zh: "哈哈，上次汉语课的时候说的。", pinyin: "hā hā， shàng cì hàn yǔ kè de shí hòu shuō de。", vi: "Haha, hôm trước trong giờ tiếng Hán cậu nói." },
          { role: "海伦", zh: "不好意思，我真忘了。", pinyin: "bù hǎo yì sī， wǒ zhēn wàng le。", vi: "Ngại quá, tớ quên thật." },
        ],
      },

      // ===== Bài 8 =====
      {
        id: "b2-8-1",
        baiNumber: 8,
        baiTitleZh: "你会做菜吗？",
        baiTitleVi: "Bạn biết nấu ăn không?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "田中", zh: "美京，今天你去哪儿吃晚饭？", pinyin: "měi jīng， jīn tiān nǐ qù nǎ ér chī wǎn fàn？", vi: "Mỹ Kinh, hôm nay cậu đi đâu ăn tối?" },
          { role: "美京", zh: "我想回家吃晚饭。", pinyin: "wǒ xiǎng huí jiā chī wǎn fàn。", vi: "Tớ muốn về nhà ăn tối." },
          { role: "田中", zh: "你会做菜吗？", pinyin: "nǐ huì zuò cài ma？", vi: "Cậu biết nấu ăn không?" },
          { role: "美京", zh: "会，我会做韩国菜和中国菜。你呢？", pinyin: "huì， wǒ huì zuò hán guó cài hé zhōng guó cài。 nǐ ne？", vi: "Có, tớ biết nấu món Hàn Quốc và món Trung Quốc. Còn cậu?" },
          { role: "田中", zh: "你真行！我不会做菜，我只会吃。", pinyin: "nǐ zhēn xíng！ wǒ bú huì zuò cài， wǒ zhǐ huì chī。", vi: "Cậu giỏi thật! Tớ không biết nấu ăn, tớ chỉ biết ăn thôi." },
          { role: "美京", zh: "那你晚上来我家吃吧，我今天做韩国菜。", pinyin: "nà nǐ wǎn shàng lái wǒ jiā chī ba， wǒ jīn tiān zuò hán guó cài。", vi: "Vậy tối nay đến nhà tớ ăn đi, hôm nay tớ làm món Hàn Quốc." },
          { role: "田中", zh: "太好了！对了，我会做水果沙拉。晚上我做一个吧！", pinyin: "tài hǎo le！ duì le， wǒ huì zuò shuǐ guǒ shā lā。 wǎn shàng wǒ zuò yí gè ba！", vi: "Tuyệt quá! À, tớ biết làm salad trái cây. Tối nay tớ làm một đĩa nhé!" },
          { role: "美京", zh: "田中，你会喝酒吗？", pinyin: "tián zhōng， nǐ huì hē jiǔ ma？", vi: "Tanaka, cậu biết uống rượu không?" },
          { role: "田中", zh: "会，喝一点儿。你呢？", pinyin: "huì， hē yì diǎn ér。 nǐ ne？", vi: "Biết, uống được một chút. Còn cậu?" },
          { role: "美京", zh: "我很喜欢喝红酒，我还会做红酒。上个月我做了两瓶红酒。", pinyin: "wǒ hěn xǐ huān hē hóng jiǔ， wǒ hái huì zuò hóng jiǔ。 shàng gè yuè wǒ zuò le liǎng píng hóng jiǔ。", vi: "Tớ rất thích uống rượu vang, tớ còn biết làm rượu vang nữa. Tháng trước tớ làm hai chai rượu vang." },
          { role: "田中", zh: "是吗？你真行！", pinyin: "shì ma？ nǐ zhēn xíng！", vi: "Thật à? Cậu giỏi thật!" },
          { role: "美京", zh: "哪里哪里！今天晚上尝一下吧！", pinyin: "nǎ lǐ nǎ lǐ！ jīn tiān wǎn shàng cháng yī xià ba！", vi: "Đâu có đâu! Tối nay nếm thử nhé!" },
          { role: "田中", zh: "好的！", pinyin: "hǎo de！", vi: "Được!" },
        ],
      },
      {
        id: "b2-8-2",
        baiNumber: 8,
        baiTitleZh: "你会做菜吗？",
        baiTitleVi: "Bạn biết nấu ăn không?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "卡玛拉", zh: "田中，听美京说你很喜欢吃韩国菜？", pinyin: "tián zhōng， tīng měi jīng shuō nǐ hěn xǐ huān chī hán guó cài？", vi: "Tanaka, nghe Mỹ Kinh nói cậu rất thích ăn món Hàn Quốc à?" },
          { role: "田中", zh: "对，昨天美京做了韩国菜，请我吃了。", pinyin: "duì， zuó tiān měi jīng zuò le hán guó cài， qǐng wǒ chī le。", vi: "Đúng vậy, hôm qua Mỹ Kinh làm món Hàn Quốc, mời tớ ăn." },
          { role: "卡玛拉", zh: "是吗？美京会做菜？", pinyin: "shì ma？ měi jīng huì zuò cài？", vi: "Thật à? Mỹ Kinh biết nấu ăn sao?" },
          { role: "田中", zh: "对，除了做菜以外，她还会做红酒。真的很好喝！", pinyin: "duì， chú le zuò cài yǐ wài， tā hái huì zuò hóng jiǔ。 zhēn de hěn hǎo hē！", vi: "Đúng vậy, ngoài nấu ăn ra, cô ấy còn biết làm rượu vang nữa. Thật sự rất ngon!" },
          { role: "卡玛拉", zh: "是吗？我觉得美京非常聪明，听说她会说很多外语，除了汉语以外，她还会说英语和日语。", pinyin: "shì ma？ wǒ jué de měi jīng fēi cháng cōng míng， tīng shuō tā huì shuō hěn duō wài yǔ， chú le hàn yǔ yǐ wài， tā hái huì shuō yīng yǔ hé rì yǔ。", vi: "Thật à? Tớ thấy Mỹ Kinh rất thông minh, nghe nói cô ấy biết nhiều ngoại ngữ, ngoài tiếng Hán ra, cô ấy còn biết tiếng Anh và tiếng Nhật." },
          { role: "田中", zh: "真的吗？卡玛拉，你也很聪明啊，除了英语以外，你还会说汉语和法语。", pinyin: "zhēn de ma？ kǎ mǎ lā， nǐ yě hěn cōng míng a， chú le yīng yǔ yǐ wài， nǐ hái huì shuō hàn yǔ hé fǎ yǔ。", vi: "Thật à? Kamala, cậu cũng rất thông minh đấy, ngoài tiếng Anh ra, cậu còn biết tiếng Hán và tiếng Pháp." },
          { role: "卡玛拉", zh: "哪里哪里！你的汉语非常好！", pinyin: "nǎ lǐ nǎ lǐ！ nǐ de hàn yǔ fēi cháng hǎo！", vi: "Đâu có đâu! Tiếng Hán của cậu rất giỏi!" },
        ],
      },

      // ===== Bài 9 =====
      {
        id: "b2-9-1",
        baiNumber: 9,
        baiTitleZh: "你见过熊猫吗？",
        baiTitleVi: "Bạn đã nhìn thấy gấu trúc bao giờ chưa?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "王文丽", zh: "欧文，这个周末你打算去哪儿？", pinyin: "ōu wén， zhè ge zhōu mò nǐ dǎ suàn qù nǎ ér？", vi: "Owen, cuối tuần này cậu định đi đâu?" },
          { role: "欧文", zh: "我觉得好玩儿的地方都已经去过了，文丽，你有什么建议？", pinyin: "wǒ jué de hǎo wán ér de dì fāng dōu yǐ jīng qù guò le， wén lì， nǐ yǒu shén me jiàn yì？", vi: "Tớ thấy mấy chỗ vui chơi đều đã đi rồi, Văn Lệ, cậu có gợi ý gì không?" },
          { role: "王文丽", zh: "我想一下……你见过熊猫吗？", pinyin: "wǒ xiǎng yī xià …… nǐ jiàn guò xióng māo ma？", vi: "Để tớ nghĩ xem... Cậu đã thấy gấu trúc bao giờ chưa?" },
          { role: "欧文", zh: "熊猫？我还没见过真的熊猫，可是我看过电影《功夫熊猫》。哪儿有熊猫？", pinyin: "xióng māo？ wǒ hái méi jiàn guò zhēn de xióng māo， kě shì wǒ kàn guò diàn yǐng《 gōng fu xióng māo》。 nǎ ér yǒu xióng māo？", vi: "Gấu trúc à? Tớ chưa thấy gấu trúc thật bao giờ, nhưng tớ đã xem phim 'Kung Fu Panda'. Ở đâu có gấu trúc?" },
          { role: "王文丽", zh: "郊区的动物园里就有。", pinyin: "jiāo qū de dòng wù yuán lǐ jiù yǒu。", vi: "Trong vườn thú ở ngoại ô có đấy." },
          { role: "欧文", zh: "真的？你去过那儿吗？", pinyin: "zhēn de？ nǐ qù guò nà ér ma？", vi: "Thật à? Cậu đã đi đó bao giờ chưa?" },
          { role: "王文丽", zh: "去过，那儿的熊猫可爱极了！你对动物感兴趣的话，可以去动物园。", pinyin: "qù guò， nà ér de xióng māo kě ài jí le！ nǐ duì dòng wù gǎn xìng qù de huà， kě yǐ qù dòng wù yuán。", vi: "Có rồi, gấu trúc ở đó đáng yêu cực kỳ! Nếu cậu thích động vật thì có thể đến vườn thú." },
          { role: "欧文", zh: "当然感兴趣，那我去动物园吧。你可以跟我一起去吗？一个人去没意思。", pinyin: "dāng rán gǎn xìng qù， nà wǒ qù dòng wù yuán ba。 nǐ kě yǐ gēn wǒ yì qǐ qù ma？ yí gè rén qù méi yì si。", vi: "Tất nhiên là thích, vậy tớ đi vườn thú đi. Cậu có thể đi cùng tớ không? Đi một mình thì chán." },
          { role: "王文丽", zh: "不好意思，我周末没空儿，我要……", pinyin: "bù hǎo yì sī， wǒ zhōu mò méi kòng ér， wǒ yào ……", vi: "Ngại quá, cuối tuần tớ không rảnh, tớ phải..." },
          { role: "欧文", zh: "我知道，你要跟男朋友约会吧？", pinyin: "wǒ zhī dào， nǐ yào gēn nán péng yǒu yuē huì ba？", vi: "Tớ biết rồi, cậu phải hẹn hò với bạn trai đúng không?" },
        ],
      },
      {
        id: "b2-9-2",
        baiNumber: 9,
        baiTitleZh: "你见过熊猫吗？",
        baiTitleVi: "Bạn đã nhìn thấy gấu trúc bao giờ chưa?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "海伦，你去过郊区的动物园吗？", pinyin: "hǎi lún， nǐ qù guò jiāo qū de dòng wù yuán ma？", vi: "Helen, cậu đã đi vườn thú ở ngoại ô bao giờ chưa?" },
          { role: "海伦", zh: "没去过，我对动物不太感兴趣。", pinyin: "méi qù guò， wǒ duì dòng wù bù tài gǎn xìng qù。", vi: "Chưa đi, tớ không hứng thú với động vật lắm." },
          { role: "欧文", zh: "真遗憾！我周末想去动物园，打算请你一起去。", pinyin: "zhēn yí hàn！ wǒ zhōu mò xiǎng qù dòng wù yuán， dǎ suàn qǐng nǐ yì qǐ qù。", vi: "Tiếc quá! Cuối tuần tớ muốn đi vườn thú, định rủ cậu đi cùng." },
          { role: "海伦", zh: "我对博物馆很感兴趣，周末想去市中心的博物馆。欧文，你去过吗？", pinyin: "wǒ duì bó wù guǎn hěn gǎn xìng qù， zhōu mò xiǎng qù shì zhōng xīn de bó wù guǎn。 ōu wén， nǐ qù guò ma？", vi: "Tớ rất thích bảo tàng, cuối tuần tớ muốn đi bảo tàng ở trung tâm thành phố. Owen, cậu đã đi đó chưa?" },
          { role: "欧文", zh: "当然去过，我很喜欢参观博物馆。", pinyin: "dāng rán qù guò， wǒ hěn xǐ huān cān guān bó wù guǎn。", vi: "Tất nhiên đi rồi, tớ rất thích đi tham quan bảo tàng." },
          { role: "海伦", zh: "那这个星期六跟我再去一次，好吗？", pinyin: "nà zhè ge xīng qī liù gēn wǒ zài qù yī cì， hǎo ma？", vi: "Vậy thứ Bảy tuần này đi cùng tớ thêm một lần nữa nhé, được không?" },
          { role: "欧文", zh: "好吧。你怎么感谢我？", pinyin: "hǎo ba。 nǐ zěn me gǎn xiè wǒ？", vi: "Được thôi. Cậu cảm ơn tớ thế nào đây?" },
          { role: "海伦", zh: "星期六晚上我请你吃烤鸭吧，你吃没吃过烤鸭？", pinyin: "xīng qī liù wǎn shàng wǒ qǐng nǐ chī kǎo yā ba， nǐ chī méi chī guò kǎo yā？", vi: "Tối thứ Bảy tớ mời cậu ăn vịt quay nhé, cậu đã ăn vịt quay bao giờ chưa?" },
          { role: "欧文", zh: "没吃过，听说很好吃。", pinyin: "méi chī guò， tīng shuō hěn hǎo chī。", vi: "Chưa ăn, nghe nói rất ngon." },
          { role: "海伦", zh: "当然，味道好极了。", pinyin: "dāng rán， wèi dào hǎo jí le。", vi: "Tất nhiên, hương vị tuyệt vời." },
          { role: "欧文", zh: "我的肚子已经饿了，现在就去吃吧！", pinyin: "wǒ de dǔ zi yǐ jīng è le， xiàn zài jiù qù chī ba！", vi: "Bụng tớ đã đói rồi, đi ăn ngay bây giờ đi!" },
        ],
      },

      // ===== Bài 10 =====
      {
        id: "b2-10-1",
        baiNumber: 10,
        baiTitleZh: "给您添麻烦了！",
        baiTitleVi: "Làm phiền cô rồi!",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "黄老师", zh: "谁啊？", pinyin: "shuí a？", vi: "Ai vậy?" },
          { role: "田中", zh: "是我，田中。", pinyin: "shì wǒ， tián zhōng。", vi: "Là em, Tanaka." },
          { role: "黄老师", zh: "田中，你好！欢迎！请进！", pinyin: "tián zhōng， nǐ hǎo！ huān yíng！ qǐng jìn！", vi: "Tanaka, chào em! Hoan nghênh! Mời vào!" },
          { role: "田中", zh: "黄老师，您家真大，真漂亮！", pinyin: "huáng lǎo shī， nín jiā zhēn dà， zhēn piào liàng！", vi: "Cô Hoàng, nhà cô thật rộng, thật đẹp!" },
          { role: "黄老师", zh: "谢谢！请坐！", pinyin: "xiè xiè！ qǐng zuò！", vi: "Cảm ơn em! Mời ngồi!" },
          { role: "田中", zh: "黄老师，今天您一个人在家？", pinyin: "huáng lǎo shī， jīn tiān nín yí gè rén zài jiā？", vi: "Cô Hoàng, hôm nay cô ở nhà một mình ạ?" },
          { role: "黄老师", zh: "对，我爱人和孩子都出去了，爱人有工作，孩子中午有约会。", pinyin: "duì， wǒ ài rén hé hái zi dōu chū qù le， ài rén yǒu gōng zuò， hái zi zhōng wǔ yǒu yuē huì。", vi: "Đúng vậy, chồng cô và các con đều ra ngoài rồi, chồng cô đi làm, con cô buổi trưa có cuộc hẹn." },
          { role: "田中", zh: "您有几个孩子？", pinyin: "nín yǒu jǐ gè hái zi？", vi: "Cô có mấy người con ạ?" },
          { role: "黄老师", zh: "两个，一个女儿，一个儿子，都工作了。你喝茶还是咖啡？", pinyin: "liǎng gè， yí gè nǚ ér， yí gè ér zi， dōu gōng zuò le。 nǐ hē chá hái shì kā fēi？", vi: "Hai đứa, một con gái, một con trai, đều đi làm rồi. Em uống trà hay cà phê?" },
          { role: "田中", zh: "给您添麻烦了。我喝咖啡吧。", pinyin: "gěi nín tiān má fán le。 wǒ hē kā fēi ba。", vi: "Làm phiền cô rồi. Em uống cà phê ạ." },
          { role: "黄老师", zh: "别客气，不麻烦。", pinyin: "bié kè qì， bù má fán。", vi: "Đừng khách sáo, không phiền đâu." },
        ],
      },
      {
        id: "b2-10-2",
        baiNumber: 10,
        baiTitleZh: "给您添麻烦了！",
        baiTitleVi: "Làm phiền cô rồi!",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "黄老师", zh: "肚子饿了没有？我们吃饭吧！", pinyin: "dù zi è le méi yǒu？ wǒ men chī fàn ba！", vi: "Đói bụng chưa? Chúng ta ăn cơm thôi!" },
          { role: "田中", zh: "做了这么多菜，您辛苦了！", pinyin: "zuò le zhè me duō cài， nín xīn kǔ le！", vi: "Cô nấu nhiều món vậy, cô vất vả quá!" },
          { role: "黄老师", zh: "不多，不多！尝一下好吃不好吃？", pinyin: "bù duō， bù duō！ cháng yī xià hǎo chī bù hǎo chī？", vi: "Không nhiều, không nhiều đâu! Em nếm thử xem ngon không?" },
          { role: "田中", zh: "好的。这是麻婆豆腐吧，好吃极了！", pinyin: "hǎo de。 zhè shì má pó dòu fǔ ba， hǎo chī jí le！", vi: "Vâng ạ. Đây là đậu phụ Mapo phải không, ngon cực kỳ!" },
          { role: "黄老师", zh: "很辣吧？田中，你怕不怕辣？", pinyin: "hěn là ba？ tián zhōng， nǐ pà bù pà là？", vi: "Cay lắm phải không? Tanaka, em có sợ cay không?" },
          { role: "田中", zh: "不怕！这个菜叫什么？味道又酸又甜。", pinyin: "bù pà！ zhè ge cài jiào shén me？ wèi dào yòu suān yòu tián。", vi: "Không sợ! Món này tên là gì? Vị vừa chua vừa ngọt." },
          { role: "黄老师", zh: "这是糖醋鱼。", pinyin: "zhè shì táng cù yú。", vi: "Đây là cá sốt chua ngọt." },
          { role: "田中", zh: "太好吃了。黄老师，您真会做菜！", pinyin: "tài hǎo chī le。 huáng lǎo shī， nín zhēn huì zuò cài！", vi: "Ngon quá. Cô Hoàng, cô nấu ăn giỏi thật!" },
          { role: "黄老师", zh: "哪里哪里！喜欢的话，多吃一点儿！", pinyin: "nǎ lǐ nǎ lǐ！ xǐ huān de huà， duō chī yì diǎn ér！", vi: "Đâu có đâu! Thích thì ăn thêm một chút!" },
          { role: "田中", zh: "谢谢。", pinyin: "xiè xiè。", vi: "Cảm ơn cô." },
          { role: "田中", zh: "今天给您添麻烦了！", pinyin: "jīn tiān gěi nín tiān má fán le！", vi: "Hôm nay làm phiền cô rồi!" },
          { role: "黄老师", zh: "哪里，欢迎再来。", pinyin: "nǎ lǐ， huān yíng zài lái。", vi: "Đâu có, lần sau lại đến nhé." },
        ],
      },
    ],
  });
})();
