// Dữ liệu hội thoại Msutong Sơ cấp B4 (Bài 1-10)
// Trích từ hoi-thoai-b4-bai-1-10.md — 20 bài học (mỗi "Bài khóa" = 1 lesson).

(function () {
  window.dialogueBooks = window.dialogueBooks || [];
  window.dialogueBooks.push({
    id: "msutong-b4",
    shortName: "B4",
    name: "Msutong Sơ cấp B4",
    lessons: [
      // ===== Bài 1 =====
      {
        id: "b4-1-1",
        baiNumber: 1,
        baiTitleZh: "国庆节放七天假",
        baiTitleVi: "Quốc khánh được nghỉ bảy ngày",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "田中，快到10月1号了，你知道国庆节放多长时间的假吗？", pinyin: "tián zhōng， kuài dào 10 yuè 1 hào le， nǐ zhī dào guó qìng jié fàng duō zhǎng shí jiān de jiǎ ma？", vi: "Tanaka, sắp đến mùng 1 tháng 10 rồi, cậu có biết Quốc khánh được nghỉ bao lâu không?" },
          { role: "田中", zh: "国庆节放七天假，休息一个星期。", pinyin: "guó qìng jié fàng qī tiān jiǎ， xiū xī yí gè xīng qī。", vi: "Quốc khánh được nghỉ bảy ngày, nghỉ một tuần." },
          { role: "海伦", zh: "中国的节日都放长假吗？", pinyin: "zhōng guó de jié rì dōu fàng cháng jià ma？", vi: "Các ngày lễ ở Trung Quốc đều được nghỉ dài à?" },
          { role: "田中", zh: "不，有的节日只放一天假，比如中秋节。", pinyin: "bù， yǒu de jié rì zhǐ fàng yī tiān jiǎ， bǐ rú zhōng qiū jié。", vi: "Không, có ngày lễ chỉ nghỉ một ngày, ví dụ Tết Trung thu." },
          { role: "海伦", zh: "听说国庆节是从星期四开始放假，我们下个星期只上三天课。", pinyin: "tīng shuō guó qìng jié shì cóng xīng qī sì kāi shǐ fàng jià， wǒ men xià gè xīng qī zhǐ shàng sān tiān kè。", vi: "Nghe nói Quốc khánh bắt đầu nghỉ từ thứ Năm, tuần sau chúng ta chỉ học ba ngày." },
          { role: "田中", zh: "对，我已经请了三天的假，下个星期就不去上课了，回日本去。", pinyin: "duì， wǒ yǐ jīng qǐng le sān tiān de jiǎ， xià gè xīng qī jiù bù qù shàng kè le， huí rì běn qù。", vi: "Đúng, tớ đã xin nghỉ ba ngày, tuần sau sẽ không đi học, về Nhật Bản." },
          { role: "海伦", zh: "你回去看你的爱人和孩子吗？", pinyin: "nǐ huí qù kàn nǐ de ài rén hé hái zi ma？", vi: "Cậu về thăm vợ và con à?" },
          { role: "田中", zh: "不是。下个星期一我的好朋友结婚，我这个星期六回去。海伦，你国庆节干什么？", pinyin: "bú shì。 xià gè xīng qī yī wǒ de hǎo péng yǒu jié hūn， wǒ zhè ge xīng qī liù huí qù。 hǎi lún， nǐ guó qìng jié gàn shén me？", vi: "Không phải. Thứ Hai tuần sau bạn thân tớ kết hôn, tớ thứ Bảy này về. Helen, Quốc khánh cậu làm gì?" },
          { role: "海伦", zh: "我想在宿舍舒舒服服地睡几天，太累了。", pinyin: "wǒ xiǎng zài sù shè shū shū fú fú dì shuì jǐ tiān， tài lèi le。", vi: "Tớ muốn ở ký túc xá ngủ thoải mái mấy ngày, mệt quá rồi." },
          { role: "田中", zh: "是不是想睡一个星期觉？", pinyin: "shì bú shì xiǎng shuì yí gè xīng qī jué？", vi: "Có phải muốn ngủ cả một tuần không?" },
        ],
      },
      {
        id: "b4-1-2",
        baiNumber: 1,
        baiTitleZh: "国庆节放七天假",
        baiTitleVi: "Quốc khánh được nghỉ bảy ngày",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "放了四天假了。欧文，你去哪儿玩儿了？", pinyin: "fàng le sì tiān jiǎ le。 ōu wén， nǐ qù nǎ ér wán ér le？", vi: "Đã nghỉ bốn ngày rồi. Owen, cậu đi đâu chơi vậy?" },
          { role: "欧文", zh: "小明很热情，他开了辆车，带我们去旅行了。", pinyin: "xiǎo míng hěn rè qíng， tā kāi le liàng chē， dài wǒ men qù lǚ xíng le。", vi: "Tiểu Minh rất nhiệt tình, cậu ấy lái xe đưa chúng tớ đi du lịch." },
          { role: "海伦", zh: "高速公路很堵吧？", pinyin: "gāo sù gōng lù hěn dǔ ba？", vi: "Đường cao tốc tắc lắm phải không?" },
          { role: "欧文", zh: "去的时候只堵了一会儿，回来的时候堵了五个小时左右。", pinyin: "qù de shí hòu zhǐ dǔ le yī huì er， huí lái de shí hòu dǔ le wǔ gè xiǎo shí zuǒ yòu。", vi: "Lúc đi chỉ tắc một lát, lúc về tắc khoảng năm tiếng." },
          { role: "海伦", zh: "国庆节高速公路免费，当然堵了。", pinyin: "guó qìng jié gāo sù gōng lù miǎn fèi， dāng rán dǔ le。", vi: "Quốc khánh đường cao tốc miễn phí, đương nhiên là tắc." },
          { role: "欧文", zh: "如果坐飞机就不堵了。海伦，你出去玩儿了吗？", pinyin: "rú guǒ zuò fēi jī jiù bù dǔ le。 hǎi lún， nǐ chū qù wán ér le ma？", vi: "Nếu đi máy bay thì không tắc. Helen, cậu đi chơi không?" },
          { role: "海伦", zh: "我要参加HSK考试，每天都在宿舍学习。", pinyin: "wǒ yào cān jiā HSK kǎo shì， měi tiān dōu zài sù shè xué xí。", vi: "Tớ phải tham gia kỳ thi HSK, ngày nào cũng học ở ký túc xá." },
          { role: "欧文", zh: "我明天也要在家里好好儿地学习。", pinyin: "wǒ míng tiān yě yào zài jiā lǐ hǎo hǎo ér dì xué xí。", vi: "Mai tớ cũng phải ở nhà học hành cho tử tế." },
          { role: "海伦", zh: "旅行也是很好的学习。", pinyin: "lǚ xíng yě shì hěn hǎo de xué xí。", vi: "Du lịch cũng là cách học rất tốt." },
        ],
      },

      // ===== Bài 2 =====
      {
        id: "b4-2-1",
        baiNumber: 2,
        baiTitleZh: "找到满意的工作不容易啊",
        baiTitleVi: "Tìm được công việc như mong muốn thật không dễ",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "小明，中国的大学生毕业以前需要去实习吗？", pinyin: "xiǎo míng， zhōng guó de dà xué shēng bì yè yǐ qián xū yào qù shí xí ma？", vi: "Tiểu Minh, sinh viên đại học Trung Quốc trước khi tốt nghiệp có cần đi thực tập không?" },
          { role: "高小明", zh: "是的，我的朋友刚刚找到了一家公司去实习，我也想去。", pinyin: "shì de， wǒ de péng yǒu gāng gāng zhǎo dào le yī jiā gōng sī qù shí xí， wǒ yě xiǎng qù。", vi: "Có, bạn tớ vừa tìm được một công ty để thực tập, tớ cũng muốn đi." },
          { role: "海伦", zh: "什么公司？", pinyin: "shén me gōng sī？", vi: "Công ty gì?" },
          { role: "高小明", zh: "是家美国公司，他们让我先用英语写好简历。我的英语不太好，你帮我看一下写对了没有？", pinyin: "shì jiā měi guó gōng sī， tā men ràng wǒ xiān yòng yīng yǔ xiě hǎo jiǎn lì。 wǒ de yīng yǔ bù tài hǎo， nǐ bāng wǒ kàn yī xià xiě duì le méi yǒu？", vi: "Là một công ty Mỹ, họ bảo tớ viết CV bằng tiếng Anh trước. Tiếng Anh tớ không giỏi, cậu xem giúp tớ viết đúng chưa nhé?" },
          { role: "海伦", zh: "好的，我看看。你还需要面试吗？", pinyin: "hǎo de， wǒ kàn kàn。 nǐ hái xū yào miàn shì ma？", vi: "Được, để tớ xem. Cậu còn phải phỏng vấn không?" },
          { role: "高小明", zh: "要，有些公司还要面试很多次。", pinyin: "yào， yǒu xiē gōng sī hái yào miàn shì hěn duō cì。", vi: "Phải, có công ty còn phỏng vấn nhiều lần." },
          { role: "海伦", zh: "这家公司需要每天去吗？", pinyin: "zhè jiā gōng sī xū yào měi tiān qù ma？", vi: "Công ty này có cần đi mỗi ngày không?" },
          { role: "高小明", zh: "每个星期去四天。我星期一和星期四上午有课，打算上完课去。", pinyin: "měi gè xīng qī qù sì tiān。 wǒ xīng qī yī hé xīng qī sì shàng wǔ yǒu kè， dǎ suàn shàng wán kè qù。", vi: "Mỗi tuần đi bốn ngày. Sáng thứ Hai và thứ Năm tớ có tiết, định học xong tiết rồi đi." },
          { role: "海伦", zh: "公司会同意吗？", pinyin: "gōng sī huì tóng yì ma？", vi: "Công ty có đồng ý không?" },
          { role: "高小明", zh: "没问题，我的朋友也是上完课以后去的。", pinyin: "méi wèn tí， wǒ de péng yǒu yě shì shàng wán kè yǐ hòu qù de。", vi: "Không vấn đề gì, bạn tớ cũng học xong tiết rồi mới đi." },
          { role: "海伦", zh: "如果能通过面试，你以后就要忙死了。", pinyin: "rú guǒ néng tōng guò miàn shì， nǐ yǐ hòu jiù yào máng sǐ le。", vi: "Nếu vượt qua phỏng vấn, sau này cậu sẽ bận chết." },
        ],
      },
      {
        id: "b4-2-2",
        baiNumber: 2,
        baiTitleZh: "找到满意的工作不容易啊",
        baiTitleVi: "Tìm được công việc như mong muốn thật không dễ",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "卡玛拉", zh: "小明，你快毕业了，工作找到了吗？", pinyin: "xiǎo míng， nǐ kuài bì yè le， gōng zuò zhǎo dào le ma？", vi: "Tiểu Minh, cậu sắp tốt nghiệp rồi, đã tìm được việc chưa?" },
          { role: "高小明", zh: "还没有。最近忙着找工作，我已经参加了很多场面试。", pinyin: "hái méi yǒu。 zuì jìn máng zhe zhǎo gōng zuò， wǒ yǐ jīng cān jiā le hěn duō chǎng miàn shì。", vi: "Chưa. Gần đây bận đi tìm việc, tớ đã tham gia rất nhiều buổi phỏng vấn." },
          { role: "卡玛拉", zh: "找到满意的工作不容易啊。", pinyin: "zhǎo dào mǎn yì de gōng zuò bù róng yì a。", vi: "Tìm được công việc như mong muốn thật không dễ." },
          { role: "高小明", zh: "是啊，竞争很厉害。上个星期一家公司给我发了电子邮件，通知我明天去面试。希望这次能通过。", pinyin: "shì a， jìng zhēng hěn lì hài。 shàng gè xīng qī yī jiā gōng sī gěi wǒ fā le diàn zi yóu jiàn， tōng zhī wǒ míng tiān qù miàn shì。 xī wàng zhè cì néng tōng guò。", vi: "Đúng vậy, cạnh tranh khốc liệt lắm. Tuần trước có một công ty gửi email cho tớ, báo mai đi phỏng vấn. Hy vọng lần này có thể vượt qua." },
          { role: "卡玛拉", zh: "明天的面试你准备好了吗？", pinyin: "míng tiān de miàn shì nǐ zhǔn bèi hǎo le ma？", vi: "Buổi phỏng vấn ngày mai cậu chuẩn bị xong chưa?" },
          { role: "高小明", zh: "早就准备好了。", pinyin: "zǎo jiù zhǔn bèi hǎo le。", vi: "Từ lâu đã chuẩn bị xong rồi." },
          { role: "卡玛拉", zh: "是用汉语还是用英语面试？", pinyin: "shì yòng hàn yǔ hái shì yòng yīng yǔ miàn shì？", vi: "Phỏng vấn bằng tiếng Hán hay tiếng Anh?" },
          { role: "高小明", zh: "那是一家美国公司，得用英语面试。", pinyin: "nà shì yī jiā měi guó gōng sī， dé yòng yīng yǔ miàn shì。", vi: "Đó là công ty Mỹ, phải phỏng vấn bằng tiếng Anh." },
          { role: "卡玛拉", zh: "祝你好运（气）！", pinyin: "zhù nǐ hǎo yùn（ qì）！", vi: "Chúc cậu may mắn!" },
          { role: "高小明", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        ],
      },

      // ===== Bài 3 =====
      {
        id: "b4-3-1",
        baiNumber: 3,
        baiTitleZh: "我要给他寄过去",
        baiTitleVi: "Tôi sẽ gửi cho cậu ấy",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "小明，附近有邮局或者快递公司吗？", pinyin: "xiǎo míng， fù jìn yǒu yóu jú huò zhě kuài dì gōng sī ma？", vi: "Tiểu Minh, gần đây có bưu điện hoặc công ty chuyển phát nhanh không?" },
          { role: "高小明", zh: "有。你要寄东西吗？", pinyin: "yǒu。 nǐ yào jì dōng xī ma？", vi: "Có. Cậu muốn gửi đồ à?" },
          { role: "海伦", zh: "我西安的朋友叫我买了一些东西，我要给他寄过去。", pinyin: "wǒ xī ān de péng yǒu jiào wǒ mǎi le yī xiē dōng xī， wǒ yào gěi tā jì guò qù。", vi: "Bạn ở Tây An nhờ tớ mua một số thứ, tớ phải gửi sang cho cậu ấy." },
          { role: "高小明", zh: "附近有很多快递公司。你可以打电话叫快递员过来取，也可以送过去。", pinyin: "fù jìn yǒu hěn duō kuài dì gōng sī。 nǐ kě yǐ dǎ diàn huà jiào kuài dì yuán guò lái qǔ， yě kě yǐ sòng guò qù。", vi: "Gần đây có nhiều công ty chuyển phát nhanh. Cậu có thể gọi điện kêu nhân viên đến lấy, cũng có thể mang qua." },
          { role: "海伦", zh: "送过去远不远？", pinyin: "sòng guò qù yuǎn bù yuǎn？", vi: "Mang qua có xa không?" },
          { role: "高小明", zh: "有一家快递公司离这里很近，走过去一会儿就到。", pinyin: "yǒu yī jiā kuài dì gōng sī lí zhè lǐ hěn jìn， zǒu guò qù yī huì er jiù dào。", vi: "Có một công ty chuyển phát rất gần đây, đi bộ qua một lát là đến." },
          { role: "海伦", zh: "送过去以前，要不要包好？", pinyin: "sòng guò qù yǐ qián， yào bù yào bāo hǎo？", vi: "Trước khi mang đi, có cần đóng gói không?" },
          { role: "高小明", zh: "不用包好，到了那里需要拿出来检查。你寄的东西多吗？", pinyin: "bù yòng bāo hǎo， dào le nà lǐ xū yào ná chū lái jiǎn chá。 nǐ jì de dōng xī duō ma？", vi: "Không cần đóng gói trước, đến đó cần lấy ra để kiểm tra. Đồ cậu gửi có nhiều không?" },
          { role: "海伦", zh: "比较多，大概有七公斤。", pinyin: "bǐ jiào duō， dà gài yǒu qī gōng jīn。", vi: "Khá nhiều, khoảng bảy ký." },
          { role: "高小明", zh: "很重啊，给快递公司打电话，让他们过来取吧。我有他们的电话号码。", pinyin: "hěn zhòng a， gěi kuài dì gōng sī dǎ diàn huà， ràng tā men guò lái qǔ ba。 wǒ yǒu tā men de diàn huà hào mǎ。", vi: "Nặng đấy, gọi điện cho công ty chuyển phát, để họ đến lấy đi. Tớ có số điện thoại của họ." },
          { role: "海伦", zh: "好的，我马上就打。", pinyin: "hǎo de， wǒ mǎ shàng jiù dǎ。", vi: "Được, tớ gọi ngay." },
        ],
      },
      {
        id: "b4-3-2",
        baiNumber: 3,
        baiTitleZh: "我要给他寄过去",
        baiTitleVi: "Tôi sẽ gửi cho cậu ấy",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "快递员", zh: "你好，请问是黄女士吗？我是送快递的，有你的快递，你现在在家吗？", pinyin: "nǐ hǎo， qǐng wèn shì huáng nǚ shì ma？ wǒ shì sòng kuài dì de， yǒu nǐ de kuài dì， nǐ xiàn zài zài jiā ma？", vi: "Xin chào, xin hỏi có phải cô Hoàng không? Tôi là nhân viên chuyển phát, có bưu kiện của cô, cô đang ở nhà chứ?" },
          { role: "黄女士", zh: "在。我家在20楼，请送上来吧。", pinyin: "zài。 wǒ jiā zài 20 lóu， qǐng sòng shàng lái ba。", vi: "Có. Nhà tôi ở tầng 20, mang lên giúp tôi đi." },
          { role: "快递员", zh: "对不起，电梯坏了，还在修，不能用。", pinyin: "duì bù qǐ， diàn tī huài le， hái zài xiū， bù néng yòng。", vi: "Xin lỗi, thang máy hỏng, đang sửa, không dùng được." },
          { role: "黄女士", zh: "是什么快递？", pinyin: "shì shén me kuài dì？", vi: "Là bưu kiện gì vậy?" },
          { role: "快递员", zh: "是一封信，一家公司寄来的。", pinyin: "shì yī fēng xìn， yī jiā gōng sī jì lái de。", vi: "Là một bức thư, do một công ty gửi đến." },
          { role: "黄女士", zh: "不用送上来了，电梯旁边有我家的信箱，你找一下2003信箱，放进去吧。", pinyin: "bù yòng sòng shàng lái le， diàn tī páng biān yǒu wǒ jiā de xìn xiāng， nǐ zhǎo yī xià 2003 xìn xiāng， fàng jìn qù ba。", vi: "Không cần mang lên nữa, bên cạnh thang máy có hòm thư nhà tôi, anh tìm hòm thư 2003, bỏ vào đó nhé." },
          { role: "快递员", zh: "好的，我看到了。啊，电梯修好了，我还是送上去吧。", pinyin: "hǎo de， wǒ kàn dào le。 a， diàn tī xiū hǎo le， wǒ hái shì sòng shàng qù ba。", vi: "Vâng, tôi thấy rồi. À, thang máy sửa xong rồi, tôi mang lên luôn vậy." },
          { role: "黄女士", zh: "谢谢！对了，我的信箱里是不是还有报纸？也请你带上来吧。", pinyin: "xiè xiè！ duì le， wǒ de xìn xiāng lǐ shì bú shì hái yǒu bào zhǐ？ yě qǐng nǐ dài shàng lái ba。", vi: "Cảm ơn! Mà này, trong hòm thư của tôi có báo nữa phải không? Anh mang lên luôn giúp tôi nhé." },
          { role: "快递员", zh: "好的。里面还有一本杂志，都拿出来吗？", pinyin: "hǎo de。 lǐ miàn hái yǒu yī běn zá zhì， dōu ná chū lái ma？", vi: "Được. Bên trong còn có một cuốn tạp chí nữa, lấy hết ra ạ?" },
          { role: "黄女士", zh: "请你都带上来，给你添麻烦了！", pinyin: "qǐng nǐ dōu dài shàng lái， gěi nǐ tiān má fán le！", vi: "Anh mang hết lên giúp tôi, làm phiền anh quá!" },
          { role: "快递员", zh: "没关系。", pinyin: "méi guān xì。", vi: "Không sao đâu." },
        ],
      },

      // ===== Bài 4 =====
      {
        id: "b4-4-1",
        baiNumber: 4,
        baiTitleZh: "您是不是住到12号？",
        baiTitleVi: "Bạn có ở đến ngày 12 không?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "服务员", zh: "您好，欢迎入住。请问，您预订房间了吗？", pinyin: "nín hǎo， huān yíng rù zhù。 qǐng wèn， nín yù dìng fáng jiān le ma？", vi: "Xin chào, hoan nghênh quý khách. Xin hỏi, ngài đã đặt phòng chưa?" },
          { role: "欧文", zh: "我在网上预订了一个带早餐的单人间，我叫欧文。", pinyin: "wǒ zài wǎng shàng yù dìng le yí gè dài zǎo cān de dān rén jiān， wǒ jiào ōu wén。", vi: "Tôi đã đặt một phòng đơn kèm bữa sáng trên mạng, tôi tên Owen." },
          { role: "服务员", zh: "欧文先生，您是不是住到12号？", pinyin: "ōu wén xiān shēng， nín shì bú shì zhù dào 12 hào？", vi: "Anh Owen, anh có ở đến ngày 12 không?" },
          { role: "欧文", zh: "是的，一共住三个晚上。", pinyin: "shì de， yī gòng zhù sān gè wǎn shàng。", vi: "Đúng vậy, tổng cộng ở ba đêm." },
          { role: "服务员", zh: "不好意思，您需要付五百块钱押金。", pinyin: "bù hǎo yì sī， nín xū yào fù wǔ bǎi kuài qián yā jīn。", vi: "Xin lỗi, anh cần đặt cọc năm trăm tệ." },
          { role: "欧文", zh: "行，给您五百块钱。", pinyin: "xíng， gěi nín wǔ bǎi kuài qián。", vi: "Được, đây ạ, năm trăm tệ." },
          { role: "服务员", zh: "这是押金收据，请收好，退房的时候请拿过来。", pinyin: "zhè shì yā jīn shōu jù， qǐng shōu hǎo， tuì fáng de shí hòu qǐng ná guò lái。", vi: "Đây là biên lai đặt cọc, xin giữ kỹ, khi trả phòng mang đến nhé." },
          { role: "欧文", zh: "宾馆可以免费上网吧？Wifi密码请写给我吧。", pinyin: "bīn guǎn kě yǐ miǎn fèi shàng wǎng ba？Wifi mì mǎ qǐng xiě gěi wǒ ba。", vi: "Khách sạn có wifi miễn phí phải không? Xin viết mật khẩu wifi cho tôi." },
          { role: "服务员", zh: "密码放在房间的桌子上了。", pinyin: "mì mǎ fàng zài fáng jiān de zhuō zi shàng le。", vi: "Mật khẩu để trên bàn trong phòng rồi ạ." },
          { role: "欧文", zh: "吃早饭需要早餐券吗？", pinyin: "chī zǎo fàn xū yào zǎo cān quàn ma？", vi: "Ăn sáng có cần phiếu ăn sáng không?" },
          { role: "服务员", zh: "需要。餐厅会开到早上9点半。这是您的门卡和早餐券。您的房间在9楼，坐左边的电梯上去。", pinyin: "xū yào。 cān tīng huì kāi dào zǎo shàng 9 diǎn bàn。 zhè shì nín de mén kǎ hé zǎo cān quàn。 nín de fáng jiān zài 9 lóu， zuò zuǒ biān de diàn tī shàng qù。", vi: "Có. Nhà hàng mở đến 9 giờ 30 sáng. Đây là thẻ phòng và phiếu ăn sáng của anh. Phòng anh ở tầng 9, đi thang máy bên trái lên." },
          { role: "欧文", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        ],
      },
      {
        id: "b4-4-2",
        baiNumber: 4,
        baiTitleZh: "您是不是住到12号？",
        baiTitleVi: "Bạn có ở đến ngày 12 không?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "您好，我是住在905房间的欧文。请问几点以前退房？", pinyin: "nín hǎo， wǒ shì zhù zài 905 fáng jiān de ōu wén。 qǐng wèn jǐ diǎn yǐ qián tuì fáng？", vi: "Xin chào, tôi là Owen ở phòng 905. Xin hỏi mấy giờ phải trả phòng?" },
          { role: "服务员", zh: "按照规定，应该12点以前退房。", pinyin: "àn zhào guī dìng， yīng gāi 12 diǎn yǐ qián tuì fáng。", vi: "Theo quy định, phải trả phòng trước 12 giờ." },
          { role: "欧文", zh: "可以延长一会儿吗？", pinyin: "kě yǐ yán cháng yī huì er ma？", vi: "Có thể gia hạn một chút không?" },
          { role: "服务员", zh: "可以延长到1点，1点以后就不行了。", pinyin: "kě yǐ yán cháng dào 1 diǎn，1 diǎn yǐ hòu jiù bù xíng le。", vi: "Có thể gia hạn đến 1 giờ, sau 1 giờ thì không được nữa." },
          { role: "服务员", zh: "先生，您的房间号码是多少？", pinyin: "xiān shēng， nín de fáng jiān hào mǎ shì duō shǎo？", vi: "Thưa anh, số phòng của anh là bao nhiêu?" },
          { role: "欧文", zh: "905。", pinyin: "905。", vi: "905." },
          { role: "服务员", zh: "您是付现金还是刷卡？", pinyin: "nín shì fù xiàn jīn hái shì shuā kǎ？", vi: "Anh trả tiền mặt hay quẹt thẻ?" },
          { role: "欧文", zh: "付现金。多少钱？", pinyin: "fù xiàn jīn。 duō shǎo qián？", vi: "Trả tiền mặt. Bao nhiêu tiền vậy?" },
          { role: "服务员", zh: "一共九百三十块，您有五百块押金，付四百三十块就可以。押金的收据呢？", pinyin: "yī gòng jiǔ bǎi sān shí kuài， nín yǒu wǔ bǎi kuài yā jīn， fù sì bǎi sān shí kuài jiù kě yǐ。 yā jīn de shōu jù ne？", vi: "Tổng cộng 930 tệ, anh đã cọc 500 tệ, trả 430 tệ là được. Biên lai đặt cọc đâu ạ?" },
          { role: "欧文", zh: "这是收据，还给你。对了，附近有没有地铁站？", pinyin: "zhè shì shōu jù， huán gěi nǐ。 duì le， fù jìn yǒu méi yǒu dì tiě zhàn？", vi: "Đây là biên lai, trả lại cô. À, gần đây có ga tàu điện ngầm không?" },
          { role: "服务员", zh: "有。这是宾馆附近的地图。您看，从这里走到地铁站只要五分钟。", pinyin: "yǒu。 zhè shì bīn guǎn fù jìn de dì tú。 nín kàn， cóng zhè lǐ zǒu dào dì tiě zhàn zhǐ yào wǔ fēn zhōng。", vi: "Có. Đây là bản đồ khu vực quanh khách sạn. Anh xem này, từ đây đi bộ đến ga tàu điện ngầm chỉ mất năm phút." },
          { role: "欧文", zh: "这张地图很有帮助，可以送给我吗？", pinyin: "zhè zhāng dì tú hěn yǒu bāng zhù， kě yǐ sòng gěi wǒ ma？", vi: "Bản đồ này hữu ích lắm, có thể tặng cho tôi không?" },
          { role: "服务员", zh: "当然可以，给您。", pinyin: "dāng rán kě yǐ， gěi nín。", vi: "Tất nhiên được, mời anh." },
          { role: "欧文", zh: "谢谢你们热情的服务！", pinyin: "xiè xiè nǐ men rè qíng de fú wù！", vi: "Cảm ơn dịch vụ nhiệt tình của các bạn!" },
          { role: "服务员", zh: "谢谢光临，欢迎再来！", pinyin: "xiè xiè guāng lín， huān yíng zài lái！", vi: "Cảm ơn quý khách, hoan nghênh quay lại!" },
        ],
      },

      // ===== Bài 5 =====
      {
        id: "b4-5-1",
        baiNumber: 5,
        baiTitleZh: "每天都看得到美景",
        baiTitleVi: "Mỗi ngày đều nhìn thấy cảnh đẹp",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "卡玛拉", zh: "小明，四千五百块在学校附近租得到两室一厅吗？", pinyin: "xiǎo míng， sì qiān wǔ bǎi kuài zài xué xiào fù jìn zū dé dào liǎng shì yī tīng ma？", vi: "Tiểu Minh, 4500 tệ ở gần trường có thuê được phòng hai phòng ngủ một phòng khách không?" },
          { role: "高小明", zh: "两室一厅要六千以上。", pinyin: "liǎng shì yī tīng yào liù qiān yǐ shàng。", vi: "Hai phòng ngủ một phòng khách phải hơn 6000 tệ." },
          { role: "卡玛拉", zh: "房租这么贵啊，租不起。一室一厅一个月要多少钱？", pinyin: "fáng zū zhè me guì a， zū bù qǐ。 yī shì yī tīng yí gè yuè yào duō shǎo qián？", vi: "Tiền nhà đắt thế à, thuê không nổi. Một phòng ngủ một phòng khách mỗi tháng bao nhiêu tiền?" },
          { role: "高小明", zh: "三千五百块左右。卡玛拉，你想租房子？", pinyin: "sān qiān wǔ bǎi kuài zuǒ yòu。 kǎ mǎ lā， nǐ xiǎng zū fáng zi？", vi: "Khoảng 3500 tệ. Kamala, cậu muốn thuê nhà à?" },
          { role: "卡玛拉", zh: "对，我想租一套有家具和家用电器的房子。", pinyin: "duì， wǒ xiǎng zū yī tào yǒu jiā jù hé jiā yòng diàn qì de fáng zi。", vi: "Đúng, tớ muốn thuê một căn có sẵn nội thất và đồ điện gia dụng." },
          { role: "高小明", zh: "房子里一般都有家具和家用电器。", pinyin: "fáng zi lǐ yì bān dōu yǒu jiā jù hé jiā yòng diàn qì。", vi: "Trong nhà thường đều có nội thất và đồ điện gia dụng." },
          { role: "卡玛拉", zh: "你能陪我去房产公司吗？我听不懂他们说话，也看不懂合同。", pinyin: "nǐ néng péi wǒ qù fáng chǎn gōng sī ma？ wǒ tīng bù dǒng tā men shuō huà， yě kàn bù dǒng hé tóng。", vi: "Cậu có thể đi cùng tớ đến công ty bất động sản không? Tớ nghe không hiểu họ nói, cũng đọc không hiểu hợp đồng." },
          { role: "高小明", zh: "学校附近就有家房产公司，明天下午一起去看看吧。", pinyin: "xué xiào fù jìn jiù yǒu jiā fáng chǎn gōng sī， míng tiān xià wǔ yì qǐ qù kàn kàn ba。", vi: "Gần trường có một công ty bất động sản, chiều mai cùng đi xem đi." },
          { role: "卡玛拉", zh: "明天下午我有课，去不了。你上午方便吗？", pinyin: "míng tiān xià wǔ wǒ yǒu kè， qù bù liǎo。 nǐ shàng wǔ fāng biàn ma？", vi: "Chiều mai tớ có tiết, không đi được. Sáng cậu rảnh không?" },
          { role: "高小明", zh: "行，我九点在学校门口等你。", pinyin: "xíng， wǒ jiǔ diǎn zài xué xiào mén kǒu děng nǐ。", vi: "Được, chín giờ tớ đợi cậu ở cổng trường." },
        ],
      },
      {
        id: "b4-5-2",
        baiNumber: 5,
        baiTitleZh: "每天都看得到美景",
        baiTitleVi: "Mỗi ngày đều nhìn thấy cảnh đẹp",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "卡玛拉", zh: "小明，刚才房产公司的人介绍得详细吗？", pinyin: "xiǎo míng， gāng cái fáng chǎn gōng sī de rén jiè shào dé xiáng xì ma？", vi: "Tiểu Minh, vừa nãy nhân viên công ty bất động sản giới thiệu kỹ không?" },
          { role: "高小明", zh: "非常详细。卡玛拉，你没听懂吗？", pinyin: "fēi cháng xiáng xì。 kǎ mǎ lā， nǐ méi tīng dǒng ma？", vi: "Rất kỹ. Kamala, cậu không hiểu à?" },
          { role: "卡玛拉", zh: "只听懂了一点儿。是不是一个月三千六百块？", pinyin: "zhǐ tīng dǒng le yì diǎn ér。 shì bú shì yí gè yuè sān qiān liù bǎi kuài？", vi: "Chỉ hiểu được một chút. Có phải một tháng 3600 tệ không?" },
          { role: "高小明", zh: "对，家具是新的，但是电冰箱、洗衣机、空调比较旧。", pinyin: "duì， jiā jù shì xīn de， dàn shì diàn bīng xiāng、 xǐ yī jī、 kōng tiáo bǐ jiào jiù。", vi: "Đúng, đồ nội thất là đồ mới, nhưng tủ lạnh, máy giặt, điều hòa khá cũ." },
          { role: "卡玛拉", zh: "环境怎么样？", pinyin: "huán jìng zěn me yàng？", vi: "Môi trường thế nào?" },
          { role: "高小明", zh: "就在公园旁边，空气新鲜，每天都看得到美景。", pinyin: "jiù zài gōng yuán páng biān， kōng qì xīn xiān， měi tiān dōu kàn dé dào měi jǐng。", vi: "Ngay bên cạnh công viên, không khí trong lành, mỗi ngày đều nhìn thấy cảnh đẹp." },
          { role: "卡玛拉", zh: "离地铁站近吗？十分钟走得到吗？", pinyin: "lí dì tiě zhàn jìn ma？ shí fēn zhōng zǒu dé dào ma？", vi: "Gần ga tàu điện ngầm không? Đi bộ mười phút đến nơi được không?" },
          { role: "高小明", zh: "走得到，非常近。", pinyin: "zǒu dé dào， fēi cháng jìn。", vi: "Đến nơi được, rất gần." },
          { role: "卡玛拉", zh: "厅大吗？我常请朋友来家里，七八个人坐得下吗？", pinyin: "tīng dà ma？ wǒ cháng qǐng péng yǒu lái jiā lǐ， qī bā gè rén zuò dé xià ma？", vi: "Phòng khách có rộng không? Tớ thường mời bạn về nhà, bảy tám người có ngồi vừa không?" },
          { role: "高小明", zh: "没问题。你觉得满意吗？", pinyin: "méi wèn tí。 nǐ jué de mǎn yì ma？", vi: "Không vấn đề gì. Cậu thấy hài lòng không?" },
          { role: "卡玛拉", zh: "非常满意。下个月1号住得进去吗？", pinyin: "fēi cháng mǎn yì。 xià gè yuè 1 hào zhù dé jìn qù ma？", vi: "Rất hài lòng. Mùng 1 tháng sau dọn vào ở được không?" },
          { role: "高小明", zh: "住得进去。不过，得马上签合同。", pinyin: "zhù dé jìn qù。 bù guò， dé mǎ shàng qiān hé tóng。", vi: "Vào ở được. Nhưng phải ký hợp đồng ngay." },
        ],
      },

      // ===== Bài 6 =====
      {
        id: "b4-6-1",
        baiNumber: 6,
        baiTitleZh: "后面站着的两个女孩儿是谁？",
        baiTitleVi: "Hai cô gái đứng phía sau kia là ai?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "高小明，你拿着什么？", pinyin: "gāo xiǎo míng， nǐ ná zhe shén me？", vi: "Cao Tiểu Minh, cậu đang cầm gì vậy?" },
          { role: "高小明", zh: "以前拍的全家福。你看，这是我的爸爸和妈妈。我爸爸喜欢抽烟，所以他拿着烟。", pinyin: "yǐ qián pāi de quán jiā fú。 nǐ kàn， zhè shì wǒ de bà bà hé mā mā。 wǒ bà bà xǐ huān chōu yān， suǒ yǐ tā ná zhe yān。", vi: "Ảnh gia đình chụp ngày xưa. Cậu xem này, đây là bố và mẹ tớ. Bố tớ thích hút thuốc, nên ông cầm điếu thuốc." },
          { role: "海伦", zh: "你妈妈比爸爸年轻多了。", pinyin: "nǐ mā mā bǐ bà bà nián qīng duō le。", vi: "Mẹ cậu trẻ hơn bố nhiều quá." },
          { role: "高小明", zh: "对，我妈妈比爸爸小六岁。", pinyin: "duì， wǒ mā mā bǐ bà bà xiǎo liù suì。", vi: "Đúng vậy, mẹ tớ kém bố sáu tuổi." },
          { role: "海伦", zh: "后面站着的两个女孩儿是谁？", pinyin: "hòu miàn zhàn zhe de liǎng gè nǚ hái ér shì shuí？", vi: "Hai cô gái đứng phía sau kia là ai?" },
          { role: "高小明", zh: "一个是我姐姐，一个是我妹妹。你猜猜哪个是姐姐？", pinyin: "yí gè shì wǒ jiě jiě， yí gè shì wǒ mèi mèi。 nǐ cāi cāi nǎ ge shì jiě jiě？", vi: "Một là chị tớ, một là em gái tớ. Cậu đoán xem ai là chị?" },
          { role: "海伦", zh: "两个人一模一样，我怎么猜得到？", pinyin: "liǎng gè rén yī mú yī yàng， wǒ zěn me cāi dé dào？", vi: "Hai người giống y hệt nhau, tớ đoán làm sao được?" },
          { role: "高小明", zh: "怎么会一模一样？你再仔细地看看。", pinyin: "zěn me huì yī mú yī yàng？ nǐ zài zǐ xì dì kàn kàn。", vi: "Sao mà giống y hệt được? Cậu xem kỹ lại đi." },
          { role: "海伦", zh: "哦！戴眼镜的是姐姐，穿裙子的是妹妹，对吗？", pinyin: "ó！ dài yǎn jìng de shì jiě jiě， chuān qún zi de shì mèi mèi， duì ma？", vi: "À! Người đeo kính là chị, người mặc váy là em, đúng không?" },
          { role: "高小明", zh: "猜对了！海伦，可以看看你的全家福吗？", pinyin: "cāi duì le！ hǎi lún， kě yǐ kàn kàn nǐ de quán jiā fú ma？", vi: "Đoán đúng rồi! Helen, cho tớ xem ảnh gia đình của cậu được không?" },
          { role: "海伦", zh: "行，我明天一定带来。", pinyin: "xíng， wǒ míng tiān yí dìng dài lái。", vi: "Được, mai tớ nhất định mang đến." },
        ],
      },
      {
        id: "b4-6-2",
        baiNumber: 6,
        baiTitleZh: "后面站着的两个女孩儿是谁？",
        baiTitleVi: "Hai cô gái đứng phía sau kia là ai?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "高小明", zh: "海伦，你的全家福带来了吗？", pinyin: "gāo xiǎo míng， nǐ de quán jiā fú dài lái le ma？", vi: "Helen, ảnh gia đình của cậu mang đến chưa?" },
          { role: "海伦", zh: "带来了，在我的手机里。你看看。", pinyin: "dài lái le， zài wǒ de shǒu jī lǐ。 nǐ kàn kàn。", vi: "Có mang theo, trong điện thoại tớ. Cậu xem đi." },
          { role: "高小明", zh: "你的爸爸和妈妈在沙发上坐着，两个孩子，一个在沙发后面站着，一个在妈妈旁边坐着。这张全家福什么时候拍的？", pinyin: "nǐ de bà bà hé mā mā zài shā fā shàng zuò zhe， liǎng gè hái zi， yí gè zài shā fā hòu miàn zhàn zhe， yí gè zài mā mā páng biān zuò zhe。 zhè zhāng quán jiā fú shén me shí hòu pāi de？", vi: "Bố và mẹ cậu ngồi trên ghế sofa, hai đứa trẻ, một đứa đứng phía sau sofa, một đứa ngồi cạnh mẹ. Ảnh gia đình này chụp khi nào vậy?" },
          { role: "海伦", zh: "是我小时候拍的。高小明，你猜猜哪个是我？", pinyin: "shì wǒ xiǎo shí hòu pāi de。 gāo xiǎo míng， nǐ cāi cāi nǎ ge shì wǒ？", vi: "Chụp hồi tớ còn nhỏ. Cao Tiểu Minh, cậu đoán xem ai là tớ?" },
          { role: "高小明", zh: "你坐在妈妈旁边，拿着花儿，开心地笑着，对不对？", pinyin: "nǐ zuò zài mā mā páng biān， ná zhe huā ér， kāi xīn dì xiào zhe， duì bú duì？", vi: "Cậu ngồi cạnh mẹ, cầm hoa, cười tươi vui vẻ, đúng không?" },
          { role: "海伦", zh: "不对，我拿着巧克力。", pinyin: "bú duì， wǒ ná zhe qiǎo kè lì。", vi: "Sai rồi, tớ cầm sô-cô-la." },
          { role: "高小明", zh: "哦！那个站着的孩子是你，怎么跟男孩子一模一样！", pinyin: "ó！ nà ge zhàn zhe de hái zi shì nǐ， zěn me gēn nán hái zi yī mú yī yàng！", vi: "À! Đứa đang đứng kia là cậu, sao mà giống con trai y hệt vậy!" },
          { role: "海伦", zh: "对，小时候我总是打扮得跟男孩子一样。", pinyin: "duì， xiǎo shí hòu wǒ zǒng shì dǎ bàn dé gēn nán hái zi yī yàng。", vi: "Đúng vậy, hồi nhỏ tớ luôn ăn mặc giống con trai." },
          { role: "高小明", zh: "那我怎么猜得到？", pinyin: "nà wǒ zěn me cāi dé dào？", vi: "Vậy làm sao tớ đoán được?" },
        ],
      },

      // ===== Bài 7 =====
      {
        id: "b4-7-1",
        baiNumber: 7,
        baiTitleZh: "我想把美元换成人民币",
        baiTitleVi: "Tôi muốn đổi đô la Mỹ sang nhân dân tệ",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "您好，我想把美元换成人民币。", pinyin: "nín hǎo， wǒ xiǎng bǎ měi yuán huàn chéng rén mín bì。", vi: "Xin chào, tôi muốn đổi đô la Mỹ sang nhân dân tệ." },
          { role: "银行职员", zh: "请把这张表填一下，填好以后，把它给我。", pinyin: "qǐng bǎ zhè zhāng biǎo tián yī xià， tián hǎo yǐ hòu， bǎ tā gěi wǒ。", vi: "Xin điền vào tờ phiếu này, điền xong đưa cho tôi." },
          { role: "海伦", zh: "表格上都是汉语，有些地方我看不懂。您能不能帮我翻译成英语？", pinyin: "biǎo gé shàng dōu shì hàn yǔ， yǒu xiē dì fāng wǒ kàn bù dǒng。 nín néng bù néng bāng wǒ fān yì chéng yīng yǔ？", vi: "Trên phiếu toàn tiếng Hán, có chỗ tôi không hiểu. Bạn có thể giúp tôi dịch sang tiếng Anh không?" },
          { role: "银行职员", zh: "不好意思，我不会英语，翻译不了。", pinyin: "bù hǎo yì sī， wǒ bú huì yīng yǔ， fān yì bù liǎo。", vi: "Xin lỗi, tôi không biết tiếng Anh, không dịch được." },
          { role: "海伦", zh: "今天的汇率是多少？", pinyin: "jīn tiān de huì lǜ shì duō shǎo？", vi: "Tỷ giá hôm nay là bao nhiêu?" },
          { role: "银行职员", zh: "一百美元换六百二十元人民币。您想换多少美元？", pinyin: "yì bǎi měi yuán huàn liù bǎi èr shí yuán rén mín bì。 nín xiǎng huàn duō shǎo měi yuán？", vi: "100 đô la đổi được 620 nhân dân tệ. Cô muốn đổi bao nhiêu đô?" },
          { role: "海伦", zh: "换一千美元。", pinyin: "huàn yī qiān měi yuán。", vi: "Đổi 1000 đô." },
          { role: "银行职员", zh: "请把护照、表格和钱给我。", pinyin: "qǐng bǎ hù zhào、 biǎo gé hé qián gěi wǒ。", vi: "Vui lòng đưa hộ chiếu, tờ khai và tiền cho tôi." },
          { role: "海伦", zh: "不好意思，我换不了了，把表格还给我吧。", pinyin: "bù hǎo yì sī， wǒ huàn bù liǎo le， bǎ biǎo gé huán gěi wǒ ba。", vi: "Xin lỗi, tôi không đổi được nữa, trả tờ khai lại cho tôi nhé." },
          { role: "银行职员", zh: "怎么了？", pinyin: "zěn me le？", vi: "Sao vậy ạ?" },
          { role: "海伦", zh: "我忘了带护照。我家离这儿很近，我回去把护照拿来。", pinyin: "wǒ wàng le dài hù zhào。 wǒ jiā lí zhè ér hěn jìn， wǒ huí qù bǎ hù zhào ná lái。", vi: "Tôi quên mang hộ chiếu. Nhà tôi gần đây, tôi về lấy hộ chiếu rồi quay lại." },
          { role: "银行职员", zh: "请把您的表格和钱拿好，再来的时候，还用这张表格。", pinyin: "qǐng bǎ nín de biǎo gé hé qián ná hǎo， zài lái de shí hòu， hái yòng zhè zhāng biǎo gé。", vi: "Xin giữ kỹ tờ khai và tiền, khi quay lại vẫn dùng tờ khai này." },
        ],
      },
      {
        id: "b4-7-2",
        baiNumber: 7,
        baiTitleZh: "我想把美元换成人民币",
        baiTitleVi: "Tôi muốn đổi đô la Mỹ sang nhân dân tệ",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "您好，我想在你们银行办一张卡。", pinyin: "nín hǎo， wǒ xiǎng zài nǐ men yín háng bàn yī zhāng kǎ。", vi: "Xin chào, tôi muốn mở một thẻ tại ngân hàng các bạn." },
          { role: "银行职员", zh: "您是外国人吧？外国人一般只能办借记卡，不能办信用卡。", pinyin: "nín shì wài guó rén ba？ wài guó rén yì bān zhǐ néng bàn jiè jì kǎ， bù néng bàn xìn yòng kǎ。", vi: "Cô là người nước ngoài phải không? Người nước ngoài thường chỉ làm được thẻ ghi nợ, không làm được thẻ tín dụng." },
          { role: "海伦", zh: "我就办借记卡。", pinyin: "wǒ jiù bàn jiè jì kǎ。", vi: "Vậy tôi làm thẻ ghi nợ." },
          { role: "银行职员", zh: "请填写这张表格，填好以后，把它和护照一起给我。", pinyin: "qǐng tián xiě zhè zhāng biǎo gé， tián hǎo yǐ hòu， bǎ tā hé hù zhào yì qǐ gěi wǒ。", vi: "Vui lòng điền tờ khai này, điền xong đưa cùng với hộ chiếu cho tôi." },
          { role: "银行职员", zh: "您把地址写错了，应该写您在中国的地址。", pinyin: "nín bǎ dì zhǐ xiě cuò le， yīng gāi xiě nín zài zhōng guó de dì zhǐ。", vi: "Cô viết nhầm địa chỉ rồi, phải viết địa chỉ của cô ở Trung Quốc." },
          { role: "海伦", zh: "好的，请把表格还给我，我修改一下。", pinyin: "hǎo de， qǐng bǎ biǎo gé huán gěi wǒ， wǒ xiū gǎi yī xià。", vi: "Vâng, xin trả tờ khai lại cho tôi, tôi sửa lại." },
          { role: "银行职员", zh: "办借记卡需要手续费五元，请准备一下。", pinyin: "bàn jiè jì kǎ xū yào shǒu xù fèi wǔ yuán， qǐng zhǔn bèi yī xià。", vi: "Mở thẻ ghi nợ cần phí dịch vụ 5 tệ, xin chuẩn bị." },
          { role: "海伦", zh: "糟糕，我把钱包忘在家里了，得回去取。", pinyin: "zāo gāo， wǒ bǎ qián bāo wàng zài jiā lǐ le， dé huí qù qǔ。", vi: "Chết rồi, tôi để quên ví ở nhà, phải về lấy." },
          { role: "银行职员", zh: "您的家远吗？", pinyin: "nín de jiā yuǎn ma？", vi: "Nhà cô có xa không?" },
          { role: "海伦", zh: "就在附近。对了，今天就可以把借记卡给我吗？", pinyin: "jiù zài fù jìn。 duì le， jīn tiān jiù kě yǐ bǎ jiè jì kǎ gěi wǒ ma？", vi: "Ngay gần đây. À, hôm nay đã có thể đưa thẻ ghi nợ cho tôi luôn không?" },
          { role: "银行职员", zh: "可以。您在卡里存钱以后，今天就能用了。", pinyin: "kě yǐ。 nín zài kǎ lǐ cún qián yǐ hòu， jīn tiān jiù néng yòng le。", vi: "Được. Sau khi cô gửi tiền vào thẻ, hôm nay là có thể dùng được." },
          { role: "海伦", zh: "请等一下，我马上回家取钱。", pinyin: "qǐng děng yí xià， wǒ mǎ shàng huí jiā qǔ qián。", vi: "Xin đợi một chút, tôi về nhà lấy tiền ngay." },
        ],
      },

      // ===== Bài 8 =====
      {
        id: "b4-8-1",
        baiNumber: 8,
        baiTitleZh: "请把护照拿出来",
        baiTitleVi: "Vui lòng xuất trình hộ chiếu",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "女安检员", zh: "请问，您带打火机了吗？", pinyin: "qǐng wèn， nín dài dǎ huǒ jī le ma？", vi: "Xin hỏi, anh có mang bật lửa không?" },
          { role: "田中", zh: "带了。不能带吗？", pinyin: "dài le。 bù néng dài ma？", vi: "Có mang. Không được mang à?" },
          { role: "女安检员", zh: "对，请把它扔到旁边的垃圾箱里。请把护照、登机牌拿出来。", pinyin: "duì， qǐng bǎ tā rēng dào páng biān de lā jī xiāng lǐ。 qǐng bǎ hù zhào、 dēng jī pái ná chū lái。", vi: "Đúng, xin vứt nó vào thùng rác bên cạnh. Vui lòng lấy hộ chiếu, thẻ lên máy bay ra." },
          { role: "田中", zh: "这是我的护照和登机牌。", pinyin: "zhè shì wǒ de hù zhào hé dēng jī pái。", vi: "Đây là hộ chiếu và thẻ lên máy bay của tôi." },
          { role: "女安检员", zh: "请给我看一下。请把手机、电脑、钱包从旅行箱里拿出来。", pinyin: "qǐng gěi wǒ kàn yī xià。 qǐng bǎ shǒu jī、 diàn nǎo、 qián bāo cóng lǚ xíng xiāng lǐ ná chū lái。", vi: "Cho tôi xem một chút. Xin lấy điện thoại, máy tính, ví ra khỏi va li." },
          { role: "田中", zh: "放在哪里？", pinyin: "fàng zài nǎ lǐ？", vi: "Để vào đâu ạ?" },
          { role: "女安检员", zh: "放在托盘里。请把外衣脱下来，也放在托盘里。", pinyin: "fàng zài tuō pán lǐ。 qǐng bǎ wài yī tuō xià lái， yě fàng zài tuō pán lǐ。", vi: "Để vào khay. Xin cởi áo khoác ra, cũng để vào khay." },
          { role: "女安检员", zh: "请把自己的东西拿好，不要拿错。", pinyin: "qǐng bǎ zì jǐ de dōng xī ná hǎo， bú yào ná cuò。", vi: "Xin lấy đồ của mình cẩn thận, đừng lấy nhầm." },
          { role: "田中", zh: "都拿好了，谢谢！", pinyin: "dōu ná hǎo le， xiè xiè！", vi: "Đã lấy hết rồi, cảm ơn!" },
          { role: "女安检员", zh: "您忘了拿护照了。", pinyin: "nín wàng le ná hù zhào le。", vi: "Anh quên lấy hộ chiếu rồi." },
          { role: "田中", zh: "不好意思，我把护照忘在托盘里了。", pinyin: "bù hǎo yì sī， wǒ bǎ hù zhào wàng zài tuō pán lǐ le。", vi: "Xin lỗi, tôi để quên hộ chiếu trong khay." },
          { role: "女安检员", zh: "您的旅行箱也没有关好。", pinyin: "nín de lǚ xíng xiāng yě méi yǒu guān hǎo。", vi: "Va li của anh cũng chưa đóng kỹ." },
        ],
      },
      {
        id: "b4-8-2",
        baiNumber: 8,
        baiTitleZh: "请把护照拿出来",
        baiTitleVi: "Vui lòng xuất trình hộ chiếu",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "女安检员", zh: "您好，您要去哪儿？", pinyin: "nín hǎo， nín yào qù nǎ ér？", vi: "Xin chào, anh đi đâu vậy?" },
          { role: "田中", zh: "我去西安。", pinyin: "wǒ qù xī ān。", vi: "Tôi đi Tây An." },
          { role: "女安检员", zh: "请把火车票、身份证件拿出来。", pinyin: "qǐng bǎ huǒ chē piào、 shēn fèn zhèng jiàn ná chū lái。", vi: "Xin lấy vé tàu, giấy tờ tùy thân ra." },
          { role: "田中", zh: "这是我的护照和车票。", pinyin: "zhè shì wǒ de hù zhào hé chē piào。", vi: "Đây là hộ chiếu và vé tàu của tôi." },
          { role: "女安检员", zh: "先生，您的旅行箱里放着什么？", pinyin: "xiān shēng， nín de lǚ xíng xiāng lǐ fàng zhe shén me？", vi: "Thưa anh, trong va li của anh để gì?" },
          { role: "田中", zh: "放着电脑、衣服和送朋友的礼物。", pinyin: "fàng zhe diàn nǎo、 yī fú hé sòng péng yǒu de lǐ wù。", vi: "Để máy tính, quần áo và quà tặng bạn." },
          { role: "女安检员", zh: "请把旅行箱打开，需要检查一下。", pinyin: "qǐng bǎ lǚ xíng xiāng dǎ kāi， xū yào jiǎn chá yī xià。", vi: "Xin mở va li ra, cần kiểm tra một chút." },
          { role: "女安检员", zh: "您带水果刀了吧？", pinyin: "nín dài shuǐ guǒ dāo le ba？", vi: "Anh có mang dao gọt hoa quả phải không?" },
          { role: "田中", zh: "带了，水果刀比较大，不能带吗？", pinyin: "dài le， shuǐ guǒ dāo bǐ jiào dà， bù néng dài ma？", vi: "Có mang, dao gọt hoa quả khá to, không được mang à?" },
          { role: "女安检员", zh: "对，坐火车不能带大的水果刀。", pinyin: "duì， zuò huǒ chē bù néng dài dà de shuǐ guǒ dāo。", vi: "Đúng, đi tàu không được mang dao gọt hoa quả lớn." },
          { role: "田中", zh: "不好意思，我不知道这个规定。", pinyin: "bù hǎo yì sī， wǒ bù zhī dào zhè ge guī dìng。", vi: "Xin lỗi, tôi không biết quy định này." },
          { role: "女安检员", zh: "请您把刀拿出来，不能带进去。", pinyin: "qǐng nín bǎ dāo ná chū lái， bù néng dài jìn qù。", vi: "Xin anh lấy dao ra, không được mang vào." },
        ],
      },

      // ===== Bài 9 =====
      {
        id: "b4-9-1",
        baiNumber: 9,
        baiTitleZh: "你的电脑可能被病毒感染了",
        baiTitleVi: "Máy tính của bạn có lẽ đã bị nhiễm virus",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "卡玛拉", zh: "真倒霉，我的电脑最近总是死机，上不了网。", pinyin: "zhēn dǎo méi， wǒ de diàn nǎo zuì jìn zǒng shì sǐ jī， shàng bù liǎo wǎng。", vi: "Đen quá, máy tính tớ gần đây cứ bị treo, không vào được mạng." },
          { role: "欧文", zh: "卡玛拉，你的电脑可能被病毒感染了。", pinyin: "kǎ mǎ lā， nǐ de diàn nǎo kě néng bèi bìng dú gǎn rǎn le。", vi: "Kamala, máy tính cậu có lẽ đã bị nhiễm virus." },
          { role: "卡玛拉", zh: "对，我杀了很多次毒。病毒是被杀掉了，但是，很多文件被删除掉了，找不回来了。", pinyin: "duì， wǒ shā le hěn duō cì dú。 bìng dú shì bèi shā diào le， dàn shì， hěn duō wén jiàn bèi shān chú diào le， zhǎo bù huí lái le。", vi: "Đúng vậy, tớ đã quét virus rất nhiều lần. Virus thì đã bị diệt, nhưng nhiều tập tin đã bị xóa, không tìm lại được." },
          { role: "欧文", zh: "我的U盘上个星期也被病毒感染，打不开了。", pinyin: "wǒ de U pán shàng gè xīng qī yě bèi bìng dú gǎn rǎn， dǎ bù kāi le。", vi: "USB của tớ tuần trước cũng bị nhiễm virus, không mở được nữa." },
          { role: "卡玛拉", zh: "欧文，你杀毒了吗？", pinyin: "ōu wén， nǐ shā dú le ma？", vi: "Owen, cậu đã quét virus chưa?" },
          { role: "欧文", zh: "这次非常严重，杀不掉。", pinyin: "zhè cì fēi cháng yán zhòng， shā bù diào。", vi: "Lần này nghiêm trọng lắm, diệt không nổi." },
          { role: "卡玛拉", zh: "U盘里有重要的文件吗？", pinyin: "U pán lǐ yǒu zhòng yào de wén jiàn ma？", vi: "Trong USB có tập tin quan trọng không?" },
          { role: "欧文", zh: "没有，U盘被我扔掉了。", pinyin: "méi yǒu，U pán bèi wǒ rēng diào le。", vi: "Không có, USB tớ đã vứt rồi." },
          { role: "卡玛拉", zh: "我的电脑已经用了八年了，老了，也应该让它退休了。", pinyin: "wǒ de diàn nǎo yǐ jīng yòng le bā nián le， lǎo le， yě yīng gāi ràng tā tuì xiū le。", vi: "Máy tính tớ đã dùng tám năm rồi, cũ rồi, cũng nên cho nó nghỉ hưu thôi." },
          { role: "欧文", zh: "那是被你用坏的。", pinyin: "nà shì bèi nǐ yòng huài de。", vi: "Đó là do cậu dùng hỏng đấy." },
          { role: "卡玛拉", zh: "一样，你的U盘也是被你用坏的！", pinyin: "yī yàng， nǐ de U pán yě shì bèi nǐ yòng huài de！", vi: "Cũng vậy thôi, USB của cậu cũng là do cậu dùng hỏng!" },
        ],
      },
      {
        id: "b4-9-2",
        baiNumber: 9,
        baiTitleZh: "你的电脑可能被病毒感染了",
        baiTitleVi: "Máy tính của bạn có lẽ đã bị nhiễm virus",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "田中", zh: "海伦，我正找你呢！", pinyin: "hǎi lún， wǒ zhèng zhǎo nǐ ne！", vi: "Helen, tớ đang tìm cậu đây!" },
          { role: "海伦", zh: "什么事这么着急？", pinyin: "shén me shì zhè me zhe jí？", vi: "Có chuyện gì mà sốt ruột thế?" },
          { role: "田中", zh: "我的信用卡刚刚被刷了三千块钱，怎么能不着急？", pinyin: "wǒ de xìn yòng kǎ gāng gāng bèi shuā le sān qiān kuài qián， zěn me néng bù zháo jí？", vi: "Thẻ tín dụng của tớ vừa bị quẹt mất 3000 tệ, làm sao mà không sốt ruột được?" },
          { role: "海伦", zh: "你的信用卡是不是让人偷了？", pinyin: "nǐ de xìn yòng kǎ shì bú shì ràng rén tōu le？", vi: "Thẻ tín dụng của cậu có phải bị người ta lấy trộm không?" },
          { role: "田中", zh: "没有被偷，是手机被病毒感染了。", pinyin: "méi yǒu bèi tōu， shì shǒu jī bèi bìng dú gǎn rǎn le。", vi: "Không bị trộm, là điện thoại bị nhiễm virus." },
          { role: "海伦", zh: "你开通了手机银行？", pinyin: "nǐ kāi tōng le shǒu jī yín háng？", vi: "Cậu có kích hoạt ngân hàng di động không?" },
          { role: "田中", zh: "对。是病毒偷了我的钱。听说你会给手机杀毒，我马上就来找你了。", pinyin: "duì。 shì bìng dú tōu le wǒ de qián。 tīng shuō nǐ huì gěi shǒu jī shā dú， wǒ mǎ shàng jiù lái zhǎo nǐ le。", vi: "Có. Virus đã lấy trộm tiền của tớ. Nghe nói cậu biết diệt virus điện thoại, tớ chạy đến tìm cậu ngay." },
          { role: "海伦", zh: "把手机给我看一下。啊，真的被病毒感染了。", pinyin: "bǎ shǒu jī gěi wǒ kàn yī xià。 a， zhēn de bèi bìng dú gǎn rǎn le。", vi: "Đưa điện thoại tớ xem nào. À, thật sự bị nhiễm virus rồi." },
          { role: "田中", zh: "能把病毒杀掉吗？", pinyin: "néng bǎ bìng dú shā diào ma？", vi: "Có diệt được virus không?" },
          { role: "海伦", zh: "能。你放心吧，马上帮你杀病毒。", pinyin: "néng。 nǐ fàng xīn ba， mǎ shàng bāng nǐ shā bìng dú。", vi: "Được. Cậu yên tâm, tớ giúp cậu diệt virus ngay." },
          { role: "田中", zh: "太谢谢你了！", pinyin: "tài xiè xiè nǐ le！", vi: "Cảm ơn cậu nhiều lắm!" },
        ],
      },

      // ===== Bài 10 =====
      {
        id: "b4-10-1",
        baiNumber: 10,
        baiTitleZh: "祝你一路平安",
        baiTitleVi: "Chúc bạn thượng lộ bình an",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "高小明", zh: "时间过得太快了！卡玛拉，你已经在这儿学习了两年，后天就要回国了。", pinyin: "shí jiān guò dé tài kuài le！ kǎ mǎ lā， nǐ yǐ jīng zài zhè ér xué xí le liǎng nián， hòu tiān jiù yào huí guó le。", vi: "Thời gian trôi nhanh thật! Kamala, cậu đã học ở đây hai năm rồi, ngày kia là về nước." },
          { role: "卡玛拉", zh: "是啊。你给了我很多帮助，小明，太谢谢你了！", pinyin: "shì a。 nǐ gěi le wǒ hěn duō bāng zhù， xiǎo míng， tài xiè xiè nǐ le！", vi: "Đúng vậy. Cậu đã giúp tớ rất nhiều, Tiểu Minh, cảm ơn cậu rất nhiều!" },
          { role: "高小明", zh: "应该的，不用谢。你都准备好了吗？", pinyin: "yīng gāi de， bù yòng xiè。 nǐ dōu zhǔn bèi hǎo le ma？", vi: "Đáng làm thôi, không cần cảm ơn. Cậu chuẩn bị xong hết chưa?" },
          { role: "卡玛拉", zh: "早就准备好了，有两个行李箱，不知道会不会超重。", pinyin: "zǎo jiù zhǔn bèi hǎo le， yǒu liǎng gè xíng lǐ xiāng， bù zhī dào huì bú huì chāo zhòng。", vi: "Đã chuẩn bị xong từ lâu, có hai va li, không biết có bị quá ký không." },
          { role: "高小明", zh: "三十公斤左右没有问题吧。我有电子秤，明天带过来称一下吧。", pinyin: "sān shí gōng jīn zuǒ yòu méi yǒu wèn tí ba。 wǒ yǒu diàn zi chèng， míng tiān dài guò lái chēng yī xià ba。", vi: "Khoảng 30 ký thì không vấn đề gì. Tớ có cân điện tử, mai mang qua cân thử nhé." },
          { role: "卡玛拉", zh: "那谢谢你了。我准备后天早上七点出发，七点叫得到出租车吗？", pinyin: "nà xiè xiè nǐ le。 wǒ zhǔn bèi hòu tiān zǎo shàng qī diǎn chū fā， qī diǎn jiào dé dào chū zū chē ma？", vi: "Vậy cảm ơn cậu. Tớ định ngày kia 7 giờ sáng xuất phát, 7 giờ có gọi được taxi không?" },
          { role: "高小明", zh: "很难。明天晚上预约一下吧。你是几点的航班？", pinyin: "hěn nán。 míng tiān wǎn shàng yù yuē yī xià ba。 nǐ shì jǐ diǎn de háng bān？", vi: "Khó lắm. Tối mai đặt trước đi. Cậu chuyến bay mấy giờ?" },
          { role: "卡玛拉", zh: "九点半，来得及吗？", pinyin: "jiǔ diǎn bàn， lái de jí ma？", vi: "9 giờ 30, kịp không?" },
          { role: "高小明", zh: "从这里开到机场要一个小时左右，可能来不及。", pinyin: "cóng zhè lǐ kāi dào jī chǎng yào yí gè xiǎo shí zuǒ yòu， kě néng lái bù jí。", vi: "Từ đây lái xe đến sân bay mất khoảng một tiếng, có thể không kịp." },
          { role: "卡玛拉", zh: "那六点半出发吧。", pinyin: "nà liù diǎn bàn chū fā ba。", vi: "Vậy 6 giờ 30 xuất phát đi." },
          { role: "高小明", zh: "后天我来送你，把你送到机场。", pinyin: "hòu tiān wǒ lái sòng nǐ， bǎ nǐ sòng dào jī chǎng。", vi: "Ngày kia tớ đến tiễn cậu, đưa cậu đến sân bay." },
          { role: "卡玛拉", zh: "太早了，不用送我了。", pinyin: "tài zǎo le， bù yòng sòng wǒ le。", vi: "Sớm quá, không cần tiễn tớ đâu." },
          { role: "高小明", zh: "我们是好朋友，怎么能不送呢？", pinyin: "wǒ men shì hǎo péng yǒu， zěn me néng bù sòng ne？", vi: "Chúng ta là bạn thân, sao có thể không tiễn được?" },
        ],
      },
      {
        id: "b4-10-2",
        baiNumber: 10,
        baiTitleZh: "祝你一路平安",
        baiTitleVi: "Chúc bạn thượng lộ bình an",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "高小明", zh: "卡玛拉，你的行李超重了。", pinyin: "kǎ mǎ lā， nǐ de xíng lǐ chāo zhòng le。", vi: "Kamala, hành lý của cậu quá ký rồi." },
          { role: "卡玛拉", zh: "是啊，我要把美好的回忆都带回去，东西太多了，当然超重。", pinyin: "shì a， wǒ yào bǎ měi hǎo de huí yì dōu dài huí qù， dōng xī tài duō le， dāng rán chāo zhòng。", vi: "Đúng vậy, tớ phải mang theo tất cả ký ức đẹp về, đồ nhiều quá, đương nhiên là quá ký." },
          { role: "高小明", zh: "见面容易，说再见难。我们就要说再见了。", pinyin: "jiàn miàn róng yì， shuō zài jiàn nán。 wǒ men jiù yào shuō zài jiàn le。", vi: "Gặp nhau thì dễ, nói tạm biệt thì khó. Chúng ta sắp phải nói tạm biệt rồi." },
          { role: "卡玛拉", zh: "是啊，我真舍不得离开这里，舍不得离开大家。", pinyin: "shì a， wǒ zhēn shě bù dé lí kāi zhè lǐ， shě bù dé lí kāi dà jiā。", vi: "Đúng vậy, tớ thật sự không nỡ rời đi, không nỡ xa mọi người." },
          { role: "高小明", zh: "你是不是有些难过了？", pinyin: "nǐ shì bú shì yǒu xiē nán guò le？", vi: "Cậu có thấy hơi buồn không?" },
          { role: "卡玛拉", zh: "怎么会难过呢？我是高高兴兴地来中国的，也要高高兴兴地回国去。", pinyin: "zěn me huì nán guò ne？ wǒ shì gāo gāo xìng xìng dì lái zhōng guó de， yě yào gāo gāo xìng xìng dì huí guó qù。", vi: "Sao lại buồn được? Tớ vui vẻ đến Trung Quốc, cũng phải vui vẻ về nước." },
          { role: "高小明", zh: "以后多联系。", pinyin: "yǐ hòu duō lián xì。", vi: "Sau này giữ liên lạc nhé." },
          { role: "卡玛拉", zh: "好的，现在手机联系又快又方便，世界越来越小了。", pinyin: "hǎo de， xiàn zài shǒu jī lián xì yòu kuài yòu fāng biàn， shì jiè yuè lái yuè xiǎo le。", vi: "Được, bây giờ liên lạc qua điện thoại vừa nhanh vừa tiện, thế giới càng ngày càng nhỏ." },
          { role: "高小明", zh: "欢迎以后有机会再来中国。", pinyin: "huān yíng yǐ hòu yǒu jī huì zài lái zhōng guó。", vi: "Hoan nghênh sau này có dịp lại đến Trung Quốc." },
          { role: "卡玛拉", zh: "也欢迎你去我的国家旅行。", pinyin: "yě huān yíng nǐ qù wǒ de guó jiā lǚ xíng。", vi: "Cũng hoan nghênh cậu đến đất nước tớ du lịch." },
          { role: "高小明", zh: "一定去。祝你一路平安！", pinyin: "yí dìng qù。 zhù nǐ yí lù píng ān！", vi: "Nhất định sẽ đi. Chúc cậu thượng lộ bình an!" },
          { role: "卡玛拉", zh: "谢谢，再见！", pinyin: "xiè xiè， zài jiàn！", vi: "Cảm ơn, tạm biệt!" },
        ],
      },
    ],
  });
})();
