// Dữ liệu hội thoại Msutong Sơ cấp B3 (Bài 1-10)
// Trích từ hoi-thoai-b3-bai-1-10.md — 20 bài học (mỗi "Bài khóa" = 1 lesson).

(function () {
  window.dialogueBooks = window.dialogueBooks || [];
  window.dialogueBooks.push({
    id: "msutong-b3",
    shortName: "B3",
    name: "Msutong Sơ cấp B3",
    lessons: [
      // ===== Bài 1 =====
      {
        id: "b3-1-1",
        baiNumber: 1,
        baiTitleZh: "我家在农村",
        baiTitleVi: "Nhà tôi ở nông thôn",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "小明，你是北方人还是南方人？", pinyin: "xiǎo míng， nǐ shì běi fāng rén hái shì nán fāng rén？", vi: "Tiểu Minh, cậu là người miền Bắc hay người miền Nam?" },
          { role: "高小明", zh: "我是南方人，我老家在四川。", pinyin: "wǒ shì nán fāng rén， wǒ lǎo jiā zài sì chuān。", vi: "Tớ là người miền Nam, quê tớ ở Tứ Xuyên." },
          { role: "海伦", zh: "你家在城市还是在农村？", pinyin: "nǐ jiā zài chéng shì hái shì zài nóng cūn？", vi: "Nhà cậu ở thành phố hay ở nông thôn?" },
          { role: "高小明", zh: "我家在农村。", pinyin: "wǒ jiā zài nóng cūn。", vi: "Nhà tớ ở nông thôn." },
          { role: "海伦", zh: "环境一定不错吧？", pinyin: "huán jìng yí dìng bù cuò ba？", vi: "Môi trường chắc chắn rất tốt nhỉ?" },
          { role: "高小明", zh: "那当然，我家北边是大山，南边是小山，东边、西边都是田野，空气新鲜，环境很好。", pinyin: "nà dāng rán， wǒ jiā běi biān shì dà shān， nán biān shì xiǎo shān， dōng biān、 xī biān dōu shì tián yě， kōng qì xīn xiān， huán jìng hěn hǎo。", vi: "Tất nhiên rồi, phía Bắc nhà tớ là núi lớn, phía Nam là núi nhỏ, phía Đông và phía Tây đều là đồng ruộng, không khí trong lành, môi trường rất tốt." },
          { role: "海伦", zh: "真是好地方！", pinyin: "zhēn shì hǎo dì fāng！", vi: "Đúng là nơi tốt!" },
          { role: "高小明", zh: "可是，离城市很远，交通不太方便。", pinyin: "kě shì， lí chéng shì hěn yuǎn， jiāo tōng bù tài fāng biàn。", vi: "Nhưng mà, cách thành phố rất xa, giao thông không tiện lắm." },
          { role: "海伦", zh: "你家附近有学校吗？", pinyin: "nǐ jiā fù jìn yǒu xué xiào ma？", vi: "Gần nhà cậu có trường học không?" },
          { role: "高小明", zh: "只有小学，没有中学。我是在城市上中学的。", pinyin: "zhǐ yǒu xiǎo xué， méi yǒu zhōng xué。 wǒ shì zài chéng shì shàng zhōng xué de。", vi: "Chỉ có trường tiểu học, không có trường trung học. Tớ học trung học ở thành phố." },
          { role: "海伦", zh: "下次去你的老家玩儿玩儿，可以吗？", pinyin: "xià cì qù nǐ de lǎo jiā wán ér wán ér， kě yǐ ma？", vi: "Lần sau đến quê cậu chơi, được không?" },
          { role: "高小明", zh: "当然可以，欢迎欢迎！", pinyin: "dāng rán kě yǐ， huān yíng huān yíng！", vi: "Tất nhiên là được, hoan nghênh hoan nghênh!" },
        ],
      },
      {
        id: "b3-1-2",
        baiNumber: 1,
        baiTitleZh: "我家在农村",
        baiTitleVi: "Nhà tôi ở nông thôn",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "文丽，你喜欢农村还是城市？", pinyin: "wén lì， nǐ xǐ huān nóng cūn hái shì chéng shì？", vi: "Văn Lệ, cậu thích nông thôn hay thành phố?" },
          { role: "王文丽", zh: "都喜欢。欧文，你家在城市还是农村？", pinyin: "dōu xǐ huān。 ōu wén， nǐ jiā zài chéng shì hái shì nóng cūn？", vi: "Cả hai đều thích. Owen, nhà cậu ở thành phố hay nông thôn?" },
          { role: "欧文", zh: "我家在城市。", pinyin: "wǒ jiā zài chéng shì。", vi: "Nhà tớ ở thành phố." },
          { role: "王文丽", zh: "那儿一定很热闹吧？", pinyin: "nà ér yí dìng hěn rè nào ba？", vi: "Chỗ đó chắc rất náo nhiệt nhỉ?" },
          { role: "欧文", zh: "很热闹。我家旁边都是商店。", pinyin: "hěn rè nào。 wǒ jiā páng biān dōu shì shāng diàn。", vi: "Rất náo nhiệt. Bên cạnh nhà tớ đều là cửa hàng." },
          { role: "王文丽", zh: "有超市和书店吗？", pinyin: "yǒu chāo shì hé shū diàn ma？", vi: "Có siêu thị và hiệu sách không?" },
          { role: "欧文", zh: "有，我家左边有一家很大的超市，右边有一家新书店，离我家都很近。", pinyin: "yǒu， wǒ jiā zuǒ biān yǒu yī jiā hěn dà de chāo shì， yòu biān yǒu yī jiā xīn shū diàn， lí wǒ jiā dōu hěn jìn。", vi: "Có, bên trái nhà tớ có một siêu thị rất lớn, bên phải có một hiệu sách mới, đều rất gần nhà tớ." },
          { role: "王文丽", zh: "生活很方便。", pinyin: "shēng huó hěn fāng biàn。", vi: "Cuộc sống rất tiện lợi." },
          { role: "欧文", zh: "对，我妈妈每天都去超市买东西，我常常去书店看看。", pinyin: "duì， wǒ mā mā měi tiān dōu qù chāo shì mǎi dōng xī， wǒ cháng cháng qù shū diàn kàn kàn。", vi: "Đúng vậy, mẹ tớ ngày nào cũng đi siêu thị mua đồ, tớ thường đi hiệu sách xem qua." },
          { role: "王文丽", zh: "你家附近交通怎么样？", pinyin: "nǐ jiā fù jìn jiāo tōng zěn me yàng？", vi: "Giao thông gần nhà cậu thế nào?" },
          { role: "欧文", zh: "有地铁站，也有公交车站，十分方便。你看，这是我家附近的照片。", pinyin: "yǒu dì tiě zhàn， yě yǒu gōng jiāo chē zhàn， shí fēn fāng biàn。 nǐ kàn， zhè shì wǒ jiā fù jìn de zhào piān。", vi: "Có ga tàu điện ngầm, cũng có bến xe buýt, rất tiện. Cậu xem này, đây là ảnh khu vực gần nhà tớ." },
          { role: "王文丽", zh: "给我看看。", pinyin: "gěi wǒ kàn kàn。", vi: "Cho tớ xem nào." },
        ],
      },

      // ===== Bài 2 =====
      {
        id: "b3-2-1",
        baiNumber: 2,
        baiTitleZh: "一充值就能打电话",
        baiTitleVi: "Nạp tiền là có thể gọi điện thoại",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "高小明", zh: "海伦，这是你的新手机？", pinyin: "hǎi lún， zhè shì nǐ de xīn shǒu jī？", vi: "Helen, đây là điện thoại mới của cậu à?" },
          { role: "海伦", zh: "对，是我刚刚买的。小明，给我介绍一下怎么用，好吗？", pinyin: "duì， shì wǒ gāng gāng mǎi de。 xiǎo míng， gěi wǒ jiè shào yī xià zěn me yòng， hǎo ma？", vi: "Đúng vậy, tớ vừa mua. Tiểu Minh, giới thiệu cho tớ cách dùng được không?" },
          { role: "高小明", zh: "你得去买一张SIM卡。", pinyin: "nǐ dé qù mǎi yī zhāng SIM kǎ。", vi: "Cậu phải đi mua một cái SIM." },
          { role: "海伦", zh: "去哪儿买？", pinyin: "qù nǎ ér mǎi？", vi: "Mua ở đâu?" },
          { role: "高小明", zh: "卖手机的地方。", pinyin: "mài shǒu jī de dì fāng。", vi: "Nơi bán điện thoại." },
          { role: "海伦", zh: "需要充值吗？", pinyin: "xū yào chōng zhí ma？", vi: "Có cần nạp tiền không?" },
          { role: "高小明", zh: "对。一充值就能打电话。可以买充值卡充值，也可以上网充值。", pinyin: "duì。 yī chōng zhí jiù néng dǎ diàn huà。 kě yǐ mǎi chōng zhí kǎ chōng zhí， yě kě yǐ shàng wǎng chōng zhí。", vi: "Đúng. Nạp tiền là có thể gọi điện. Có thể mua thẻ nạp để nạp, cũng có thể nạp qua mạng." },
          { role: "海伦", zh: "充值卡多少钱一张？", pinyin: "chōng zhí kǎ duō shǎo qián yī zhāng？", vi: "Một thẻ nạp giá bao nhiêu?" },
          { role: "高小明", zh: "有五十块钱和一百块钱的两种。", pinyin: "yǒu wǔ shí kuài qián hé yì bǎi kuài qián de liǎng zhǒng。", vi: "Có hai loại 50 tệ và 100 tệ." },
          { role: "海伦", zh: "我不会充值，你能教我一下吗？", pinyin: "wǒ bú huì chōng zhí， nǐ néng jiào wǒ yī xià ma？", vi: "Tớ không biết nạp, cậu dạy tớ được không?" },
          { role: "高小明", zh: "充值很容易，你打电话公司的服务电话，都有外语服务，不用担心。", pinyin: "chōng zhí hěn róng yì， nǐ dǎ diàn huà gōng sī de fú wù diàn huà， dōu yǒu wài yǔ fú wù， bù yòng dān xīn。", vi: "Nạp rất dễ, cậu gọi tổng đài của công ty viễn thông, đều có dịch vụ tiếng nước ngoài, không cần lo." },
        ],
      },
      {
        id: "b3-2-2",
        baiNumber: 2,
        baiTitleZh: "一充值就能打电话",
        baiTitleVi: "Nạp tiền là có thể gọi điện thoại",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "欧文，你用微信吗？", pinyin: "ōu wén， nǐ yòng wēi xìn ma？", vi: "Owen, cậu dùng WeChat không?" },
          { role: "欧文", zh: "当然用啊，在中国，很多人都用微信。", pinyin: "dāng rán yòng a， zài zhōng guó， hěn duō rén dōu yòng wēi xìn。", vi: "Tất nhiên dùng chứ, ở Trung Quốc, rất nhiều người dùng WeChat." },
          { role: "海伦", zh: "你可以教我一下吗？我还不会用微信。", pinyin: "nǐ kě yǐ jiào wǒ yī xià ma？ wǒ hái bú huì yòng wēi xìn。", vi: "Cậu dạy tớ một chút được không? Tớ vẫn chưa biết dùng WeChat." },
          { role: "欧文", zh: "好啊，很容易。你看，在APP里下一个微信，用你的手机号码注册一下就可以了。", pinyin: "hǎo a， hěn róng yì。 nǐ kàn， zài APP lǐ xià yí gè wēi xìn， yòng nǐ de shǒu jī hào mǎ zhù cè yī xià jiù kě yǐ le。", vi: "Được, dễ thôi. Cậu xem này, vào kho ứng dụng tải WeChat về, đăng ký bằng số di động là xong." },
          { role: "海伦", zh: "太好了。你的微信号是什么？", pinyin: "tài hǎo le。 nǐ de wēi xìn hào shì shén me？", vi: "Tuyệt quá. Mã WeChat của cậu là gì?" },
          { role: "欧文", zh: "这是我的微信号。你会用汉语发微信吗？", pinyin: "zhè shì wǒ de wēi xìn hào。 nǐ huì yòng hàn yǔ fā wēi xìn ma？", vi: "Đây là mã WeChat của tớ. Cậu biết dùng tiếng Hán nhắn WeChat không?" },
          { role: "海伦", zh: "不会，你能不能教我一下？", pinyin: "bú huì， nǐ néng bù néng jiào wǒ yī xià？", vi: "Không biết, cậu dạy tớ được không?" },
          { role: "欧文", zh: "行，手机上有手写输入法，也有拼音输入法。", pinyin: "xíng， shǒu jī shàng yǒu shǒu xiě shū rù fǎ， yě yǒu pīn yīn shū rù fǎ。", vi: "Được, trên điện thoại có bộ gõ viết tay, cũng có bộ gõ pinyin." },
          { role: "海伦", zh: "哪一种容易？", pinyin: "nǎ yī zhǒng róng yì？", vi: "Loại nào dễ hơn?" },
          { role: "欧文", zh: "都很容易，我觉得你应该学习拼音输入法。", pinyin: "dōu hěn róng yì， wǒ jué de nǐ yīng gāi xué xí pīn yīn shū rù fǎ。", vi: "Cả hai đều dễ, tớ nghĩ cậu nên học bộ gõ pinyin." },
        ],
      },

      // ===== Bài 3 =====
      {
        id: "b3-3-1",
        baiNumber: 3,
        baiTitleZh: "这药每天吃几次？",
        baiTitleVi: "Thuốc này mỗi ngày uống mấy lần?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "医生", zh: "你是第一次在中国的医院看病吗？", pinyin: "nǐ shì dì yī cì zài zhōng guó de yī yuàn kàn bìng ma？", vi: "Đây là lần đầu cậu đến khám bệnh ở bệnh viện Trung Quốc à?" },
          { role: "田中", zh: "不，上个月来过一次。", pinyin: "bù， shàng gè yuè lái guò yī cì。", vi: "Không, tháng trước đã đến một lần rồi." },
          { role: "医生", zh: "你哪儿不舒服？", pinyin: "nǐ nǎ ér bù shū fú？", vi: "Cậu thấy chỗ nào khó chịu?" },
          { role: "田中", zh: "我头疼，有点儿发烧。", pinyin: "wǒ tóu téng， yǒu diǎn ér fā shāo。", vi: "Tôi đau đầu, hơi sốt." },
          { role: "医生", zh: "最近感冒过吗？", pinyin: "zuì jìn gǎn mào guò ma？", vi: "Gần đây có bị cảm chưa?" },
          { role: "田中", zh: "上个月感冒过一次。", pinyin: "shàng gè yuè gǎn mào guò yī cì。", vi: "Tháng trước bị cảm một lần." },
          { role: "医生", zh: "量量体温吧。", pinyin: "liàng liáng tǐ wēn ba。", vi: "Đo nhiệt độ xem nào." },
          { role: "田中", zh: "体温高吗？", pinyin: "tǐ wēn gāo ma？", vi: "Nhiệt độ có cao không ạ?" },
          { role: "医生", zh: "三十九度五，很高。", pinyin: "sān shí jiǔ dù wǔ， hěn gāo。", vi: "39.5 độ, rất cao." },
          { role: "田中", zh: "需要打针吗？", pinyin: "xū yào dǎ zhēn ma？", vi: "Có cần tiêm không ạ?" },
          { role: "医生", zh: "要，每天打一次，打三天。", pinyin: "yào， měi tiān dǎ yī cì， dǎ sān tiān。", vi: "Cần, mỗi ngày tiêm một lần, tiêm ba ngày." },
          { role: "田中", zh: "要不要吃药？", pinyin: "yào bù yào chī yào？", vi: "Có cần uống thuốc không ạ?" },
          { role: "医生", zh: "当然要，这是感冒药，每天吃一次。", pinyin: "dāng rán yào， zhè shì gǎn mào yào， měi tiān chī yī cì。", vi: "Tất nhiên cần, đây là thuốc cảm, mỗi ngày uống một lần." },
        ],
      },
      {
        id: "b3-3-2",
        baiNumber: 3,
        baiTitleZh: "这药每天吃几次？",
        baiTitleVi: "Thuốc này mỗi ngày uống mấy lần?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "医生，您好。", pinyin: "yī shēng， nín hǎo。", vi: "Bác sĩ, chào bác sĩ ạ." },
          { role: "医生", zh: "你好！你哪儿不舒服？", pinyin: "nǐ hǎo！ nǐ nǎ ér bù shū fú？", vi: "Chào em! Em thấy chỗ nào khó chịu?" },
          { role: "海伦", zh: "肚子疼，没有胃口，不想吃饭。", pinyin: "dǔ zi téng， méi yǒu wèi kǒu， bù xiǎng chī fàn。", vi: "Đau bụng, không có cảm giác thèm ăn, không muốn ăn cơm." },
          { role: "医生", zh: "拉肚子吗？", pinyin: "lā dù zi ma？", vi: "Có bị tiêu chảy không?" },
          { role: "海伦", zh: "是的，昨天晚上去了四五次洗手间。", pinyin: "shì de， zuó tiān wǎn shàng qù le sì wǔ cì xǐ shǒu jiān。", vi: "Có ạ, tối hôm qua em đi nhà vệ sinh bốn năm lần." },
          { role: "医生", zh: "你昨天吃的东西有没有问题？", pinyin: "nǐ zuó tiān chī de dōng xī yǒu méi yǒu wèn tí？", vi: "Đồ ăn em ăn hôm qua có vấn đề gì không?" },
          { role: "海伦", zh: "我喝的牛奶或者吃的蛋糕不太新鲜。", pinyin: "wǒ hē de niú nǎi huò zhě chī de dàn gāo bù tài xīn xiān。", vi: "Sữa em uống hoặc bánh ngọt em ăn không tươi lắm." },
          { role: "医生", zh: "吃点儿药吧。", pinyin: "chī diǎn ér yào ba。", vi: "Uống một chút thuốc đi." },
          { role: "海伦", zh: "这药每天吃几次？", pinyin: "zhè yào měi tiān chī jǐ cì？", vi: "Thuốc này mỗi ngày uống mấy lần?" },
          { role: "医生", zh: "早上吃一次，中午吃一次，晚上吃一次。", pinyin: "zǎo shàng chī yī cì， zhōng wǔ chī yī cì， wǎn shàng chī yī cì。", vi: "Sáng uống một lần, trưa uống một lần, tối uống một lần." },
          { role: "海伦", zh: "先吃药还是先吃饭？", pinyin: "xiān chī yào hái shì xiān chī fàn？", vi: "Uống thuốc trước hay ăn cơm trước?" },
          { role: "医生", zh: "先吃药。", pinyin: "xiān chī yào。", vi: "Uống thuốc trước." },
          { role: "海伦", zh: "一吃就能好吗？我下午还得上课。", pinyin: "yī chī jiù néng hǎo ma？ wǒ xià wǔ hái dé shàng kè。", vi: "Uống là khỏi luôn được không ạ? Chiều em còn phải đi học." },
          { role: "医生", zh: "你得在家休息，多喝水，不能去上课。", pinyin: "nǐ dé zài jiā xiū xī， duō hē shuǐ， bù néng qù shàng kè。", vi: "Em phải ở nhà nghỉ ngơi, uống nhiều nước, không thể đi học." },
        ],
      },

      // ===== Bài 4 =====
      {
        id: "b3-4-1",
        baiNumber: 4,
        baiTitleZh: "我想请你参加生日聚会",
        baiTitleVi: "Tôi muốn mời bạn tham dự tiệc sinh nhật",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "欧文", zh: "海伦，星期五有空儿吗？", pinyin: "hǎi lún， xīng qī wǔ yǒu kòng er ma？", vi: "Helen, thứ Sáu có rảnh không?" },
          { role: "海伦", zh: "白天还是晚上？晚上我有空儿。", pinyin: "bái tiān hái shì wǎn shàng？ wǎn shàng wǒ yǒu kòng er。", vi: "Ban ngày hay buổi tối? Buổi tối tớ có rảnh." },
          { role: "欧文", zh: "晚上。我想请你参加我的生日聚会。", pinyin: "wǎn shàng。 wǒ xiǎng qǐng nǐ cān jiā wǒ de shēng rì jù huì。", vi: "Buổi tối. Tớ muốn mời cậu tham dự tiệc sinh nhật của tớ." },
          { role: "海伦", zh: "谢谢，我一定参加。参加的同学多吗？", pinyin: "xiè xiè， wǒ yí dìng cān jiā。 cān jiā de tóng xué duō ma？", vi: "Cảm ơn, nhất định tớ sẽ tham dự. Có nhiều bạn tham dự không?" },
          { role: "欧文", zh: "不太多，很多同学周末有约会，不能来参加。", pinyin: "bù tài duō， hěn duō tóng xué zhōu mò yǒu yuē huì， bù néng lái cān jiā。", vi: "Không nhiều lắm, rất nhiều bạn cuối tuần có hẹn, không thể đến tham dự." },
          { role: "海伦", zh: "卡玛拉是我的好朋友。我可以带她一起来吗？", pinyin: "kǎ mǎ lā shì wǒ de hǎo péng yǒu。 wǒ kě yǐ dài tā yì qǐ lái ma？", vi: "Kamala là bạn thân của tớ. Tớ có thể dẫn cậu ấy đến cùng được không?" },
          { role: "欧文", zh: "当然可以，欢迎一起来。", pinyin: "dāng rán kě yǐ， huān yíng yì qǐ lái。", vi: "Tất nhiên là được, hoan nghênh đến cùng." },
          { role: "海伦", zh: "你请了高小明参加吗？", pinyin: "nǐ qǐng le gāo xiǎo míng cān jiā ma？", vi: "Cậu đã mời Cao Tiểu Minh tham dự chưa?" },
          { role: "欧文", zh: "我没请他参加，他感冒了，需要休息。我请了田中参加。你们今天是不是要见面？", pinyin: "wǒ méi qǐng tā cān jiā， tā gǎn mào le， xū yào xiū xī。 wǒ qǐng le tián zhōng cān jiā。 nǐ men jīn tiān shì bú shì yào jiàn miàn？", vi: "Tớ chưa mời cậu ấy tham dự, cậu ấy bị cảm, cần nghỉ ngơi. Tớ đã mời Tanaka. Hôm nay các cậu sẽ gặp nhau phải không?" },
          { role: "海伦", zh: "对，今天下午我们在教室见面。", pinyin: "duì， jīn tiān xià wǔ wǒ men zài jiào shì jiàn miàn。", vi: "Đúng vậy, chiều nay chúng tớ gặp nhau ở phòng học." },
          { role: "欧文", zh: "你让他明天告诉我参加不参加。", pinyin: "nǐ ràng tā míng tiān gào sù wǒ cān jiā bù cān jiā。", vi: "Cậu bảo cậu ấy ngày mai báo cho tớ là có tham dự hay không." },
          { role: "海伦", zh: "好的，我一定告诉他。我叫他给你发短信。", pinyin: "hǎo de， wǒ yí dìng gào sù tā。 wǒ jiào tā gěi nǐ fā duǎn xìn。", vi: "Được, nhất định tớ sẽ nói với cậu ấy. Tớ bảo cậu ấy nhắn tin cho cậu." },
        ],
      },
      {
        id: "b3-4-2",
        baiNumber: 4,
        baiTitleZh: "我想请你参加生日聚会",
        baiTitleVi: "Tôi muốn mời bạn tham dự tiệc sinh nhật",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "小明，朋友请我吃过很多次饭，这次我想请客。", pinyin: "xiǎo míng， péng yǒu qǐng wǒ chī guò hěn duō cì fàn， zhè cì wǒ xiǎng qǐng kè。", vi: "Tiểu Minh, bạn bè đã mời tớ ăn cơm rất nhiều lần, lần này tớ muốn đãi khách." },
          { role: "高小明", zh: "对，这叫礼尚往来。", pinyin: "duì， zhè jiào lǐ shàng wǎng lái。", vi: "Đúng đấy, cái này gọi là 'có qua có lại'." },
          { role: "海伦", zh: "听说北京烤鸭非常有名，我想请朋友吃烤鸭。小明，这里有吃烤鸭的饭店吗？", pinyin: "tīng shuō běi jīng kǎo yā fēi cháng yǒu míng， wǒ xiǎng qǐng péng yǒu chī kǎo yā。 xiǎo míng， zhè lǐ yǒu chī kǎo yā de fàn diàn ma？", vi: "Nghe nói vịt quay Bắc Kinh rất nổi tiếng, tớ muốn mời bạn ăn vịt quay. Tiểu Minh, ở đây có nhà hàng vịt quay không?" },
          { role: "高小明", zh: "我想想。对了，我家附近有一家，又好吃又便宜。", pinyin: "wǒ xiǎng xiǎng。 duì le， wǒ jiā fù jìn yǒu yī jiā， yòu hǎo chī yòu pián yi。", vi: "Để tớ nghĩ xem. À, gần nhà tớ có một quán, vừa ngon vừa rẻ." },
          { role: "海伦", zh: "那一定很有人气，是不是需要预约？", pinyin: "nà yí dìng hěn yǒu rén qì， shì bú shì xū yào yù yuē？", vi: "Vậy chắc rất đông khách, có cần đặt chỗ không?" },
          { role: "高小明", zh: "我也不清楚，打电话问一下吧。你打算请几个客人吃饭呢？", pinyin: "wǒ yě bù qīng chǔ， dǎ diàn huà wèn yī xià ba。 nǐ dǎ suàn qǐng jǐ gè kè rén chī fàn ne？", vi: "Tớ cũng không rõ, gọi điện hỏi thử xem. Cậu định mời mấy người ăn cơm?" },
          { role: "海伦", zh: "我想请的客人有两个，一个客人你认识。", pinyin: "wǒ xiǎng qǐng de kè rén yǒu liǎng gè， yí gè kè rén nǐ rèn shí。", vi: "Tớ muốn mời hai vị khách, một người cậu quen biết." },
          { role: "高小明", zh: "我认识你请的客人？", pinyin: "wǒ rèn shí nǐ qǐng de kè rén？", vi: "Tớ quen khách mà cậu mời sao?" },
          { role: "海伦", zh: "他姓高，叫高小明。", pinyin: "tā xìng gāo， jiào gāo xiǎo míng。", vi: "Anh ấy họ Cao, tên là Cao Tiểu Minh." },
          { role: "高小明", zh: "海伦，你太客气了，我们是老朋友，这次AA制吧。", pinyin: "hǎi lún， nǐ tài kè qì le， wǒ men shì lǎo péng yǒu， zhè cì AA zhì ba。", vi: "Helen, cậu khách sáo quá, chúng ta là bạn cũ, lần này chia đôi tiền đi." },
          { role: "海伦", zh: "我不是客气，这是不是叫礼尚往来？", pinyin: "wǒ bú shì kè qì， zhè shì bú shì jiào lǐ shàng wǎng lái？", vi: "Tớ không phải khách sáo, đây có gọi là 'có qua có lại' không?" },
          { role: "高小明", zh: "还有一个人是谁？是不是你的语伴？", pinyin: "hái yǒu yí gè rén shì shuí？ shì bú shì nǐ de yǔ bàn？", vi: "Còn một người nữa là ai? Có phải bạn học ngôn ngữ của cậu không?" },
          { role: "海伦", zh: "对！我马上给饭店打电话预约。", pinyin: "duì！ wǒ mǎ shàng gěi fàn diàn dǎ diàn huà yù yuē。", vi: "Đúng! Tớ sẽ gọi điện đặt bàn ngay." },
        ],
      },

      // ===== Bài 5 =====
      {
        id: "b3-5-1",
        baiNumber: 5,
        baiTitleZh: "现在，我有很多中国朋友了",
        baiTitleVi: "Bây giờ, tôi đã có rất nhiều bạn Trung Quốc",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "欧文，你在中国生活已经习惯了吗？", pinyin: "ōu wén， nǐ zài zhōng guó shēng huó yǐ jīng xí guàn le ma？", vi: "Owen, cậu đã quen với cuộc sống ở Trung Quốc chưa?" },
          { role: "欧文", zh: "我觉得还是不太习惯。", pinyin: "wǒ jué de hái shì bù tài xí guàn。", vi: "Tớ vẫn thấy chưa quen lắm." },
          { role: "海伦", zh: "来中国以前，你会骑自行车吗？", pinyin: "lái zhōng guó yǐ qián， nǐ huì qí zì xíng chē ma？", vi: "Trước khi đến Trung Quốc, cậu biết đi xe đạp không?" },
          { role: "欧文", zh: "不会，但是在这里骑自行车很方便，所以我请中国朋友教我，现在已经会骑自行车了。", pinyin: "bú huì， dàn shì zài zhè lǐ qí zì xíng chē hěn fāng biàn， suǒ yǐ wǒ qǐng zhōng guó péng yǒu jiào wǒ， xiàn zài yǐ jīng huì qí zì xíng chē le。", vi: "Không biết, nhưng ở đây đi xe đạp rất tiện, nên tớ nhờ bạn Trung Quốc dạy, giờ đã biết đi rồi." },
          { role: "海伦", zh: "刚来中国的时候，你知道怎么坐公交车吗？", pinyin: "gāng lái zhōng guó de shí hòu， nǐ zhī dào zěn me zuò gōng jiāo chē ma？", vi: "Khi mới đến Trung Quốc, cậu biết đi xe buýt thế nào không?" },
          { role: "欧文", zh: "不知道，但是我现在会坐公交车了，也会坐地铁了。", pinyin: "bù zhī dào， dàn shì wǒ xiàn zài huì zuò gōng jiāo chē le， yě huì zuò dì tiě le。", vi: "Không biết, nhưng giờ tớ đã biết đi xe buýt, cũng biết đi tàu điện ngầm rồi." },
          { role: "海伦", zh: "刚来中国的时候，你会买东西吗？", pinyin: "gāng lái zhōng guó de shí hòu， nǐ huì mǎi dōng xī ma？", vi: "Khi mới đến Trung Quốc, cậu biết mua đồ không?" },
          { role: "欧文", zh: "不会，但是现在我可以一个人去超市、商店买东西了，也会讨价还价了。", pinyin: "bú huì， dàn shì xiàn zài wǒ kě yǐ yí gè rén qù chāo shì、 shāng diàn mǎi dōng xī le， yě huì tǎo jià huán jià le。", vi: "Không biết, nhưng giờ tớ có thể một mình đi siêu thị, cửa hàng mua đồ rồi, cũng biết mặc cả nữa." },
          { role: "海伦", zh: "来中国以前，你常常运动吗？", pinyin: "lái zhōng guó yǐ qián， nǐ cháng cháng yùn dòng ma？", vi: "Trước khi đến Trung Quốc, cậu có thường tập thể dục không?" },
          { role: "欧文", zh: "对，我每天跑步。来中国以后，学习很忙，不经常跑步了，越来越胖了。", pinyin: "duì， wǒ měi tiān pǎo bù。 lái zhōng guó yǐ hòu， xué xí hěn máng， bù jīng cháng pǎo bù le， yuè lái yuè pàng le。", vi: "Có, mỗi ngày tớ đều chạy bộ. Sau khi đến Trung Quốc, học tập bận lắm, không thường xuyên chạy bộ nữa, càng ngày càng béo." },
          { role: "海伦", zh: "你的好习惯没有了，胖了，我的坏习惯没有了，瘦了。", pinyin: "nǐ de hǎo xí guàn méi yǒu le， pàng le， wǒ de huài xí guàn méi yǒu le， shòu le。", vi: "Thói quen tốt của cậu mất rồi, béo lên, thói quen xấu của tớ mất rồi, gầy đi." },
          { role: "欧文", zh: "海伦，你有什么坏习惯？", pinyin: "hǎi lún， nǐ yǒu shén me huài xí guàn？", vi: "Helen, cậu có thói quen xấu gì?" },
          { role: "海伦", zh: "来中国以前，我最喜欢睡懒觉。现在我要努力学习，不能睡懒觉了。", pinyin: "lái zhōng guó yǐ qián， wǒ zuì xǐ huān shuì lǎn jiào。 xiàn zài wǒ yào nǔ lì xué xí， bù néng shuì lǎn jiào le。", vi: "Trước khi đến Trung Quốc, tớ rất thích ngủ nướng. Giờ tớ phải cố gắng học, không thể ngủ nướng được nữa." },
        ],
      },
      {
        id: "b3-5-2",
        baiNumber: 5,
        baiTitleZh: "现在，我有很多中国朋友了",
        baiTitleVi: "Bây giờ, tôi đã có rất nhiều bạn Trung Quốc",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "海伦，来中国以后，你的汉语进步大吗？", pinyin: "ōu wén， lái zhōng guó yǐ hòu， nǐ de hàn yǔ jìn bù dà ma？", vi: "Helen, từ khi đến Trung Quốc, tiếng Hán của cậu tiến bộ nhiều không?" },
          { role: "海伦", zh: "来中国以前，我没学过汉语，现在会说很多汉语了。", pinyin: "lái zhōng guó yǐ qián， wǒ méi xué guò hàn yǔ， xiàn zài huì shuō hěn duō hàn yǔ le。", vi: "Trước khi đến Trung Quốc, tớ chưa học tiếng Hán, giờ đã biết nói rất nhiều rồi." },
          { role: "欧文", zh: "写呢？", pinyin: "xiě ne？", vi: "Viết thì sao?" },
          { role: "海伦", zh: "刚来的时候不会写汉字，现在会写很多汉字了。", pinyin: "gāng lái de shí hòu bú huì xiě hàn zì， xiàn zài huì xiě hěn duō hàn zì le。", vi: "Mới đến thì không biết viết chữ Hán, giờ đã biết viết rất nhiều chữ rồi." },
          { role: "欧文", zh: "以前你了解中国吗？", pinyin: "yǐ qián nǐ liǎo jiě zhōng guó ma？", vi: "Trước đây cậu có hiểu về Trung Quốc không?" },
          { role: "海伦", zh: "不了解，来中国以后，慢慢了解了。", pinyin: "bù liǎo jiě， lái zhōng guó yǐ hòu， màn màn liǎo jiě le。", vi: "Không hiểu, sau khi đến Trung Quốc, từ từ hiểu ra." },
          { role: "欧文", zh: "来中国以前，你有中国朋友吗？", pinyin: "lái zhōng guó yǐ qián， nǐ yǒu zhōng guó péng yǒu ma？", vi: "Trước khi đến Trung Quốc, cậu có bạn Trung Quốc không?" },
          { role: "海伦", zh: "只有一个。现在，我有很多中国朋友了。欧文，你呢？", pinyin: "zhǐ yǒu yí gè。 xiàn zài， wǒ yǒu hěn duō zhōng guó péng yǒu le。 ōu wén， nǐ ne？", vi: "Chỉ có một. Giờ thì tớ có rất nhiều bạn Trung Quốc rồi. Owen, còn cậu?" },
          { role: "欧文", zh: "我以前没有，现在也没有。以后呢，你给我介绍介绍吧。", pinyin: "wǒ yǐ qián méi yǒu， xiàn zài yě méi yǒu。 yǐ hòu ne， nǐ gěi wǒ jiè shào jiè shào ba。", vi: "Trước đây tớ không có, giờ cũng không có. Sau này, cậu giới thiệu cho tớ nhé." },
          { role: "海伦", zh: "行，你请我喝一次咖啡，我给你介绍一个。", pinyin: "xíng， nǐ qǐng wǒ hē yī cì kā fēi， wǒ gěi nǐ jiè shào yí gè。", vi: "Được, cậu mời tớ uống một lần cà phê, tớ sẽ giới thiệu cho cậu một người." },
          { role: "欧文", zh: "那我每天请你喝。", pinyin: "nà wǒ měi tiān qǐng nǐ hē。", vi: "Vậy ngày nào tớ cũng mời cậu uống." },
        ],
      },

      // ===== Bài 6 =====
      {
        id: "b3-6-1",
        baiNumber: 6,
        baiTitleZh: "她说汉语说得怎么样？",
        baiTitleVi: "Cô ấy nói tiếng Hán thế nào?",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "高小明", zh: "卡玛拉，你有同屋吧，介绍介绍你的同屋，好吗？", pinyin: "kǎ mǎ lā， nǐ yǒu tóng wū ba， jiè shào jiè shào nǐ de tóng wū， hǎo ma？", vi: "Kamala, cậu có bạn cùng phòng phải không, giới thiệu cho tớ về bạn cùng phòng của cậu, được không?" },
          { role: "卡玛拉", zh: "我同屋是英国人，叫海伦。她喜欢唱歌，中文歌唱得非常好，还喜欢踢足球，不过，球踢得不太好。", pinyin: "wǒ tóng wū shì yīng guó rén， jiào hǎi lún。 tā xǐ huān chàng gē， zhōng wén gē chàng dé fēi cháng hǎo， hái xǐ huān tī zú qiú， bù guò， qiú tī dé bù tài hǎo。", vi: "Bạn cùng phòng của tớ là người Anh, tên Helen. Cô ấy thích hát, hát tiếng Trung rất hay, còn thích đá bóng, nhưng đá bóng không giỏi lắm." },
          { role: "高小明", zh: "她说汉语说得怎么样？", pinyin: "tā shuō hàn yǔ shuō dé zěn me yàng？", vi: "Cô ấy nói tiếng Hán thế nào?" },
          { role: "卡玛拉", zh: "说得比较好，她还会说一点儿日语。", pinyin: "shuō dé bǐ jiào hǎo， tā hái huì shuō yì diǎn ér rì yǔ。", vi: "Nói khá tốt, cô ấy còn biết một chút tiếng Nhật." },
          { role: "高小明", zh: "她长什么样子？", pinyin: "tā zhǎng shén me yàng zi？", vi: "Cô ấy trông thế nào?" },
          { role: "卡玛拉", zh: "她个子高高的，眼睛大大的，皮肤白白的，头发长长的，黄黄的，长得非常漂亮。", pinyin: "tā gè zi gāo gāo de， yǎn jīng dà dà de， pí fū bái bái de， tóu fà cháng cháng de， huáng huáng de， zhǎng dé fēi cháng piào liàng。", vi: "Cô ấy cao cao, mắt to to, da trắng trắng, tóc dài dài, vàng vàng, trông rất xinh." },
          { role: "高小明", zh: "她平时忙不忙？", pinyin: "tā píng shí máng bù máng？", vi: "Ngày thường cô ấy có bận không?" },
          { role: "卡玛拉", zh: "小明，你问得很详细啊，想给她介绍男朋友吗？", pinyin: "xiǎo míng， nǐ wèn dé hěn xiáng xì a， xiǎng gěi tā jiè shào nán péng yǒu ma？", vi: "Tiểu Minh, cậu hỏi kỹ thế, muốn giới thiệu bạn trai cho cô ấy à?" },
          { role: "高小明", zh: "不，我想给她介绍一个语伴。", pinyin: "bù， wǒ xiǎng gěi tā jiè shào yí gè yǔ bàn。", vi: "Không, tớ muốn giới thiệu cho cô ấy một bạn học ngôn ngữ." },
          { role: "卡玛拉", zh: "太巧了，她正想找一个语伴呢。", pinyin: "tài qiǎo le， tā zhèng xiǎng zhǎo yí gè yǔ bàn ne。", vi: "Vừa khéo, cô ấy đang muốn tìm một bạn học ngôn ngữ." },
        ],
      },
      {
        id: "b3-6-2",
        baiNumber: 6,
        baiTitleZh: "她说汉语说得怎么样？",
        baiTitleVi: "Cô ấy nói tiếng Hán thế nào?",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "卡玛拉，你今天怎么回来得这么晚？", pinyin: "kǎ mǎ lā， nǐ jīn tiān zěn me huí lái de zhè me wǎn？", vi: "Kamala, sao hôm nay cậu về muộn thế?" },
          { role: "卡玛拉", zh: "我去超市了。", pinyin: "wǒ qù chāo shì le。", vi: "Tớ đi siêu thị." },
          { role: "海伦", zh: "刚才，一个中国男同学来找过你。", pinyin: "gāng cái， yí gè zhōng guó nán tóng xué lái zhǎo guò nǐ。", vi: "Vừa nãy, một bạn nam Trung Quốc đến tìm cậu." },
          { role: "卡玛拉", zh: "他长什么样子？", pinyin: "tā zhǎng shén me yàng zi？", vi: "Cậu ấy trông thế nào?" },
          { role: "海伦", zh: "他穿了一件T恤，个子矮矮的，头发黑黑的，有点儿胖，长得比较帅。", pinyin: "tā chuān le yī jiàn T xù， gè zi ǎi ǎi de， tóu fà hēi hēi de， yǒu diǎn ér pàng， zhǎng dé bǐ jiào shuài。", vi: "Cậu ấy mặc áo phông, người thấp thấp, tóc đen đen, hơi mập, trông khá đẹp trai." },
          { role: "卡玛拉", zh: "他会说英语吗？", pinyin: "tā huì shuō yīng yǔ ma？", vi: "Cậu ấy biết nói tiếng Anh không?" },
          { role: "海伦", zh: "他说英语说得非常好，不过，说得比较慢。", pinyin: "tā shuō yīng yǔ shuō dé fēi cháng hǎo， bù guò， shuō dé bǐ jiào màn。", vi: "Cậu ấy nói tiếng Anh rất hay, có điều, nói khá chậm." },
          { role: "卡玛拉", zh: "我知道了，他是我的中国朋友高小明。", pinyin: "wǒ zhī dào le， tā shì wǒ de zhōng guó péng yǒu gāo xiǎo míng。", vi: "Tớ biết rồi, đó là bạn Trung Quốc của tớ - Cao Tiểu Minh." },
          { role: "海伦", zh: "他知道我的名字，还知道我是你的同屋。", pinyin: "tā zhī dào wǒ de míng zì， hái zhī dào wǒ shì nǐ de tóng wū。", vi: "Cậu ấy biết tên tớ, còn biết tớ là bạn cùng phòng của cậu." },
          { role: "卡玛拉", zh: "我给他介绍过你。他想给你介绍一个语伴。", pinyin: "wǒ gěi tā jiè shào guò nǐ。 tā xiǎng gěi nǐ jiè shào yí gè yǔ bàn。", vi: "Tớ đã giới thiệu cậu cho cậu ấy. Cậu ấy muốn giới thiệu cho cậu một bạn học ngôn ngữ." },
          { role: "海伦", zh: "真不巧，我昨天已经找了一个，你说得太晚了。", pinyin: "zhēn bù qiǎo， wǒ zuó tiān yǐ jīng zhǎo le yí gè， nǐ shuō dé tài wǎn le。", vi: "Tiếc thật, hôm qua tớ đã tìm được một người rồi, cậu nói muộn quá." },
        ],
      },

      // ===== Bài 7 =====
      {
        id: "b3-7-1",
        baiNumber: 7,
        baiTitleZh: "公交车过来了，我们上车吧",
        baiTitleVi: "Xe buýt đến rồi, chúng mình lên xe đi",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "海伦", zh: "现在中国很多城市都有地铁。小明，这里的地铁怎么坐？", pinyin: "xiàn zài zhōng guó hěn duō chéng shì dōu yǒu dì tiě。 xiǎo míng， zhè lǐ de dì tiě zěn me zuò？", vi: "Bây giờ nhiều thành phố Trung Quốc đều có tàu điện ngầm. Tiểu Minh, tàu điện ngầm ở đây đi thế nào?" },
          { role: "高小明", zh: "你去年就来了，还没有坐过？", pinyin: "nǐ qù nián jiù lái le， hái méi yǒu zuò guò？", vi: "Cậu đến từ năm ngoái rồi, vẫn chưa đi bao giờ à?" },
          { role: "海伦", zh: "没有，我出去的时候一般都打的。", pinyin: "méi yǒu， wǒ chū qù de shí hòu yì bān dōu dǎ dī。", vi: "Chưa, khi tớ đi ra ngoài thường bắt taxi." },
          { role: "高小明", zh: "你有公交卡吗？进去的时候刷一下。", pinyin: "nǐ yǒu gōng jiāo kǎ ma？ jìn qù de shí hòu shuā yī xià。", vi: "Cậu có thẻ giao thông không? Khi vào quẹt một cái." },
          { role: "海伦", zh: "没有公交卡怎么办？", pinyin: "méi yǒu gōng jiāo kǎ zěn me bàn？", vi: "Nếu không có thẻ giao thông thì làm sao?" },
          { role: "高小明", zh: "进去以前需要买票。入口附近一般有自动售票机，一投入硬币，票就出来了。进去的时候刷一下票。", pinyin: "jìn qù yǐ qián xū yào mǎi piào。 rù kǒu fù jìn yì bān yǒu zì dòng shòu piào jī， yī tóu rù yìng bì， piào jiù chū lái le。 jìn qù de shí hòu shuā yī xià piào。", vi: "Trước khi vào cần mua vé. Gần cửa vào thường có máy bán vé tự động, vừa bỏ đồng xu vào là vé ra ngay. Khi vào thì quẹt vé." },
          { role: "海伦", zh: "出来的时候，还需要刷卡吗？", pinyin: "chū lái de shí hòu， hái xū yào shuā kǎ ma？", vi: "Khi ra có cần quẹt thẻ nữa không?" },
          { role: "高小明", zh: "还需要刷一次，或者投入地铁票。", pinyin: "hái xū yào shuā yī cì， huò zhě tóu rù dì tiě piào。", vi: "Vẫn cần quẹt một lần nữa, hoặc bỏ vé vào." },
          { role: "海伦", zh: "每个地铁站都有自动扶梯或者电梯吗？", pinyin: "měi gè dì tiě zhàn dōu yǒu zì dòng fú tī huò zhě diàn tī ma？", vi: "Mỗi ga tàu điện đều có thang cuốn hoặc thang máy không?" },
          { role: "高小明", zh: "不一定，有的地铁站有，有的地铁站没有。我家附近的地铁站，上去有自动扶梯，下来没有。", pinyin: "bù yí dìng， yǒu de dì tiě zhàn yǒu， yǒu de dì tiě zhàn méi yǒu。 wǒ jiā fù jìn de dì tiě zhàn， shàng qù yǒu zì dòng fú tī， xià lái méi yǒu。", vi: "Không nhất định, có ga có, có ga không. Ga gần nhà tớ, lên thì có thang cuốn, xuống thì không có." },
          { role: "海伦", zh: "年轻人可能没有问题，老人下去很累吧？", pinyin: "nián qīng rén kě néng méi yǒu wèn tí， lǎo rén xià qù hěn lèi ba？", vi: "Người trẻ chắc không sao, người già đi xuống mệt lắm nhỉ?" },
          { role: "高小明", zh: "是啊，老人下去会很累。", pinyin: "shì a， lǎo rén xià qù huì hěn lèi。", vi: "Đúng vậy, người già đi xuống sẽ rất mệt." },
        ],
      },
      {
        id: "b3-7-2",
        baiNumber: 7,
        baiTitleZh: "公交车过来了，我们上车吧",
        baiTitleVi: "Xe buýt đến rồi, chúng mình lên xe đi",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "高小明", zh: "卡玛拉，你是第一次在中国坐公交车吧。", pinyin: "kǎ mǎ lā， nǐ shì dì yī cì zài zhōng guó zuò gōng jiāo chē ba。", vi: "Kamala, đây là lần đầu cậu đi xe buýt ở Trung Quốc đúng không." },
          { role: "卡玛拉", zh: "是的。小明，在中国坐公交车怎么买票？", pinyin: "shì de。 xiǎo míng， zài zhōng guó zuò gōng jiāo chē zěn me mǎi piào？", vi: "Đúng vậy. Tiểu Minh, ở Trung Quốc đi xe buýt mua vé thế nào?" },
          { role: "高小明", zh: "一般从前门上车，上去以后，刷公交卡或者投币都可以。", pinyin: "yì bān cóng qián mén shàng chē， shàng qù yǐ hòu， shuā gōng jiāo kǎ huò zhě tóu bì dōu kě yǐ。", vi: "Thường lên xe ở cửa trước, lên xe xong, quẹt thẻ giao thông hoặc bỏ xu đều được." },
          { role: "卡玛拉", zh: "我没有公交卡，得准备硬币。", pinyin: "wǒ méi yǒu gōng jiāo kǎ， dé zhǔn bèi yìng bì。", vi: "Tớ không có thẻ giao thông, phải chuẩn bị đồng xu." },
          { role: "高小明", zh: "车过来了，我们上车吧。", pinyin: "chē guò lái le， wǒ men shàng chē ba。", vi: "Xe đến rồi, chúng mình lên xe đi." },
          { role: "高小明", zh: "我们在第五站下车。门口人很多，往里走一点儿吧。", pinyin: "wǒ men zài dì wǔ zhàn xià chē。 mén kǒu rén hěn duō， wǎng lǐ zǒu yì diǎn ér ba。", vi: "Chúng ta xuống ở trạm thứ năm. Cửa đông người quá, đi vào trong một chút đi." },
          { role: "卡玛拉", zh: "好的，里面的人比较少。", pinyin: "hǎo de， lǐ miàn de rén bǐ jiào shǎo。", vi: "Được, bên trong ít người hơn." },
          { role: "高小明", zh: "车开得真快，现在是第四站了，准备下去吧。", pinyin: "chē kāi dé zhēn kuài， xiàn zài shì dì sì zhàn le， zhǔn bèi xià qù ba。", vi: "Xe chạy nhanh thật, bây giờ đã là trạm thứ tư rồi, chuẩn bị xuống đi." },
          { role: "卡玛拉", zh: "这么早就准备？", pinyin: "zhè me zǎo jiù zhǔn bèi？", vi: "Sớm thế đã chuẩn bị?" },
          { role: "高小明", zh: "对，应该从后门下去，我们去那边吧，下去的时候方便。", pinyin: "duì， yīng gāi cóng hòu mén xià qù， wǒ men qù nà biān ba， xià qù de shí hòu fāng biàn。", vi: "Đúng, phải xuống ở cửa sau, chúng ta sang bên kia đi, lúc xuống cho tiện." },
          { role: "卡玛拉", zh: "现在就过去吗？太挤了。", pinyin: "xiàn zài jiù guò qù ma？ tài jǐ le。", vi: "Bây giờ đi qua à? Chen chúc quá." },
          { role: "高小明", zh: "慢慢过去吧。", pinyin: "màn màn guò qù ba。", vi: "Từ từ đi qua đi." },
        ],
      },

      // ===== Bài 8 =====
      {
        id: "b3-8-1",
        baiNumber: 8,
        baiTitleZh: "我教你汉语，你教我英语",
        baiTitleVi: "Tôi dạy bạn tiếng Hán, bạn dạy tôi tiếng Anh",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "欧文", zh: "文丽，能不能给我找一个汉语家教，请他教我汉语？", pinyin: "wén lì， néng bù néng gěi wǒ zhǎo yí gè hàn yǔ jiā jiào， qǐng tā jiào wǒ hàn yǔ？", vi: "Văn Lệ, có thể tìm cho tớ một gia sư tiếng Hán, để dạy tớ tiếng Hán không?" },
          { role: "王文丽", zh: "好啊。欧文，你准备给他多少学费？", pinyin: "hǎo a。 ōu wén， nǐ zhǔn bèi gěi tā duō shǎo xué fèi？", vi: "Được. Owen, cậu định trả cho bạn ấy bao nhiêu học phí?" },
          { role: "欧文", zh: "我教他英语，我不给他学费，他也不用给我学费。", pinyin: "wǒ jiào tā yīng yǔ， wǒ bù gěi tā xué fèi， tā yě bù yòng gěi wǒ xué fèi。", vi: "Tớ dạy bạn ấy tiếng Anh, tớ không trả học phí cho bạn ấy, bạn ấy cũng không cần trả học phí cho tớ." },
          { role: "王文丽", zh: "你是想找语伴啊？", pinyin: "nǐ shì xiǎng zhǎo yǔ bàn a？", vi: "Cậu muốn tìm bạn học ngôn ngữ à?" },
          { role: "欧文", zh: "语伴是什么意思？", pinyin: "yǔ bàn shì shén me yì si？", vi: "Bạn học ngôn ngữ là gì?" },
          { role: "王文丽", zh: "就是互相学习的朋友。", pinyin: "jiù shì hù xiāng xué xí de péng yǒu。", vi: "Là bạn cùng học hỏi lẫn nhau." },
          { role: "欧文", zh: "对，你能给我介绍一个吗？", pinyin: "duì， nǐ néng gěi wǒ jiè shào yí gè ma？", vi: "Đúng, cậu giới thiệu cho tớ một người được không?" },
          { role: "王文丽", zh: "你有什么要求吗？说得详细一点儿。", pinyin: "nǐ yǒu shén me yāo qiú ma？ shuō dé xiáng xì yì diǎn ér。", vi: "Cậu có yêu cầu gì không? Nói chi tiết một chút." },
          { role: "欧文", zh: "语伴应该会说英语，每星期学习三次。", pinyin: "yǔ bàn yīng gāi huì shuō yīng yǔ， měi xīng qī xué xí sān cì。", vi: "Bạn học ngôn ngữ phải biết nói tiếng Anh, mỗi tuần học ba lần." },
          { role: "王文丽", zh: "要男生还是女生？", pinyin: "yào nán shēng huán shì nǚ shēng？", vi: "Cần con trai hay con gái?" },
          { role: "欧文", zh: "都行，普通话应该说得标准。", pinyin: "dōu xíng， pǔ tōng huà yīng gāi shuō dé biāo zhǔn。", vi: "Đều được, tiếng phổ thông phải nói chuẩn." },
          { role: "王文丽", zh: "我问问我的同学，明天告诉你结果。", pinyin: "wǒ wèn wèn wǒ de tóng xué， míng tiān gào sù nǐ jié guǒ。", vi: "Tớ hỏi bạn cùng lớp xem, mai báo kết quả cho cậu." },
        ],
      },
      {
        id: "b3-8-2",
        baiNumber: 8,
        baiTitleZh: "我教你汉语，你教我英语",
        baiTitleVi: "Tôi dạy bạn tiếng Hán, bạn dạy tôi tiếng Anh",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "我想请一个老师教我拉二胡，文丽，你能帮我找一个吗？", pinyin: "wǒ xiǎng qǐng yí gè lǎo shī jiào wǒ lā èr hú， wén lì， nǐ néng bāng wǒ zhǎo yí gè ma？", vi: "Tớ muốn mời một thầy dạy tớ kéo nhị hồ, Văn Lệ, cậu có thể giúp tớ tìm một người được không?" },
          { role: "王文丽", zh: "你想找一个二胡家教吗？", pinyin: "nǐ xiǎng zhǎo yí gè èr hú jiā jiào ma？", vi: "Cậu muốn tìm một gia sư nhị hồ?" },
          { role: "欧文", zh: "对，我给他学费。", pinyin: "duì， wǒ gěi tā xué fèi。", vi: "Đúng, tớ sẽ trả học phí cho thầy." },
          { role: "王文丽", zh: "欧文，你对拉二胡感兴趣？", pinyin: "ōu wén， nǐ duì lā èr hú gǎn xìng qù？", vi: "Owen, cậu hứng thú với việc kéo nhị hồ à?" },
          { role: "欧文", zh: "对，上个星期我听了二胡演奏，觉得特别好听。上一次课要付多少钱？", pinyin: "duì， shàng gè xīng qī wǒ tīng le èr hú yǎn zòu， jué de tè bié hǎo tīng。 shàng yī cì kè yào fù duō shǎo qián？", vi: "Đúng, tuần trước tớ nghe biểu diễn nhị hồ, thấy rất hay. Một buổi học phải trả bao nhiêu tiền?" },
          { role: "王文丽", zh: "一个小时三百块左右。你有二胡吗？", pinyin: "yí gè xiǎo shí sān bǎi kuài zuǒ yòu。 nǐ yǒu èr hú ma？", vi: "Một tiếng khoảng 300 tệ. Cậu có nhị hồ không?" },
          { role: "欧文", zh: "我的朋友送了我一把二胡，是给我的生日礼物。", pinyin: "wǒ de péng yǒu sòng le wǒ yī bǎ èr hú， shì gěi wǒ de shēng rì lǐ wù。", vi: "Bạn tớ tặng tớ một cây nhị hồ, là quà sinh nhật của tớ." },
          { role: "王文丽", zh: "你的朋友会拉二胡吗？", pinyin: "nǐ de péng yǒu huì lā èr hú ma？", vi: "Bạn cậu có biết kéo nhị hồ không?" },
          { role: "欧文", zh: "会，他拉得非常好，但是他工作太忙了，没有时间教我。", pinyin: "huì， tā lā dé fēi cháng hǎo， dàn shì tā gōng zuò tài máng le， méi yǒu shí jiān jiào wǒ。", vi: "Có, cậu ấy kéo rất hay, nhưng công việc bận quá, không có thời gian dạy tớ." },
          { role: "王文丽", zh: "太遗憾了。我爸爸的熟人会拉二胡，我让我爸爸问一下。", pinyin: "tài yí hàn le。 wǒ bà bà de shú rén huì lā èr hú， wǒ ràng wǒ bà bà wèn yī xià。", vi: "Tiếc quá. Người quen của bố tớ biết kéo nhị hồ, để tớ bảo bố hỏi thử." },
          { role: "欧文", zh: "等你的好消息。", pinyin: "děng nǐ de hǎo xiāo xī。", vi: "Đợi tin vui từ cậu." },
          { role: "王文丽", zh: "好的，一有消息就告诉你。", pinyin: "hǎo de， yī yǒu xiāo xī jiù gào sù nǐ。", vi: "Được, có tin là báo cho cậu ngay." },
        ],
      },

      // ===== Bài 9 =====
      {
        id: "b3-9-1",
        baiNumber: 9,
        baiTitleZh: "这里的夏天比我老家热",
        baiTitleVi: "Mùa hè ở đây nóng hơn ở quê tôi",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "卡玛拉", zh: "田中，日本的天气跟这里一样吗？", pinyin: "tián zhōng， rì běn de tiān qì gēn zhè lǐ yī yàng ma？", vi: "Tanaka, thời tiết Nhật Bản có giống ở đây không?" },
          { role: "田中", zh: "跟这里差不多，夏天热，冬天冷，春天暖和，秋天凉快。", pinyin: "gēn zhè lǐ chà bu duō， xià tiān rè， dōng tiān lěng， chūn tiān nuǎn huo， qiū tiān liáng kuài。", vi: "Khá giống ở đây, mùa hè nóng, mùa đông lạnh, mùa xuân ấm áp, mùa thu mát mẻ." },
          { role: "卡玛拉", zh: "冬天下雪吗？", pinyin: "dōng tiān xià xuě ma？", vi: "Mùa đông có tuyết không?" },
          { role: "田中", zh: "跟这里一样，很多地方下雪。卡玛拉，你的老家天气怎么样？", pinyin: "gēn zhè lǐ yī yàng， hěn duō dì fāng xià xuě。 kǎ mǎ lā， nǐ de lǎo jiā tiān qì zěn me yàng？", vi: "Giống ở đây, nhiều nơi có tuyết. Kamala, thời tiết quê cậu thế nào?" },
          { role: "卡玛拉", zh: "我老家的冬天比这里暖和，夏天没有这里热，春天和秋天跟这里差不多。", pinyin: "wǒ lǎo jiā de dōng tiān bǐ zhè lǐ nuǎn huo， xià tiān méi yǒu zhè lǐ rè， chūn tiān hé qiū tiān gēn zhè lǐ chà bu duō。", vi: "Mùa đông ở quê tớ ấm hơn ở đây, mùa hè không nóng bằng ở đây, mùa xuân và mùa thu khá giống ở đây." },
          { role: "田中", zh: "夏天最高温度有多少？", pinyin: "xià tiān zuì gāo wēn dù yǒu duō shǎo？", vi: "Mùa hè nhiệt độ cao nhất là bao nhiêu?" },
          { role: "卡玛拉", zh: "32度左右，比这里低多了。", pinyin: "32 dù zuǒ yòu， bǐ zhè lǐ dī duō le。", vi: "Khoảng 32 độ, thấp hơn ở đây nhiều." },
          { role: "田中", zh: "冬天最低温度有多少？", pinyin: "dōng tiān zuì dī wēn dù yǒu duō shǎo？", vi: "Mùa đông nhiệt độ thấp nhất là bao nhiêu?" },
          { role: "卡玛拉", zh: "8度左右，没有这里这么冷，不下雪。", pinyin: "8 dù zuǒ yòu， méi yǒu zhè lǐ zhè me lěng， bù xià xuě。", vi: "Khoảng 8 độ, không lạnh như ở đây, không có tuyết." },
          { role: "田中", zh: "冬天不冷，夏天不热，真的是个好地方啊。", pinyin: "dōng tiān bù lěng， xià tiān bù rè， zhēn de shì gè hǎo dì fāng a。", vi: "Mùa đông không lạnh, mùa hè không nóng, đúng là nơi tốt." },
          { role: "卡玛拉", zh: "对，比这里舒服多了。", pinyin: "duì， bǐ zhè lǐ shū fú duō le。", vi: "Đúng vậy, thoải mái hơn ở đây nhiều." },
        ],
      },
      {
        id: "b3-9-2",
        baiNumber: 9,
        baiTitleZh: "这里的夏天比我老家热",
        baiTitleVi: "Mùa hè ở đây nóng hơn ở quê tôi",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "海伦", zh: "这个星期每天都是35度左右，真热啊。欧文你觉得热吗？", pinyin: "zhè ge xīng qī měi tiān dōu shì 35 dù zuǒ yòu， zhēn rè a。 ōu wén nǐ jué de rè ma？", vi: "Tuần này ngày nào cũng khoảng 35 độ, nóng thật. Owen, cậu thấy nóng không?" },
          { role: "欧文", zh: "这里太热了，比我的老家热多了。", pinyin: "zhè lǐ tài rè le， bǐ wǒ de lǎo jiā rè duō le。", vi: "Ở đây nóng quá, nóng hơn quê tớ nhiều." },
          { role: "海伦", zh: "听天气预报说，明天36度。", pinyin: "tīng tiān qì yù bào shuō， míng tiān 36 dù。", vi: "Nghe dự báo thời tiết nói, ngày mai 36 độ." },
          { role: "欧文", zh: "明天比今天更热啊，真的不想出去了。海伦，你的老家怎么样？", pinyin: "míng tiān bǐ jīn tiān gèng rè a， zhēn de bù xiǎng chū qù le。 hǎi lún， nǐ de lǎo jiā zěn me yàng？", vi: "Mai còn nóng hơn hôm nay, thật sự không muốn ra ngoài nữa. Helen, quê cậu thế nào?" },
          { role: "海伦", zh: "我老家的夏天跟这里一样，也非常热。", pinyin: "wǒ lǎo jiā de xià tiān gēn zhè lǐ yī yàng， yě fēi cháng rè。", vi: "Mùa hè ở quê tớ giống ở đây, cũng rất nóng." },
          { role: "欧文", zh: "听说这里的夏天和秋天常常刮台风，下大雨。", pinyin: "tīng shuō zhè lǐ de xià tiān hé qiū tiān cháng cháng guā tái fēng， xià dà yǔ。", vi: "Nghe nói mùa hè và mùa thu ở đây thường có bão, mưa lớn." },
          { role: "海伦", zh: "刮台风的话，天气就凉快得多。", pinyin: "guā tái fēng de huà， tiān qì jiù liáng kuài dé duō。", vi: "Nếu có bão thì thời tiết mát hơn nhiều." },
          { role: "欧文", zh: "今年台风什么时候来呢？", pinyin: "jīn nián tái fēng shén me shí hòu lái ne？", vi: "Năm nay bão khi nào đến nhỉ?" },
          { role: "海伦", zh: "听说今年来得比较晚。", pinyin: "tīng shuō jīn nián lái de bǐ jiào wǎn。", vi: "Nghe nói năm nay đến khá muộn." },
          { role: "欧文", zh: "来得晚比不来好，慢慢等吧。", pinyin: "lái de wǎn bǐ bù lái hǎo， màn màn děng ba。", vi: "Đến muộn còn hơn không đến, từ từ chờ vậy." },
          { role: "海伦", zh: "台风还是别来了。刮台风的话，工作和生活会很不方便的。", pinyin: "tái fēng hái shì bié lái le。 guā tái fēng de huà， gōng zuò hé shēng huó huì hěn bù fāng biàn de。", vi: "Thôi đừng để bão đến nữa. Nếu có bão thì công việc và cuộc sống sẽ rất bất tiện." },
        ],
      },

      // ===== Bài 10 =====
      {
        id: "b3-10-1",
        baiNumber: 10,
        baiTitleZh: "足球比赛很精彩",
        baiTitleVi: "Trận bóng đá rất hấp dẫn",
        partLabel: "Bài khóa (1)",
        exchanges: [
          { role: "韩美京", zh: "欧文，听说你是个足球迷。今晚有世界杯比赛，你一定看电视转播吧。", pinyin: "ōu wén， tīng shuō nǐ shì gè zú qiú mí。 jīn wǎn yǒu shì jiè bēi bǐ sài， nǐ yí dìng kàn diàn shì zhuǎn bō ba。", vi: "Owen, nghe nói cậu là fan bóng đá. Tối nay có trận World Cup, cậu chắc chắn sẽ xem truyền hình trực tiếp nhỉ." },
          { role: "欧文", zh: "当然看，今晚是韩国队跟美国队比赛，一定很精彩。韩美京，你也是个足球迷？", pinyin: "dāng rán kàn， jīn wǎn shì hán guó duì gēn měi guó duì bǐ sài， yí dìng hěn jīng cǎi。 hán měi jīng， nǐ yě shì gè zú qiú mí？", vi: "Tất nhiên rồi, tối nay là trận Hàn Quốc gặp Mỹ, chắc chắn rất hấp dẫn. Hàn Mỹ Kinh, cậu cũng là fan bóng đá à?" },
          { role: "韩美京", zh: "对，我跟你一样。你觉得今晚哪个队会赢？", pinyin: "duì， wǒ gēn nǐ yī yàng。 nǐ jué de jīn wǎn nǎ ge duì huì yíng？", vi: "Đúng vậy, tớ giống cậu. Cậu nghĩ tối nay đội nào sẽ thắng?" },
          { role: "欧文", zh: "我觉得韩国队的实力没有美国队强，一定会输。", pinyin: "wǒ jué de hán guó duì de shí lì méi yǒu měi guó duì qiáng， yí dìng huì shū。", vi: "Tớ nghĩ thực lực đội Hàn Quốc không mạnh bằng đội Mỹ, chắc chắn sẽ thua." },
          { role: "韩美京", zh: "我觉得韩国队的技术比美国队好一些，一定会赢。", pinyin: "wǒ jué de hán guó duì de jì shù bǐ měi guó duì hǎo yī xiē， yí dìng huì yíng。", vi: "Tớ thấy kỹ thuật đội Hàn Quốc khá hơn đội Mỹ một chút, chắc chắn sẽ thắng." },
          { role: "欧文", zh: "谁赢谁输，晚上就知道了。", pinyin: "shuí yíng shuí shū， wǎn shàng jiù zhī dào le。", vi: "Ai thắng ai thua, tối nay sẽ rõ." },
          { role: "韩美京", zh: "可是，我房间的电视昨天坏了，不能看了。", pinyin: "kě shì， wǒ fáng jiān de diàn shì zuó tiān huài le， bù néng kàn le。", vi: "Nhưng tivi phòng tớ hôm qua hỏng rồi, không xem được." },
          { role: "欧文", zh: "来我的房间看吧，今天有很多同学来看，很热闹。", pinyin: "lái wǒ de fáng jiān kàn ba， jīn tiān yǒu hěn duō tóng xué lái kàn， hěn rè nào。", vi: "Đến phòng tớ xem đi, hôm nay có rất nhiều bạn đến xem, rất nhộn nhịp." },
          { role: "韩美京", zh: "我能带我的韩国同屋来吗？", pinyin: "wǒ néng dài wǒ de hán guó tóng wū lái ma？", vi: "Tớ có thể dẫn bạn cùng phòng người Hàn của tớ đến không?" },
          { role: "欧文", zh: "非常欢迎。", pinyin: "fēi cháng huān yíng。", vi: "Rất hoan nghênh." },
          { role: "韩美京", zh: "那晚上见。", pinyin: "nà wǎn shàng jiàn。", vi: "Vậy hẹn gặp buổi tối." },
        ],
      },
      {
        id: "b3-10-2",
        baiNumber: 10,
        baiTitleZh: "足球比赛很精彩",
        baiTitleVi: "Trận bóng đá rất hấp dẫn",
        partLabel: "Bài khóa (2)",
        exchanges: [
          { role: "欧文", zh: "比赛快要结束了，还是零比零。", pinyin: "bǐ sài kuài yào jié shù le， hái shì líng bǐ líng。", vi: "Trận đấu sắp kết thúc rồi, vẫn là 0-0." },
          { role: "韩美京", zh: "美国队今天踢得非常好。", pinyin: "měi guó duì jīn tiān tī dé fēi cháng hǎo。", vi: "Đội Mỹ hôm nay đá rất hay." },
          { role: "欧文", zh: "韩国队踢得也不错。", pinyin: "hán guó duì tī dé yě bù cuò。", vi: "Đội Hàn Quốc đá cũng không tệ." },
          { role: "韩美京", zh: "韩国队有很多次好机会，可是都没能进球。", pinyin: "hán guó duì yǒu hěn duō cì hǎo jī huì， kě shì dōu méi néng jìn qiú。", vi: "Đội Hàn Quốc có nhiều cơ hội tốt, nhưng đều không ghi được bàn." },
          { role: "欧文", zh: "美国队也一样，运气不好。", pinyin: "měi guó duì yě yī yàng， yùn qì bù hǎo。", vi: "Đội Mỹ cũng vậy, vận may không tốt." },
          { role: "韩美京", zh: "比赛太紧张了，韩国队加油！欧文，你在给美国队加油吗？", pinyin: "bǐ sài tài jǐn zhāng le， hán guó duì jiā yóu！ ōu wén， nǐ zài gěi měi guó duì jiā yóu ma？", vi: "Trận đấu căng thẳng quá, đội Hàn Quốc cố lên! Owen, cậu đang cổ vũ đội Mỹ à?" },
          { role: "欧文", zh: "当然了，我是美国队球迷。", pinyin: "dāng rán le， wǒ shì měi guó duì qiú mí。", vi: "Đương nhiên rồi, tớ là fan đội Mỹ." },
          { role: "韩美京", zh: "今晚的比赛是不是零比零呢？", pinyin: "jīn wǎn de bǐ sài shì bú shì líng bǐ líng ne？", vi: "Trận đấu tối nay có phải sẽ là 0-0 không nhỉ?" },
          { role: "欧文", zh: "看看谁的运气更好。", pinyin: "kàn kàn shéi de yùn qì gèng hǎo。", vi: "Xem ai may mắn hơn vậy." },
        ],
      },
    ],
  });
})();
