// Dữ liệu hội thoại Msutong Sơ cấp B1 (Bài 1-10)
// Trích từ hoi-thoai-b1-bai-1-10.md — chia thành 20 bài học (mỗi "Bài khóa" = 1 lesson).
// Quy ước: vai xuất hiện đầu tiên trong exchanges → hiển thị bên phải (chat bubble).

window.dialogueData = {
  textbookId: "msutong-b1",
  textbookName: "Msutong Sơ cấp B1",
  lessons: [
    // ===== Bài 1 =====
    {
      id: "b1-1-1",
      baiNumber: 1,
      baiTitleZh: "你好！",
      baiTitleVi: "Xin chào!",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "A", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
        { role: "B", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
      ],
    },
    {
      id: "b1-1-2",
      baiNumber: 1,
      baiTitleZh: "你好！",
      baiTitleVi: "Xin chào!",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "A", zh: "王老师，您好！", pinyin: "wáng lǎo shī， nín hǎo！", vi: "Thầy Vương, em chào thầy ạ!" },
        { role: "B", zh: "您好，王老师！", pinyin: "nín hǎo， wáng lǎo shī！", vi: "Chào thầy, thầy Vương!" },
        { role: "C", zh: "你们好！", pinyin: "nǐ men hǎo！", vi: "Chào các em!" },
      ],
    },

    // ===== Bài 2 =====
    {
      id: "b1-2-1",
      baiNumber: 2,
      baiTitleZh: "你叫什么名字？",
      baiTitleVi: "Bạn tên là gì?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "A", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
        { role: "B", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
        { role: "A", zh: "你叫什么名字？", pinyin: "nǐ jiào shén me míng zì？", vi: "Bạn tên là gì?" },
        { role: "B", zh: "我叫卡玛拉。你呢？", pinyin: "wǒ jiào kǎ mǎ lā。 nǐ ne？", vi: "Tôi tên là Kamala. Còn bạn?" },
        { role: "A", zh: "我叫高小明。你是哪国人？", pinyin: "wǒ jiào gāo xiǎo míng。 nǐ shì nǎ guó rén？", vi: "Tôi tên là Cao Tiểu Minh. Bạn là người nước nào?" },
        { role: "B", zh: "我是南非人。你呢？", pinyin: "wǒ shì nán fēi rén。 nǐ ne？", vi: "Tôi là người Nam Phi. Còn bạn?" },
        { role: "A", zh: "我是中国人。", pinyin: "wǒ shì zhōng guó rén。", vi: "Tôi là người Trung Quốc." },
      ],
    },
    {
      id: "b1-2-2",
      baiNumber: 2,
      baiTitleZh: "你叫什么名字？",
      baiTitleVi: "Bạn tên là gì?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "A", zh: "王老师，您好！", pinyin: "wáng lǎo shī， nín hǎo！", vi: "Thầy Vương, em chào thầy ạ!" },
        { role: "B", zh: "你好！你叫什么名字？", pinyin: "nǐ hǎo！ nǐ jiào shén me míng zì？", vi: "Chào em! Em tên là gì?" },
        { role: "A", zh: "我叫卡玛拉。", pinyin: "wǒ jiào kǎ mǎ lā。", vi: "Em tên là Kamala." },
        { role: "B", zh: "他呢？", pinyin: "tā ne？", vi: "Còn cậu ấy?" },
        { role: "A", zh: "他叫欧文。", pinyin: "tā jiào ōu wén。", vi: "Cậu ấy tên là Owen." },
        { role: "B", zh: "他是哪国人？", pinyin: "tā shì nǎ guó rén？", vi: "Cậu ấy là người nước nào?" },
        { role: "A", zh: "他是美国人。", pinyin: "tā shì měi guó rén。", vi: "Cậu ấy là người Mỹ." },
      ],
    },

    // ===== Bài 3 =====
    {
      id: "b1-3-1",
      baiNumber: 3,
      baiTitleZh: "很高兴认识你",
      baiTitleVi: "Rất vui được làm quen với bạn",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "A", zh: "请问，您贵姓？", pinyin: "qǐng wèn， nín guì xìng？", vi: "Xin hỏi, ông/bà quý tánh là gì ạ?" },
        { role: "B", zh: "我姓马。您呢？", pinyin: "wǒ xìng mǎ。 nín ne？", vi: "Tôi họ Mã. Còn ông/bà?" },
        { role: "A", zh: "我姓高。这是我的名片。", pinyin: "wǒ xìng gāo。 zhè shì wǒ de míng piàn。", vi: "Tôi họ Cao. Đây là danh thiếp của tôi." },
        { role: "B", zh: "对不起，我没有名片。", pinyin: "duì bù qǐ， wǒ méi yǒu míng piàn。", vi: "Xin lỗi, tôi không có danh thiếp." },
        { role: "A", zh: "没关系。很高兴认识你！", pinyin: "méi guān xì。 hěn gāo xìng rèn shí nǐ！", vi: "Không sao. Rất vui được làm quen với bạn!" },
        { role: "B", zh: "高先生，认识你我也很高兴！", pinyin: "gāo xiān shēng， rèn shí nǐ wǒ yě hěn gāo xìng！", vi: "Ông Cao, làm quen với ông tôi cũng rất vui!" },
      ],
    },
    {
      id: "b1-3-2",
      baiNumber: 3,
      baiTitleZh: "很高兴认识你",
      baiTitleVi: "Rất vui được làm quen với bạn",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "A", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
        { role: "B", zh: "你好！", pinyin: "nǐ hǎo！", vi: "Xin chào!" },
        { role: "A", zh: "请问，你叫什么名字？", pinyin: "qǐng wèn， nǐ jiào shén me míng zì？", vi: "Xin hỏi, bạn tên là gì?" },
        { role: "B", zh: "我叫黄文丽。你呢？", pinyin: "wǒ jiào huáng wén lì。 nǐ ne？", vi: "Tôi tên là Hoàng Văn Lệ. Còn bạn?" },
        { role: "A", zh: "我叫欧文。你是中国人吗？", pinyin: "wǒ jiào ōu wén。 nǐ shì zhōng guó rén ma？", vi: "Tôi tên là Owen. Bạn là người Trung Quốc phải không?" },
        { role: "B", zh: "是，你是英国人吗？", pinyin: "shì， nǐ shì yīng guó rén ma？", vi: "Vâng, bạn là người Anh phải không?" },
        { role: "A", zh: "不，我不是英国人，我是美国人。", pinyin: "bù， wǒ bú shì yīng guó rén， wǒ shì měi guó rén。", vi: "Không, tôi không phải là người Anh, tôi là người Mỹ." },
        { role: "B", zh: "认识你很高兴！", pinyin: "rèn shí nǐ hěn gāo xìng！", vi: "Rất vui được làm quen với bạn!" },
        { role: "A", zh: "认识你我也很高兴！", pinyin: "rèn shí nǐ wǒ yě hěn gāo xìng！", vi: "Làm quen với bạn tôi cũng rất vui!" },
      ],
    },

    // ===== Bài 4 =====
    {
      id: "b1-4-1",
      baiNumber: 4,
      baiTitleZh: "你去哪儿？",
      baiTitleVi: "Bạn đi đâu?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "A", zh: "小姐，你好！", pinyin: "xiǎo jiě， nǐ hǎo！", vi: "Cô ơi, chào cô!" },
        { role: "B", zh: "你好，师傅！", pinyin: "nǐ hǎo， shī fù！", vi: "Chào bác tài!" },
        { role: "A", zh: "你去哪儿？", pinyin: "nǐ qù nǎ ér？", vi: "Cô đi đâu?" },
        { role: "B", zh: "我去人民广场。", pinyin: "wǒ qù rén mín guǎng chǎng。", vi: "Tôi đi Quảng trường Nhân Dân." },
        { role: "A", zh: "什么？", pinyin: "shén me？", vi: "Gì cơ?" },
        { role: "B", zh: "我去人民广场。", pinyin: "wǒ qù rén mín guǎng chǎng。", vi: "Tôi đi Quảng trường Nhân Dân." },
        { role: "A", zh: "好，知道了。", pinyin: "hǎo， zhī dào le。", vi: "Được, tôi biết rồi." },
        { role: "B", zh: "人民广场远不远？", pinyin: "rén mín guǎng chǎng yuǎn bù yuǎn？", vi: "Quảng trường Nhân Dân có xa không?" },
        { role: "A", zh: "不远，很近。", pinyin: "bù yuǎn， hěn jìn。", vi: "Không xa, gần lắm." },
      ],
    },
    {
      id: "b1-4-2",
      baiNumber: 4,
      baiTitleZh: "你去哪儿？",
      baiTitleVi: "Bạn đi đâu?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "A", zh: "人民广场到了。", pinyin: "rén mín guǎng chǎng dào le。", vi: "Đến Quảng trường Nhân Dân rồi." },
        { role: "B", zh: "多少钱？", pinyin: "duō shǎo qián？", vi: "Bao nhiêu tiền ạ?" },
        { role: "A", zh: "二十九块。", pinyin: "èr shí jiǔ kuài。", vi: "Hai mươi chín tệ." },
        { role: "B", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        { role: "A", zh: "不客气！再见！", pinyin: "bú kè qì！ zài jiàn！", vi: "Không có gì! Tạm biệt!" },
        { role: "B", zh: "再见！", pinyin: "zài jiàn！", vi: "Tạm biệt!" },
      ],
    },

    // ===== Bài 5 =====
    {
      id: "b1-5-1",
      baiNumber: 5,
      baiTitleZh: "你要吃什么？",
      baiTitleVi: "Bạn muốn ăn gì?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "A", zh: "先生，您要吃点儿什么？", pinyin: "xiān shēng， nín yào chī diǎn ér shén me？", vi: "Anh ơi, anh muốn ăn gì ạ?" },
        { role: "B", zh: "我要一个牛肉，一个青菜。", pinyin: "wǒ yào yí gè niú ròu， yí gè qīng cài。", vi: "Cho tôi một phần thịt bò, một phần rau xanh." },
        { role: "A", zh: "还要什么？", pinyin: "hái yào shén me？", vi: "Anh còn muốn gì nữa không?" },
        { role: "B", zh: "两碗米饭。", pinyin: "liǎng wǎn mǐ fàn。", vi: "Hai bát cơm." },
        { role: "A", zh: "好，还要什么？", pinyin: "hǎo， hái yào shén me？", vi: "Vâng, còn gì nữa không ạ?" },
        { role: "B", zh: "不要了，多少钱？", pinyin: "bú yào le， duō shǎo qián？", vi: "Không cần nữa, bao nhiêu tiền?" },
        { role: "A", zh: "五十块。", pinyin: "wǔ shí kuài。", vi: "Năm mươi tệ." },
        { role: "B", zh: "好。请快一点儿，我很饿。", pinyin: "hǎo。 qǐng kuài yì diǎn ér， wǒ hěn è。", vi: "Được. Làm nhanh một chút, tôi đói lắm rồi." },
        { role: "A", zh: "好。", pinyin: "hǎo。", vi: "Vâng." },
        { role: "B", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
      ],
    },
    {
      id: "b1-5-2",
      baiNumber: 5,
      baiTitleZh: "你要吃什么？",
      baiTitleVi: "Bạn muốn ăn gì?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "A", zh: "请问，您要喝点儿什么？", pinyin: "qǐng wèn， nín yào hē diǎn ér shén me？", vi: "Xin hỏi, anh/chị muốn uống gì ạ?" },
        { role: "B", zh: "我要一杯奶茶。", pinyin: "wǒ yào yī bēi nǎi chá。", vi: "Cho tôi một cốc trà sữa." },
        { role: "A", zh: "大杯还是小杯？", pinyin: "dà bēi hái shì xiǎo bēi？", vi: "Cốc to hay cốc nhỏ?" },
        { role: "B", zh: "小杯。", pinyin: "xiǎo bēi。", vi: "Cốc nhỏ." },
        { role: "A", zh: "好，还要什么？", pinyin: "hǎo， hái yào shén me？", vi: "Vâng, còn gì nữa không?" },
        { role: "B", zh: "还要一杯咖啡。", pinyin: "hái yào yī bēi kā fēi。", vi: "Cho thêm một cốc cà phê." },
        { role: "A", zh: "大杯还是小杯？", pinyin: "dà bēi hái shì xiǎo bēi？", vi: "Cốc to hay cốc nhỏ?" },
        { role: "B", zh: "大杯。", pinyin: "dà bēi。", vi: "Cốc to." },
        { role: "A", zh: "好。一共二十八块。", pinyin: "hǎo。 yī gòng èr shí bā kuài。", vi: "Vâng. Tổng cộng hai mươi tám tệ." },
        { role: "B", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        { role: "A", zh: "不客气！", pinyin: "bú kè qì！", vi: "Không có gì!" },
      ],
    },

    // ===== Bài 6 =====
    {
      id: "b1-6-1",
      baiNumber: 6,
      baiTitleZh: "你在哪儿工作？",
      baiTitleVi: "Bạn làm việc ở đâu?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "马文", zh: "你好！你叫什么名字？", pinyin: "nǐ hǎo！ nǐ jiào shén me míng zì？", vi: "Xin chào! Bạn tên là gì?" },
        { role: "海伦", zh: "我叫海伦。你呢？", pinyin: "wǒ jiào hǎi lún。 nǐ ne？", vi: "Tôi tên là Helen. Còn bạn?" },
        { role: "马文", zh: "我叫马文。海伦小姐，你是哪国人？", pinyin: "wǒ jiào mǎ wén。 hǎi lún xiǎo jiě， nǐ shì nǎ guó rén？", vi: "Tôi tên là Mã Văn. Cô Helen, cô là người nước nào?" },
        { role: "海伦", zh: "我是美国人。马先生，你是北京人吗？", pinyin: "wǒ shì měi guó rén。 mǎ xiān shēng， nǐ shì běi jīng rén ma？", vi: "Tôi là người Mỹ. Anh Mã, anh là người Bắc Kinh phải không?" },
        { role: "马文", zh: "不是，我是上海人。", pinyin: "bú shì， wǒ shì shàng hǎi rén。", vi: "Không, tôi là người Thượng Hải." },
        { role: "海伦", zh: "你在哪儿工作？", pinyin: "nǐ zài nǎ ér gōng zuò？", vi: "Anh làm việc ở đâu?" },
        { role: "马文", zh: "我在苹果公司工作，这是我的名片。", pinyin: "wǒ zài píng guǒ gōng sī gōng zuò， zhè shì wǒ de míng piàn。", vi: "Tôi làm việc ở công ty Apple, đây là danh thiếp của tôi." },
        { role: "海伦", zh: "谢谢！对不起，我没有名片，我是留学生。", pinyin: "xiè xiè！ duì bù qǐ， wǒ méi yǒu míng piàn， wǒ shì liú xué shēng。", vi: "Cảm ơn anh! Xin lỗi, tôi không có danh thiếp, tôi là du học sinh." },
        { role: "马文", zh: "没关系！你在这儿学习汉语？", pinyin: "méi guān xì！ nǐ zài zhè ér xué xí hàn yǔ？", vi: "Không sao! Cô học tiếng Hán ở đây à?" },
        { role: "海伦", zh: "对。", pinyin: "duì。", vi: "Vâng, đúng vậy." },
        { role: "马文", zh: "海伦小姐，很高兴认识你！", pinyin: "hǎi lún xiǎo jiě， hěn gāo xìng rèn shí nǐ！", vi: "Cô Helen, rất vui được làm quen với cô!" },
        { role: "海伦", zh: "我也很高兴认识你！", pinyin: "wǒ yě hěn gāo xìng rèn shí nǐ！", vi: "Tôi cũng rất vui được làm quen với anh!" },
      ],
    },
    {
      id: "b1-6-2",
      baiNumber: 6,
      baiTitleZh: "你在哪儿工作？",
      baiTitleVi: "Bạn làm việc ở đâu?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "高小明", zh: "海伦，这是你男朋友吗？", pinyin: "hǎi lún， zhè shì nǐ nán péng yǒu ma？", vi: "Helen, đây là bạn trai của cậu phải không?" },
        { role: "海伦", zh: "是。", pinyin: "shì。", vi: "Đúng vậy." },
        { role: "高小明", zh: "他也是美国人吗？", pinyin: "tā yě shì měi guó rén ma？", vi: "Anh ấy cũng là người Mỹ à?" },
        { role: "海伦", zh: "不是，他是英国人。", pinyin: "bú shì， tā shì yīng guó rén。", vi: "Không, anh ấy là người Anh." },
        { role: "高小明", zh: "他也在这儿学汉语吗？", pinyin: "tā yě zài zhè ér xué hàn yǔ ma？", vi: "Anh ấy cũng học tiếng Hán ở đây à?" },
        { role: "海伦", zh: "不，他在这儿工作。", pinyin: "bù， tā zài zhè ér gōng zuò。", vi: "Không, anh ấy làm việc ở đây." },
        { role: "高小明", zh: "他做什么工作？", pinyin: "tā zuò shén me gōng zuò？", vi: "Anh ấy làm công việc gì?" },
        { role: "海伦", zh: "他在大学教英语。", pinyin: "tā zài dà xué jiào yīng yǔ。", vi: "Anh ấy dạy tiếng Anh ở trường đại học." },
        { role: "高小明", zh: "是吗？我女朋友也是英语老师。", pinyin: "shì ma？ wǒ nǚ péng yǒu yě shì yīng yǔ lǎo shī。", vi: "Vậy à? Bạn gái của tớ cũng là giáo viên tiếng Anh." },
        { role: "海伦", zh: "是吗？她也是大学老师吗？", pinyin: "shì ma？ tā yě shì dà xué lǎo shī ma？", vi: "Thật à? Cô ấy cũng là giáo viên đại học sao?" },
        { role: "高小明", zh: "不是，她是中学老师。", pinyin: "bú shì， tā shì zhōng xué lǎo shī。", vi: "Không, cô ấy là giáo viên trung học." },
      ],
    },

    // ===== Bài 7 =====
    {
      id: "b1-7-1",
      baiNumber: 7,
      baiTitleZh: "中国银行在哪儿？",
      baiTitleVi: "Ngân hàng Trung Quốc ở đâu?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "海伦", zh: "小明，这附近有银行吗？", pinyin: "xiǎo míng， zhè fù jìn yǒu yín háng ma？", vi: "Tiểu Minh, gần đây có ngân hàng không?" },
        { role: "高小明", zh: "有，有一家中国银行。", pinyin: "yǒu， yǒu yī jiā zhōng guó yín háng。", vi: "Có, có một ngân hàng Trung Quốc." },
        { role: "海伦", zh: "有没有北京银行？", pinyin: "yǒu méi yǒu běi jīng yín háng？", vi: "Có ngân hàng Bắc Kinh không?" },
        { role: "高小明", zh: "没有。", pinyin: "méi yǒu。", vi: "Không có." },
        { role: "海伦", zh: "中国银行在哪儿？", pinyin: "zhōng guó yín háng zài nǎ ér？", vi: "Ngân hàng Trung Quốc ở đâu?" },
        { role: "高小明", zh: "从这儿往前走，然后再往左拐，有一家饭店，银行就在饭店对面。", pinyin: "cóng zhè ér wǎng qián zǒu， rán hòu zài wǎng zuǒ guǎi， yǒu yī jiā fàn diàn， yín háng jiù zài fàn diàn duì miàn。", vi: "Từ đây đi thẳng về phía trước, sau đó rẽ trái, có một nhà hàng, ngân hàng ở đối diện nhà hàng đó." },
        { role: "海伦", zh: "是四川饭店吗？", pinyin: "shì sì chuān fàn diàn ma？", vi: "Có phải là nhà hàng Tứ Xuyên không?" },
        { role: "高小明", zh: "是。", pinyin: "shì。", vi: "Đúng vậy." },
        { role: "海伦", zh: "知道了，谢谢！", pinyin: "zhī dào le， xiè xiè！", vi: "Tôi biết rồi, cảm ơn!" },
        { role: "高小明", zh: "不客气！", pinyin: "bú kè qì！", vi: "Không có gì!" },
      ],
    },
    {
      id: "b1-7-2",
      baiNumber: 7,
      baiTitleZh: "中国银行在哪儿？",
      baiTitleVi: "Ngân hàng Trung Quốc ở đâu?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "欧文", zh: "文丽，这附近有书店吗？", pinyin: "wén lì， zhè fù jìn yǒu shū diàn ma？", vi: "Văn Lệ, gần đây có hiệu sách không?" },
        { role: "黄文丽", zh: "有一家书店。", pinyin: "yǒu yī jiā shū diàn。", vi: "Có một hiệu sách." },
        { role: "欧文", zh: "书店在哪儿？", pinyin: "shū diàn zài nǎ ér？", vi: "Hiệu sách ở đâu?" },
        { role: "黄文丽", zh: "在超市对面。", pinyin: "zài chāo shì duì miàn。", vi: "Ở đối diện siêu thị." },
        { role: "欧文", zh: "什么超市？", pinyin: "shén me chāo shì？", vi: "Siêu thị nào?" },
        { role: "黄文丽", zh: "全家超市，你知道吗？", pinyin: "quán jiā chāo shì， nǐ zhī dào ma？", vi: "Siêu thị Family Mart, anh biết không?" },
        { role: "欧文", zh: "不知道，全家超市在哪儿？", pinyin: "bù zhī dào， quán jiā chāo shì zài nǎ ér？", vi: "Không biết, siêu thị Family Mart ở đâu?" },
        { role: "黄文丽", zh: "从这儿往前走，然后再往右拐，有一家中国银行，全家超市就在银行对面。", pinyin: "cóng zhè ér wǎng qián zǒu， rán hòu zài wǎng yòu guǎi， yǒu yī jiā zhōng guó yín háng， quán jiā chāo shì jiù zài yín háng duì miàn。", vi: "Từ đây đi thẳng về phía trước, sau đó rẽ phải, có một ngân hàng Trung Quốc, siêu thị Family Mart ở đối diện ngân hàng." },
        { role: "欧文", zh: "远吗？", pinyin: "yuǎn ma？", vi: "Có xa không?" },
        { role: "黄文丽", zh: "不远。", pinyin: "bù yuǎn。", vi: "Không xa." },
        { role: "欧文", zh: "谢谢！", pinyin: "xiè xiè！", vi: "Cảm ơn!" },
        { role: "黄文丽", zh: "不客气！", pinyin: "bú kè qì！", vi: "Không có gì!" },
      ],
    },

    // ===== Bài 8 =====
    {
      id: "b1-8-1",
      baiNumber: 8,
      baiTitleZh: "你的生日是几月几号？",
      baiTitleVi: "Sinh nhật của bạn là ngày tháng nào?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "欧文", zh: "文丽，你今天真漂亮，有什么事吗？", pinyin: "wén lì， nǐ jīn tiān zhēn piào liàng， yǒu shén me shì ma？", vi: "Văn Lệ, hôm nay em thật xinh, có chuyện gì vậy?" },
        { role: "黄文丽", zh: "今天是我的生日。", pinyin: "jīn tiān shì wǒ de shēng rì。", vi: "Hôm nay là sinh nhật của em." },
        { role: "欧文", zh: "是吗？今天几号？", pinyin: "shì ma？ jīn tiān jǐ hào？", vi: "Thật sao? Hôm nay là ngày bao nhiêu?" },
        { role: "黄文丽", zh: "今天六月十五号。", pinyin: "jīn tiān liù yuè shí wǔ hào。", vi: "Hôm nay là ngày 15 tháng 6." },
        { role: "欧文", zh: "你的生日是六月十五号，生日快乐！", pinyin: "nǐ de shēng rì shì liù yuè shí wǔ hào， shēng rì kuài lè！", vi: "Sinh nhật của em là ngày 15 tháng 6, chúc mừng sinh nhật!" },
        { role: "黄文丽", zh: "谢谢！欧文，你的生日是几月几号？", pinyin: "xiè xiè！ ōu wén， nǐ de shēng rì shì jǐ yuè jǐ hào？", vi: "Cảm ơn anh! Owen, sinh nhật của anh là ngày tháng nào?" },
        { role: "欧文", zh: "我的生日九月十四号。", pinyin: "wǒ de shēng rì jiǔ yuè shí sì hào。", vi: "Sinh nhật của anh là ngày 14 tháng 9." },
        { role: "黄文丽", zh: "今天晚上你有空儿吗？我想请你吃晚饭。", pinyin: "jīn tiān wǎn shàng nǐ yǒu kòng er ma？ wǒ xiǎng qǐng nǐ chī wǎn fàn。", vi: "Tối nay anh có rảnh không? Em muốn mời anh ăn tối." },
        { role: "欧文", zh: "有空儿，谢谢你！那我请你喝咖啡，好吗？", pinyin: "yǒu kòng er， xiè xiè nǐ！ nà wǒ qǐng nǐ hē kā fēi， hǎo ma？", vi: "Có rảnh, cảm ơn em! Vậy anh mời em uống cà phê, được không?" },
        { role: "黄文丽", zh: "好！谢谢！", pinyin: "hǎo！ xiè xiè！", vi: "Được! Cảm ơn anh!" },
      ],
    },
    {
      id: "b1-8-2",
      baiNumber: 8,
      baiTitleZh: "你的生日是几月几号？",
      baiTitleVi: "Sinh nhật của bạn là ngày tháng nào?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "高小明", zh: "海伦，你星期五晚上有空儿吗？", pinyin: "hǎi lún， nǐ xīng qī wǔ wǎn shàng yǒu kòng er ma？", vi: "Helen, tối thứ Sáu cậu có rảnh không?" },
        { role: "海伦", zh: "有空儿，什么事？", pinyin: "yǒu kòng er， shén me shì？", vi: "Có rảnh, có chuyện gì vậy?" },
        { role: "高小明", zh: "我想请你吃晚饭。", pinyin: "wǒ xiǎng qǐng nǐ chī wǎn fàn。", vi: "Tớ muốn mời cậu ăn tối." },
        { role: "海伦", zh: "为什么？", pinyin: "wèi shén me？", vi: "Tại sao?" },
        { role: "高小明", zh: "星期五是我的生日。", pinyin: "xīng qī wǔ shì wǒ de shēng rì。", vi: "Thứ Sáu là sinh nhật của tớ." },
        { role: "海伦", zh: "太好了！谢谢！那星期五晚上我请你看电影，好吗？", pinyin: "tài hǎo le！ xiè xiè！ nà xīng qī wǔ wǎn shàng wǒ qǐng nǐ kàn diàn yǐng， hǎo ma？", vi: "Tuyệt quá! Cảm ơn! Vậy tối thứ Sáu tớ mời cậu xem phim, được không?" },
        { role: "高小明", zh: "好，谢谢你！你的生日是几月几号？", pinyin: "hǎo， xiè xiè nǐ！ nǐ de shēng rì shì jǐ yuè jǐ hào？", vi: "Được, cảm ơn cậu! Sinh nhật của cậu là ngày tháng nào?" },
        { role: "海伦", zh: "十二月二十一号。", pinyin: "shí èr yuè èr shí yī hào。", vi: "Ngày 21 tháng 12." },
        { role: "高小明", zh: "哦，还远。星期五我们去四川饭店，好吗？", pinyin: "ó， hái yuǎn。 xīng qī wǔ wǒ men qù sì chuān fàn diàn， hǎo ma？", vi: "Ồ, còn xa. Thứ Sáu chúng ta đi nhà hàng Tứ Xuyên, được không?" },
        { role: "海伦", zh: "好！是学校对面的四川饭店吗？", pinyin: "hǎo！ shì xué xiào duì miàn de sì chuān fàn diàn ma？", vi: "Được! Là nhà hàng Tứ Xuyên đối diện trường học phải không?" },
        { role: "高小明", zh: "对！星期五晚上见！", pinyin: "duì！ xīng qī wǔ wǎn shàng jiàn！", vi: "Đúng vậy! Hẹn gặp tối thứ Sáu!" },
      ],
    },

    // ===== Bài 9 =====
    {
      id: "b1-9-1",
      baiNumber: 9,
      baiTitleZh: "你喜欢中国电影还是美国电影？",
      baiTitleVi: "Bạn thích phim Trung Quốc hay phim Mỹ?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "卡玛拉", zh: "小明，你喜不喜欢看电影？", pinyin: "xiǎo míng， nǐ xǐ bù xǐ huān kàn diàn yǐng？", vi: "Tiểu Minh, cậu có thích xem phim không?" },
        { role: "小明", zh: "非常喜欢。你呢？", pinyin: "fēi cháng xǐ huān。 nǐ ne？", vi: "Rất thích. Còn cậu?" },
        { role: "卡玛拉", zh: "我也很喜欢。你喜欢中国电影还是美国电影？", pinyin: "wǒ yě hěn xǐ huān。 nǐ xǐ huān zhōng guó diàn yǐng hái shì měi guó diàn yǐng？", vi: "Tớ cũng rất thích. Cậu thích phim Trung Quốc hay phim Mỹ?" },
        { role: "小明", zh: "都喜欢。你呢？", pinyin: "dōu xǐ huān。 nǐ ne？", vi: "Tớ thích cả hai. Còn cậu?" },
        { role: "卡玛拉", zh: "我喜欢看中国电影。", pinyin: "wǒ xǐ huān kàn zhòng guó diàn yǐng。", vi: "Tớ thích xem phim Trung Quốc." },
        { role: "小明", zh: "明天晚上我去看电影，你想看吗？", pinyin: "míng tiān wǎn shàng wǒ qù kàn diàn yǐng， nǐ xiǎng kàn ma？", vi: "Tối mai tớ đi xem phim, cậu có muốn xem không?" },
        { role: "卡玛拉", zh: "想看，电影院远不远？", pinyin: "xiǎng kàn， diàn yǐng yuàn yuǎn bù yuǎn？", vi: "Muốn chứ, rạp phim có xa không?" },
        { role: "小明", zh: "电影院很远。", pinyin: "diàn yǐng yuàn hěn yuǎn。", vi: "Rạp phim xa lắm." },
        { role: "卡玛拉", zh: "我们怎么去？坐地铁去还是坐出租车去？", pinyin: "wǒ men zěn me qù？ zuò dì tiě qù hái shì zuò chū zū chē qù？", vi: "Chúng ta đi như thế nào? Đi tàu điện ngầm hay đi taxi?" },
        { role: "小明", zh: "坐地铁吧，又快又便宜，怎么样？", pinyin: "zuò dì tiě ba， yòu kuài yòu pián yi， zěn me yàng？", vi: "Đi tàu điện ngầm đi, vừa nhanh vừa rẻ, thế nào?" },
        { role: "卡玛拉", zh: "好，我们坐地铁去。", pinyin: "hǎo， wǒ men zuò dì tiě qù。", vi: "Được, chúng ta đi tàu điện ngầm." },
      ],
    },
    {
      id: "b1-9-2",
      baiNumber: 9,
      baiTitleZh: "你喜欢中国电影还是美国电影？",
      baiTitleVi: "Bạn thích phim Trung Quốc hay phim Mỹ?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "韩美京", zh: "欧文，你喜欢吃中国菜还是韩国菜？", pinyin: "ōu wén， nǐ xǐ huān chī zhōng guó cài hái shì hán guó cài？", vi: "Owen, anh thích ăn món Trung Quốc hay món Hàn Quốc?" },
        { role: "欧文", zh: "我都喜欢。你呢？", pinyin: "wǒ dōu xǐ huān。 nǐ ne？", vi: "Anh thích cả hai. Còn em?" },
        { role: "韩美京", zh: "我也是。", pinyin: "wǒ yě shì。", vi: "Em cũng vậy." },
        { role: "欧文", zh: "那我们今天吃什么？中国菜还是韩国菜？", pinyin: "nà wǒ men jīn tiān chī shén me？ zhōng guó cài hái shì hán guó cài？", vi: "Vậy hôm nay chúng ta ăn gì? Món Trung Quốc hay món Hàn Quốc?" },
        { role: "韩美京", zh: "吃韩国菜怎么样？", pinyin: "chī hán guó cài zěn me yàng？", vi: "Ăn món Hàn Quốc thế nào?" },
        { role: "欧文", zh: "好！", pinyin: "hǎo！", vi: "Được!" },
        { role: "韩美京", zh: "我知道一家韩国饭店，很有名，那儿的菜又好吃又便宜。", pinyin: "wǒ zhī dào yī jiā hán guó fàn diàn， hěn yǒu míng， nà ér de cài yòu hǎo chī yòu pián yi。", vi: "Em biết một nhà hàng Hàn Quốc, rất nổi tiếng, món ăn ở đó vừa ngon vừa rẻ." },
        { role: "欧文", zh: "那家饭店在哪儿？", pinyin: "nà jiā fàn diàn zài nǎ ér？", vi: "Nhà hàng đó ở đâu?" },
        { role: "韩美京", zh: "在人民公园附近。", pinyin: "zài rén mín gōng yuán fù jìn。", vi: "Ở gần Công viên Nhân Dân." },
        { role: "欧文", zh: "我们怎么去？走路去还是坐公交车去？", pinyin: "wǒ men zěn me qù？ zǒu lù qù hái shì zuò gōng jiāo chē qù？", vi: "Chúng ta đi thế nào? Đi bộ hay đi xe buýt?" },
        { role: "韩美京", zh: "走路去吧，人民公园很近。", pinyin: "zǒu lù qù ba， rén mín gōng yuán hěn jìn。", vi: "Đi bộ đi, Công viên Nhân Dân gần lắm." },
        { role: "欧文", zh: "好！", pinyin: "hǎo！", vi: "Được!" },
      ],
    },

    // ===== Bài 10 =====
    {
      id: "b1-10-1",
      baiNumber: 10,
      baiTitleZh: "你家有几口人？",
      baiTitleVi: "Nhà bạn có mấy người?",
      partLabel: "Bài khóa (1)",
      exchanges: [
        { role: "欧文", zh: "你家有几口人？", pinyin: "nǐ jiā yǒu jǐ kǒu rén？", vi: "Nhà cậu có mấy người?" },
        { role: "海伦", zh: "我家有五口人，爸爸、妈妈、一个弟弟、一个妹妹，还有我。你看，这是他们的照片。", pinyin: "wǒ jiā yǒu wǔ kǒu rén， bà bà、 mā mā、 yí gè dì di、 yí gè mèi mèi， hái yǒu wǒ。 nǐ kàn， zhè shì tā men de zhào piān。", vi: "Nhà tớ có năm người: bố, mẹ, một em trai, một em gái, và tớ. Cậu xem này, đây là ảnh của họ." },
        { role: "欧文", zh: "你爸爸、妈妈做什么工作？", pinyin: "nǐ bà bà、 mā mā zuò shén me gōng zuò？", vi: "Bố mẹ cậu làm công việc gì?" },
        { role: "海伦", zh: "我爸爸是律师，我妈妈不工作。", pinyin: "wǒ bà bà shì lǜ shī， wǒ mā mā bù gōng zuò。", vi: "Bố tớ là luật sư, mẹ tớ không đi làm." },
        { role: "欧文", zh: "你弟弟和妹妹都是学生吗？", pinyin: "nǐ dì di hé mèi mèi dōu shì xué shēng ma？", vi: "Em trai và em gái cậu đều là học sinh à?" },
        { role: "海伦", zh: "对，我弟弟是大学生，我妹妹是中学生。", pinyin: "duì， wǒ dì di shì dà xué shēng， wǒ mèi mèi shì zhōng xué shēng。", vi: "Đúng vậy, em trai tớ là sinh viên đại học, em gái tớ là học sinh trung học." },
        { role: "欧文", zh: "你妹妹今年多大？", pinyin: "nǐ mèi mèi jīn nián duō dà？", vi: "Em gái cậu năm nay bao nhiêu tuổi?" },
        { role: "海伦", zh: "十二岁。", pinyin: "shí èr suì。", vi: "Mười hai tuổi." },
        { role: "欧文", zh: "你的家人都在美国吗？", pinyin: "nǐ de jiā rén dōu zài měi guó ma？", vi: "Người nhà của cậu đều ở Mỹ à?" },
        { role: "海伦", zh: "对，他们都在美国。", pinyin: "duì， tā men dōu zài měi guó。", vi: "Đúng vậy, họ đều ở Mỹ." },
      ],
    },
    {
      id: "b1-10-2",
      baiNumber: 10,
      baiTitleZh: "你家有几口人？",
      baiTitleVi: "Nhà bạn có mấy người?",
      partLabel: "Bài khóa (2)",
      exchanges: [
        { role: "高小明", zh: "美京，这是你家人的照片吗？", pinyin: "měi jīng， zhè shì nǐ jiā rén de zhào piān ma？", vi: "Mỹ Kinh, đây là ảnh người nhà của cậu phải không?" },
        { role: "韩美京", zh: "是。", pinyin: "shì。", vi: "Đúng vậy." },
        { role: "高小明", zh: "他是谁？是你哥哥吗？", pinyin: "tā shì shuí？ shì nǐ gē gē ma？", vi: "Anh ấy là ai? Anh trai của cậu phải không?" },
        { role: "韩美京", zh: "不是，他是我姐姐的男朋友。这是我的爸爸、妈妈，这是我哥哥、姐姐。", pinyin: "bú shì， tā shì wǒ jiě jiě de nán péng yǒu。 zhè shì wǒ de bà bà、 mā mā， zhè shì wǒ gē gē、 jiě jiě。", vi: "Không, anh ấy là bạn trai của chị tớ. Đây là bố mẹ tớ, đây là anh trai và chị gái tớ." },
        { role: "高小明", zh: "你家还有一只狗？", pinyin: "nǐ jiā hái yǒu yī zhī gǒu？", vi: "Nhà cậu còn có một con chó nữa à?" },
        { role: "韩美京", zh: "对，她是我妹妹。她又漂亮又可爱，我很喜欢她。", pinyin: "duì， tā shì wǒ mèi mèi。 tā yòu piào liàng yòu kě ài， wǒ hěn xǐ huān tā。", vi: "Đúng vậy, nó là em gái của tớ. Nó vừa xinh vừa đáng yêu, tớ rất thích nó." },
        { role: "高小明", zh: "她多大？", pinyin: "tā duō dà？", vi: "Nó bao nhiêu tuổi?" },
        { role: "韩美京", zh: "她今年三岁。", pinyin: "tā jīn nián sān suì。", vi: "Năm nay nó ba tuổi." },
        { role: "高小明", zh: "你哥哥、姐姐做什么工作？", pinyin: "nǐ gē gē、 jiě jiě zuò shén me gōng zuò？", vi: "Anh chị của cậu làm công việc gì?" },
        { role: "韩美京", zh: "我哥哥是医生，姐姐是律师。", pinyin: "wǒ gē gē shì yī shēng， jiě jiě shì lǜ shī。", vi: "Anh tớ là bác sĩ, chị tớ là luật sư." },
      ],
    },
  ],
};
